"""Question-level evidence transcribed from the paper and its verified marking guidelines.

Do not silently correct source errors. LOCATORS retains source pages and shared context.
"""

PAPER = {'paper_key': 'BIO-2022-CIRC',
 'paper_path': 'data/organized/biology/Class test- circulation.pdf',
 'memo_path': 'data/organized/biology/Class test- circulation MG.pdf',
 'year': 2022,
 'exam_date': '16 MAY 2022',
 'exam_period': 'may',
 'paper_type': 'class_test',
 'exam_board': 'internal',
 'total_marks': 50,
 'question_totals': [10, 15, 15, 10],
 'examiner': 'MRS S. STEGMANN',
 'moderator': 'MRS B. ZAJAC',
 'duration_stated': '50 MINUTES',
 'fidelity_rung': 'A',
 'notes': 'Read directly from digital PDF text. Whitespace normalized, blank answer lines and repeating headers '
          'omitted. Lettered subparts retain source letters; rowN identifies an unnumbered matching row. '
          'Image-dependent evidence is unresolved, not reconstructed.',
 'alignment_anchors': {'memo': 'Contractions arise within the muscle itself.',
                       'paper': 'The heart muscle is myogenic. Define this term.'}}

SCHEMA = ('qn',
 'marks',
 'topic',
 'qtype',
 'text',
 'has_diagram',
 'formulae',
 'memo_answer',
 'memo_steps',
 'memo_notes',
 'needs_visual',
 'ocr_uncertain')

RECORDS = [('1.1.1',
  1,
  'Transport in animals',
  'Multiple Choice',
  'Which statement is incorrect regarding the heart? A. Its walls are made up of striated voluntary muscle B. It '
  'is situated in a space between the lungs called the mediastinum C. Internally it is divided into four chambers '
  'D. The upper atria are receiving chambers with relatively thin walls',
  False,
  [],
  'A ✓',
  ['A'],
  'A ✓',
  False,
  False),
 ('1.1.2',
  1,
  'Transport in animals',
  'Multiple Choice',
  'Mammals are said to have a “double circulation” because… A. blood makes two full circuits of the body every '
  'five minutes. B. There are two blood circuits from the heart: one to the lungs and the other to the rest of '
  'the body. C. Each organ is served by two vessels: an artery and a vein. D. The heart has two valves, thus '
  'providing double the circulatory power of other hearts.',
  False,
  [],
  'B ✓',
  ['B'],
  'B ✓',
  False,
  False),
 ('1.1.3',
  1,
  'Transport in animals',
  'Multiple Choice',
  'The following events occur during a heartbeat. i. Semilunar valves forced open ii. Blood flows into atria iii. '
  'Both ventricles contract iv. Mitral and tricuspid valves open Select the correct order in which these events '
  'occur: A. i, ii, iii, iv B. iii, iv, i, ii C. ii, iv, iii, i D. ii, iv, i, iii',
  False,
  [],
  'C ✓',
  ['C'],
  'C ✓',
  False,
  False),
 ('1.1.4',
  1,
  'Transport in animals',
  'Multiple Choice',
  'Which of the following statements is correctly paired with a part of the circulatory system? Part of the '
  'circulatory system Statement A. Pulmonary vein Carries oxygenated blood at low pressure B. Semilunar valve '
  'Prevents flow of blood from arteries into ventricles C. AV valves Prevents flow of blood from arteries into '
  'ventricles D. Aorta Carries deoxygenated blood at high pressure',
  False,
  [],
  'B ✓',
  ['B'],
  'B ✓',
  False,
  False),
 ('1.1.5',
  1,
  'Transport in animals',
  'Multiple Choice',
  'Assuming a healthy heart, if a person has a heart rate of 72 beats per minute, calculate the duration it takes '
  'to complete each cardiac cycle. A. 1,2 seconds B. 1,2 minutes C. 0,8 seconds D. 0,8 minutes (5)',
  False,
  [],
  'C ✓ (5)',
  ['C'],
  'C ✓ (5)',
  False,
  False),
 ('1.2.1',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'The only veins to transport oxygenated blood.',
  False,
  [],
  'Pulmonary veins ✓',
  ['Pulmonary veins'],
  'Pulmonary veins ✓',
  False,
  False),
 ('1.2.2',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'Fluid that is drained between the cells of the tissue and transported back to the bloodstream.',
  False,
  [],
  'Lymph ✓',
  ['Lymph'],
  'Lymph ✓',
  False,
  False),
 ('1.2.3',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'The relaxation of the cardiac muscle.',
  False,
  [],
  'Diastole/ general diastole ✓',
  ['Diastole/ general diastole'],
  'Diastole/ general diastole ✓',
  False,
  False),
 ('1.2.4',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'White blood cells that actively leave capillaries to engulf foreign substances.',
  False,
  [],
  'Phagocytes ✓',
  ['Phagocytes'],
  'Phagocytes ✓',
  False,
  False),
 ('1.2.5',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'The number of heart beats per minute. (5)',
  False,
  [],
  'Heart rate ✓ (5)',
  ['Heart rate'],
  'Heart rate ✓ (5)',
  False,
  False),
 ('2.1',
  3,
  'Transport in animals',
  'Labelling/Diagram',
  'Provide labels for parts numbered 1, 2 and 3. (3)',
  True,
  [],
  '1- superior vena cava ✓ 2- inferior vena cava ✓ 3- pulmonary artery✓ (3)',
  ['1- superior vena cava', '2- inferior vena cava', '3- pulmonary artery'],
  '1- superior vena cava ✓ 2- inferior vena cava ✓ 3- pulmonary artery✓ (3)',
  True,
  False),
 ('2.2',
  2,
  'Transport in animals',
  'Data/Graph Interpretation',
  'Explain the importance of structure 4. (2)',
  True,
  [],
  'It separates the left and right side of the heart ✓ ensuring that oxygenated and deoxygenated blood do not '
  'mix. ✓ (2)',
  ['It separates the left and right side of the heart',
   'ensuring that oxygenated and deoxygenated blood do not mix.'],
  'It separates the left and right side of the heart ✓ ensuring that oxygenated and deoxygenated blood do not '
  'mix. ✓ (2)',
  True,
  False),
 ('2.3.1',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'The heart muscle is myogenic. Define this term. (1)',
  False,
  [],
  'Contractions arise within the muscle itself. ✓ (1)',
  ['Contractions arise within the muscle itself.'],
  'Contractions arise within the muscle itself. ✓ (1)',
  False,
  False),
 ('2.3.2',
  2,
  'Transport in animals',
  'Labelling/Diagram',
  'Provide the letter and the name of the structure which generates the heartbeat. (2)',
  True,
  [],
  'A✓- Sinoatrial (SA) node ✓ (2)',
  ['A', '- Sinoatrial (SA) node'],
  'A✓- Sinoatrial (SA) node ✓ (2)',
  True,
  False),
 ('2.3.3',
  4,
  'Transport in animals',
  'Labelling/Diagram',
  'By using the names of structures A-D, explain how the heartbeat is generated. (4)',
  True,
  [],
  'The SA node (A) generates contractions in the right atrium ✓ This stimulates the AV node (B) causing the atria '
  'to contract ✓ Which in turn sends impulses down the Bundle of His (C) ✓ These branch into the Purkinje fibres '
  '(D) which stimulate contractions in the ventricles. ✓ (4)',
  ['The SA node (A) generates contractions in the right atrium',
   'This stimulates the AV node (B) causing the atria to contract',
   'Which in turn sends impulses down the Bundle of His (C)',
   'These branch into the Purkinje fibres (D) which stimulate contractions in the ventricles.'],
  'The SA node (A) generates contractions in the right atrium ✓ This stimulates the AV node (B) causing the atria '
  'to contract ✓ Which in turn sends impulses down the Bundle of His (C) ✓ These branch into the Purkinje fibres '
  '(D) which stimulate contractions in the ventricles. ✓ (4)',
  True,
  False),
 ('2.3.4',
  3,
  'Transport in animals',
  'Short Answer',
  'Although the structure mentioned in 2.3.2. initiates the heartbeat, it cannot alter the rate at which the '
  'heartbeat contracts. What system is involved in slowing the heart rate and how does it achieve this? (3)',
  False,
  [],
  'The parasympathetic nervous system/ the nervous system ✓ Impulses are sent along the parasympathetic NS to the '
  'SA node ✓ The SA node reduces the number of impulses that it sends out and HR slows down ✓ (3)',
  ['The parasympathetic nervous system/ the nervous system',
   'Impulses are sent along the parasympathetic NS to the SA node',
   'The SA node reduces the number of impulses that it sends out and HR slows down'],
  'The parasympathetic nervous system/ the nervous system ✓ Impulses are sent along the parasympathetic NS to the '
  'SA node ✓ The SA node reduces the number of impulses that it sends out and HR slows down ✓ (3)',
  False,
  False),
 ('3.1',
  2,
  'Transport in animals',
  'Data/Graph Interpretation',
  'What is the highest blood pressure achieved in the arteries? (2)',
  True,
  [],
  '14 ✓kPa ✓ (2)',
  ['kPa'],
  '14 ✓kPa ✓ (2)',
  True,
  False),
 ('3.2',
  2,
  'Transport in animals',
  'Short Answer',
  'Explain why a higher blood pressure is achieved and maintained in the aorta. (2)',
  False,
  [],
  'The aorta receives blood directly from the left atrium, which pumps blood at the highest pressure. ✓ The aorta '
  'has a thick muscular wall to maintain the pressure of the blood. ✓ (2)',
  ['The aorta receives blood directly from the left atrium, which pumps blood at the highest pressure.',
   'The aorta has a thick muscular wall to maintain the pressure of the blood.'],
  'The aorta receives blood directly from the left atrium, which pumps blood at the highest pressure. ✓ The aorta '
  'has a thick muscular wall to maintain the pressure of the blood. ✓ (2)',
  False,
  False),
 ('3.3.a',
  2,
  'Transport in animals',
  'Short Answer',
  'What causes this fluctuation? (2)',
  False,
  [],
  'The contracting and relaxing✓ of the muscular wall/layer ✓ of the arteries. (2)',
  ['The contracting and relaxing', 'of the muscular wall/layer', 'of the arteries. (2)'],
  'The contracting and relaxing✓ of the muscular wall/layer ✓ of the arteries. (2)',
  False,
  False),
 ('3.3.b',
  5,
  'Transport in animals',
  'Labelling/Diagram',
  'Draw a labelled diagram of a cross section of an artery to indicate the various layers that make up this '
  'vessel. (5)',
  True,
  [],
  'Heading ✓ Accuracy and diagram rules ✓ Any 3 labels ✓✓✓ (5)',
  ['Heading', 'Accuracy and diagram rules', 'Any 3 labels'],
  'Heading ✓ Accuracy and diagram rules ✓ Any 3 labels ✓✓✓ (5)',
  True,
  False),
 ('3.4.a',
  1,
  'Transport in animals',
  'Short Answer',
  'How is this drop in pressure achieved? (1)',
  False,
  [],
  'As blood moves from the aorta to smaller arteries and arterioles there is a decrease in blood pressure. ✓ (1)',
  ['As blood moves from the aorta to smaller arteries and arterioles there is a decrease in blood pressure.'],
  'As blood moves from the aorta to smaller arteries and arterioles there is a decrease in blood pressure. ✓ (1)',
  False,
  False),
 ('3.4.b',
  2,
  'Transport in animals',
  'Short Answer',
  'Why is it necessary that the pressure changes as blood flows into the capillaries? (2)',
  False,
  [],
  'Capillaries only consist of one layer of endothelium. ✓ High blood pressure will cause the walls of the '
  'capillary to rupture/burst. ✓ (2)',
  ['Capillaries only consist of one layer of endothelium.',
   'High blood pressure will cause the walls of the capillary to rupture/burst.'],
  'Capillaries only consist of one layer of endothelium. ✓ High blood pressure will cause the walls of the '
  'capillary to rupture/burst. ✓ (2)',
  False,
  False),
 ('3.5',
  1,
  'Transport in animals',
  'Short Answer',
  'Although veins operate under the lowest pressure, blood is still effectively transported in these vessels. '
  'What structural adaptation do these vessels contain to aid the movement of blood back towards the heart? (1)',
  False,
  [],
  'SL valves ✓ (1)',
  ['SL valves'],
  'SL valves ✓ (1)',
  False,
  False),
 ('4.1',
  4,
  'Transport in animals',
  'Short Answer',
  'Construct a table to record the nurse’s data. (4)',
  False,
  [],
  'Heading ✓ Enclosed table ✓ Column headings ✓ Data ✓ (4)',
  ['Heading', 'Enclosed table', 'Column headings', 'Data'],
  'Heading ✓ Enclosed table ✓ Column headings ✓ Data ✓ (4)',
  False,
  False),
 ('4.2',
  1,
  'Transport in animals',
  'Short Answer',
  'Of the three patients, which reading would be in a normal, healthy range? (1)',
  False,
  [],
  'Patient 2 (120/80) ✓ (1)',
  ['Patient 2 (120/80)'],
  'Patient 2 (120/80) ✓ (1)',
  False,
  False),
 ('4.3',
  1,
  'Transport in animals',
  'Short Answer',
  'Consider the reading of 140/90 mmHG. The value: 140 represents which phase of the cardiac cycle? (1)',
  False,
  [],
  'Ventricular systole ✓ (1)',
  ['Ventricular systole'],
  'Ventricular systole ✓ (1)',
  False,
  False),
 ('4.4',
  1,
  'Transport in animals',
  'Definition/Terminology',
  'Provide the term for chronic high blood pressure. (1)',
  False,
  [],
  'Hypertension ✓ (1)',
  ['Hypertension'],
  'Hypertension ✓ (1)',
  False,
  False),
 ('4.5',
  2,
  'Transport in animals',
  'Short Answer',
  'State one factor that cannot be controlled and one factor that can be controlled when it comes to high blood '
  'pressure in an individual. (2)',
  False,
  [],
  'Controlled: weight, smoking, exercise, any relevant answer (any 1 ✓) Uncontrolled: age, genetics, being male '
  '(any 1 ✓) (2)',
  ['Controlled: weight, smoking, exercise, any relevant answer (any 1',
   ') Uncontrolled: age, genetics, being male (any 1'],
  'Controlled: weight, smoking, exercise, any relevant answer (any 1 ✓) Uncontrolled: age, genetics, being male '
  '(any 1 ✓) (2)',
  False,
  False),
 ('4.6',
  1,
  'Transport in animals',
  'Short Answer',
  'Name one danger associated with abnormally high blood pressure. (1)',
  False,
  [],
  'Heart attack, aneurysm, stroke, heart failure, kidney damage, brain damage (any 1✓) (1)',
  ['Heart attack, aneurysm, stroke, heart failure, kidney damage, brain damage (any 1'],
  'Heart attack, aneurysm, stroke, heart failure, kidney damage, brain damage (any 1✓) (1)',
  False,
  False)]

SOURCE_HASHES = {'paper_path': '4ced0fffb6b926c8489eb1c59b306a464b1a5fd891d5d66fa89345a4390aa875',
 'memo_path': '31d01c7e51c2d2968364f5d4ec81c646d9f835db169a8128c9b020d8dd68209e'}

LOCATORS = {'1.1.1': {'page': 2,
           'memo_page': 2,
           'question_stem_text': ' Various possibilities are suggested as answers to the following questions. '
                                 'Indicate the correct answer by writing the correct letter from the '
                                 'corresponding question on the folio paper provided.',
           'parent_question_number': '1.1'},
 '1.1.2': {'page': 2,
           'memo_page': 2,
           'question_stem_text': ' Various possibilities are suggested as answers to the following questions. '
                                 'Indicate the correct answer by writing the correct letter from the '
                                 'corresponding question on the folio paper provided.',
           'parent_question_number': '1.1'},
 '1.1.3': {'page': 2,
           'memo_page': 2,
           'question_stem_text': ' Various possibilities are suggested as answers to the following questions. '
                                 'Indicate the correct answer by writing the correct letter from the '
                                 'corresponding question on the folio paper provided.',
           'parent_question_number': '1.1'},
 '1.1.4': {'page': 2,
           'memo_page': 2,
           'question_stem_text': ' Various possibilities are suggested as answers to the following questions. '
                                 'Indicate the correct answer by writing the correct letter from the '
                                 'corresponding question on the folio paper provided.',
           'parent_question_number': '1.1'},
 '1.1.5': {'page': 3,
           'memo_page': 2,
           'question_stem_text': ' Various possibilities are suggested as answers to the following questions. '
                                 'Indicate the correct answer by writing the correct letter from the '
                                 'corresponding question on the folio paper provided.',
           'parent_question_number': '1.1'},
 '1.2.1': {'page': 3,
           'memo_page': 2,
           'question_stem_text': ' Provide the correct biological term for the following statements',
           'parent_question_number': '1.2'},
 '1.2.2': {'page': 3,
           'memo_page': 2,
           'question_stem_text': ' Provide the correct biological term for the following statements',
           'parent_question_number': '1.2'},
 '1.2.3': {'page': 3,
           'memo_page': 2,
           'question_stem_text': ' Provide the correct biological term for the following statements',
           'parent_question_number': '1.2'},
 '1.2.4': {'page': 3,
           'memo_page': 2,
           'question_stem_text': ' Provide the correct biological term for the following statements',
           'parent_question_number': '1.2'},
 '1.2.5': {'page': 3,
           'memo_page': 2,
           'question_stem_text': ' Provide the correct biological term for the following statements',
           'parent_question_number': '1.2'},
 '2.1': {'page': 4,
         'memo_page': 2,
         'question_stem_text': 'Study the diagram of the heart below and answer the questions that follow.',
         'parent_question_number': '2'},
 '2.2': {'page': 4,
         'memo_page': 2,
         'question_stem_text': 'Study the diagram of the heart below and answer the questions that follow.',
         'parent_question_number': '2'},
 '2.3.1': {'page': 4,
           'memo_page': 2,
           'question_stem_text': 'Study the diagram of the heart below and answer the questions that follow. '
                                 'Structures A, B, C and D are involved in conducting the heartbeat.',
           'parent_question_number': '2.3'},
 '2.3.2': {'page': 4,
           'memo_page': 2,
           'question_stem_text': 'Study the diagram of the heart below and answer the questions that follow. '
                                 'Structures A, B, C and D are involved in conducting the heartbeat.',
           'parent_question_number': '2.3'},
 '2.3.3': {'page': 4,
           'memo_page': 2,
           'question_stem_text': 'Study the diagram of the heart below and answer the questions that follow. '
                                 'Structures A, B, C and D are involved in conducting the heartbeat.',
           'parent_question_number': '2.3'},
 '2.3.4': {'page': 4,
           'memo_page': 2,
           'question_stem_text': 'Study the diagram of the heart below and answer the questions that follow. '
                                 'Structures A, B, C and D are involved in conducting the heartbeat.',
           'parent_question_number': '2.3'},
 '3.1': {'page': 4,
         'memo_page': 3,
         'question_stem_text': 'The graph below provides information about the blood pressure in different parts '
                               'of the mammalian blood circulatory system.',
         'parent_question_number': '3'},
 '3.2': {'page': 5,
         'memo_page': 3,
         'question_stem_text': 'The graph below provides information about the blood pressure in different parts '
                               'of the mammalian blood circulatory system.',
         'parent_question_number': '3'},
 '3.5': {'page': 5,
         'memo_page': 3,
         'question_stem_text': 'The graph below provides information about the blood pressure in different parts '
                               'of the mammalian blood circulatory system.',
         'parent_question_number': '3'},
 '4.1': {'page': 6,
         'memo_page': 3,
         'question_stem_text': 'Blood pressure refers to the two pressures measured in the arteries when the '
                               'muscles of the heart contract and relax. The instrument that is used to measure '
                               'blood pressure is known as a sphygomomanometer around the upper arm, as pictured '
                               'below. A nurse at a wellness centre assessed 3 different patients and recorded '
                               'the following respective readings: 135/85 mmHG; 120/80 mmHG and 140/90 mmHG.',
         'parent_question_number': '4'},
 '4.2': {'page': 6,
         'memo_page': 3,
         'question_stem_text': 'Blood pressure refers to the two pressures measured in the arteries when the '
                               'muscles of the heart contract and relax. The instrument that is used to measure '
                               'blood pressure is known as a sphygomomanometer around the upper arm, as pictured '
                               'below. A nurse at a wellness centre assessed 3 different patients and recorded '
                               'the following respective readings: 135/85 mmHG; 120/80 mmHG and 140/90 mmHG.',
         'parent_question_number': '4'},
 '4.3': {'page': 6,
         'memo_page': 3,
         'question_stem_text': 'Blood pressure refers to the two pressures measured in the arteries when the '
                               'muscles of the heart contract and relax. The instrument that is used to measure '
                               'blood pressure is known as a sphygomomanometer around the upper arm, as pictured '
                               'below. A nurse at a wellness centre assessed 3 different patients and recorded '
                               'the following respective readings: 135/85 mmHG; 120/80 mmHG and 140/90 mmHG.',
         'parent_question_number': '4'},
 '4.4': {'page': 6,
         'memo_page': 3,
         'question_stem_text': 'Blood pressure refers to the two pressures measured in the arteries when the '
                               'muscles of the heart contract and relax. The instrument that is used to measure '
                               'blood pressure is known as a sphygomomanometer around the upper arm, as pictured '
                               'below. A nurse at a wellness centre assessed 3 different patients and recorded '
                               'the following respective readings: 135/85 mmHG; 120/80 mmHG and 140/90 mmHG.',
         'parent_question_number': '4'},
 '4.5': {'page': 6,
         'memo_page': 3,
         'question_stem_text': 'Blood pressure refers to the two pressures measured in the arteries when the '
                               'muscles of the heart contract and relax. The instrument that is used to measure '
                               'blood pressure is known as a sphygomomanometer around the upper arm, as pictured '
                               'below. A nurse at a wellness centre assessed 3 different patients and recorded '
                               'the following respective readings: 135/85 mmHG; 120/80 mmHG and 140/90 mmHG.',
         'parent_question_number': '4'},
 '4.6': {'page': 6,
         'memo_page': 3,
         'question_stem_text': 'Blood pressure refers to the two pressures measured in the arteries when the '
                               'muscles of the heart contract and relax. The instrument that is used to measure '
                               'blood pressure is known as a sphygomomanometer around the upper arm, as pictured '
                               'below. A nurse at a wellness centre assessed 3 different patients and recorded '
                               'the following respective readings: 135/85 mmHG; 120/80 mmHG and 140/90 mmHG.',
         'parent_question_number': '4'},
 '3.3.a': {'page': 5,
           'memo_page': 3,
           'question_stem_text': 'The graph below provides information about the blood pressure in different '
                                 'parts of the mammalian blood circulatory system. The pressure fluctuates as the '
                                 'blood flows along the aorta and arteries. ',
           'parent_question_number': '3.3'},
 '3.3.b': {'page': 5,
           'memo_page': 3,
           'question_stem_text': 'The graph below provides information about the blood pressure in different '
                                 'parts of the mammalian blood circulatory system. The pressure fluctuates as the '
                                 'blood flows along the aorta and arteries. ',
           'parent_question_number': '3.3'},
 '3.4.a': {'page': 5,
           'memo_page': 3,
           'question_stem_text': 'The graph below provides information about the blood pressure in different '
                                 'parts of the mammalian blood circulatory system. The capillaries are the '
                                 'smallest blood vessel (with extremely small lumens) yet the pressure is '
                                 'drastically reduced in capillary networks. ',
           'parent_question_number': '3.4'},
 '3.4.b': {'page': 5,
           'memo_page': 3,
           'question_stem_text': 'The graph below provides information about the blood pressure in different '
                                 'parts of the mammalian blood circulatory system. The capillaries are the '
                                 'smallest blood vessel (with extremely small lumens) yet the pressure is '
                                 'drastically reduced in capillary networks. ',
           'parent_question_number': '3.4'}}
