"""Pass 1 evidence table — Grade 11 Chemistry Mid-Year Examination, 23 July 2025.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/Gr 11 chemistry July 2025.txt          (135 marks, Mrs Govender)
        (source PDF: .../Gr 11 chemistry July 2025.pdf)
Memo:   data/organized/chemistry/Gr 11 chemistry July 2025 MG.txt       (135 marks, Mrs Govender)

NOTE: the memo's printed "Question Total" header swaps Q5 and Q6 (shows 17,14); the
question paper correctly shows Q5 = 14 and Q6 = 17, and the sub-question marks sum to
those values, so the evidence is aligned to the paper's printed TOTAL of 135.

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2025-JUL",
    "paper_path": "data/organized/chemistry/Gr 11 chemistry July 2025.pdf",
    "memo_path": "data/organized/chemistry/Gr 11 chemistry July 2025 MG.pdf",
    "year": 2025,
    "exam_date": "23 July 2025",
    "exam_period": "july",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 135,
    "examiner": "Mrs Govender",
    "moderator": "Mr Ntombela",
    "duration_stated": "120 minutes",
    "fidelity_rung": "A",
    "notes": (
        "School-set mid-year Chemistry paper (St Benedict's College). Q1 refers to substances "
        "A-E given in an image (identities not fully legible from text). Energy-profile (Q5.1) "
        "and Maxwell-Boltzmann (Q2.4, Q6.4) sketches are diagram-based."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: INTERMOLECULAR FORCES (15 marks) ----------------
    ("1.1.1", 4, "Intermolecular Forces", "Explanation",
     "Explain the formation of London forces between molecules.",
     False, [], "random e- movement sets up a temporary dipole; induces a dipole in the neighbour; the dipoles attract",
     ["random e- movement (1)", "temp dipole (1)", "induces dipole in neighbour (1)", "attract (1)"], "Four marks.", False, False),
    ("1.1.2", 5, "Intermolecular Forces", "Explanation",
     "Substance A has a lower Bpt than substance D. Reason via molecular polarity and IMFs. (substances A-E given as an image)",
     False, [], "both have London forces; the larger molecule has more electrons -> larger temporary dipole -> stronger London -> higher Bpt",
     ["both London (1)", "larger molecule (1)", "more electrons (1)", "stronger London (1)", "more energy to overcome (1)"], "Five marks; A-E identities from an image.", False, True),
    ("1.1.3", 1, "Intermolecular Forces", "Short Answer",
     "Name substance B.",
     False, [], "hydrogen sulphide (H2S)", ["H2S (1)"], "One mark; from the substance list (image).", False, True),
    ("1.1.4", 2, "Intermolecular Forces", "Explanation",
     "Molecule C is polar. Explain why.",
     False, [], "it is asymmetrical (uneven electron-cloud distribution) and forms a dipole",
     ["asymmetrical (1)", "forms dipole (1)"], "Two marks.", False, True),
    ("1.1.5", 3, "Intermolecular Forces", "Diagram-based",
     "Draw H-bonding between one molecule of substance E and water; label ALL possible H-bonds.",
     True, [], "two H-bonds shown with water (correct labels)", ["two bonds (1)", "one methanol (1)", "H-bonds labelled (1)"], "Three marks; on the diagram.", True, True),

    # ---------------- QUESTION 2: BONDING / IMFs (17 marks) ----------------
    ("2.1.1", 3, "Bonding", "Short Answer",
     "Mg + O2 -> MgO. Balanced equation (state symbols not required).",
     False, [], "2Mg + O2 -> 2MgO", ["RHS (1)", "LHS (1)", "balancing (1)"], "Three marks.", False, False),
    ("2.1.2a", 4, "Bonding", "Explanation",
     "Why does MgO have a high melting point? (bonding/structure)",
     False, [], "ionic crystal lattice; many strong ionic bonds; strong electrostatic attraction -> much energy to overcome",
     ["ionic lattice (1)", "many ionic bonds (1)", "strong electrostatic forces (1)", "energy to overcome (1)"], "Four marks.", False, False),
    ("2.1.2b", 2, "Bonding", "Explanation",
     "Why does MgO NOT conduct when solid?",
     False, [], "ions held in fixed positions by ionic bonds; unable to move", ["ions fixed (1)", "cannot move (1)"], "Two marks.", False, False),
    ("2.2.1", 2, "Bonding", "Short Answer",
     "Specific type of bonding/IMF indicated by 1 (water and HF diagram).",
     True, [], "polar covalent bonds", ["polar (1)", "covalent (1)"], "Two marks; from the diagram.", True, False),
    ("2.2.2", 2, "Intermolecular Forces", "Explanation",
     "Why does water have a higher Bpt than HF, though both have H-bonds?",
     False, [], "water forms 4 H-bonds per molecule; HF only 2", ["water 4 (1)", "HF 2 (1)"], "Two marks.", False, False),
    ("2.2.3", 4, "Intermolecular Forces", "Explanation",
     "Account for the Bpt difference of methanol (64,7 C) and iodine (184,3 C).",
     False, [], "iodine is larger with more electrons -> larger temp dipole -> stronger London -> higher Bpt than methanol's H-bonding",
     ["iodine larger/more e- (1)", "larger temp dipole (1)", "stronger forces (1)", "more energy (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 3: LIMITING REACTANTS (18 marks) ----------------
    ("3.1.1", 1, "Stoichiometry", "Definition/Explain",
     "Define molar mass.",
     False, [], "mass in grams of one mole of a substance", ["mass in grams (1)"], "One mark.", False, False),
    ("3.1.2", 5, "Stoichiometry", "Calculation",
     "C3H7OH + 5O2 -> 3CO2 + 4H2O. 10 g propanol + 50 g O2. Limiting reactant?",
     False, ["n=m/M"], "propanol is limiting",
     ["M(propanol)=60, n=10/60=0,17 (1)", "M(O2)=32, n=50/32=1,5625 (1)", "ratio 1:5 (1)", "need 0,85 O2 (1)", "propanol limiting (1)"], "Five marks.", False, False),
    ("3.1.3", 3, "Stoichiometry", "Calculation",
     "Total number of oxygen atoms left unreacted.",
     False, ["N=n.Na"], "8,58 x 10^23 O atoms",
     ["unreacted O2 = 1,5625-0,85 = 0,7125 mol (1)", "x2 x6,02e23 (1)", "=8,58e23 (1)"], "Three marks.", False, False),
    ("3.1.4", 3, "Stoichiometry", "Calculation",
     "Volume of CO2 produced at STP.",
     False, ["V=n.Vm"], "11,42 dm3",
     ["ratio 1:3 (1)", "n(CO2)=0,51 (1)", "V=0,51x22,4=11,42 (1)"], "Three marks.", False, False),
    ("3.2", 6, "Stoichiometry", "Calculation",
     "2KF -> 2K + F2. 25 g impure KF gives 4,48 dm3 F2 at STP. Percentage purity?",
     False, ["n=V/Vm"], "92,8%",
     ["n(F2)=4,48/22,4=0,2 (1)", "ratio 2:1 -> n(KF)=0,4 (1)", "m=0,4x58=23,2 g (1)", "% = 23,2/25 x100 (1)", "=92,8% (1)"], "Six marks (memo rounds to 92,8%).", False, False),

    # ---------------- QUESTION 4: SOLUTIONS / STANDARD SOLUTION (19 marks) ----------------
    ("4.1.1", 3, "Bonding", "Short Answer",
     "100 cm3 0,4 M K2SO4 + 200 cm3 0,3 M KBr. Dissociation equation for K2SO4.",
     False, [], "K2SO4(s) -> 2K+(aq) + SO4 2-(aq)", ["2K+ (1)", "SO4 2- (1)", "state symbols (1)"], "Three marks.", False, False),
    ("4.1.2", 2, "Bonding", "Short Answer",
     "Oxidation number of sulphur in K2SO4.",
     False, [], "+6", ["+6 (2)"], "Two marks.", False, False),
    ("4.1.3", 5, "Stoichiometry", "Calculation",
     "Total concentration of K+ ions when the two solutions are mixed.",
     False, ["n=cV", "c=n/V"], "0,47 mol.dm-3",
     ["n(K+ from K2SO4)=0,08 (1)", "n(K+ from KBr)=0,06 (1)", "total n=0,14 (1)", "c=0,14/0,3 (1)", "=0,47 (1)"], "Five marks.", False, False),
    ("4.2.1", 2, "Stoichiometry", "Definition/Explain",
     "Define a standard solution.",
     False, [], "a solution of known concentration", ["known concentration (2)"], "Two marks.", False, False),
    ("4.2.2", 3, "Stoichiometry", "Calculation",
     "Mass of Mg(OH)2 for 250 ml of 0,4 M solution. (M=58,3)",
     False, ["m=cMV"], "5,83 g",
     ["m=cMV (1)", "=0,4x0,25x58,3 (1)", "=5,83 g (1)"], "Three marks.", False, False),
    ("4.2.3", 1, "Stoichiometry", "Short Answer",
     "Name of the flask used to make a standard solution.",
     False, [], "volumetric flask", ["volumetric flask (1)"], "One mark.", False, False),
    ("4.2.4", 1, "Stoichiometry", "Short Answer",
     "Apparatus used to prevent spillage when transferring.",
     False, [], "funnel", ["funnel (1)"], "One mark.", False, False),
    ("4.2.5", 2, "Scientific Skills", "Short Answer",
     "Correct order of the standard-solution steps (A-G).",
     False, [], "C F A B D E G",
     ["memo prints 'C F A B D' (truncated); full sequence C,F,A,B,D,E,G (1)", "minus 1 per wrong letter (1)"], "Two marks.", False, False),

    # ---------------- QUESTION 5: ENERGY AND RATES (14 marks) ----------------
    ("5.1", 5, "Energy & Chemical Change", "Diagram-based",
     "Fully labelled potential-energy diagram for lactic-acid breakdown (exothermic, high Ea); catalysed and uncatalysed pathways. Labels: Ea (with/without catalyst), dH, reactants, products.",
     True, [], "exothermic profile; catalysed EA lower than uncatalysed; both share reactants/products",
     ["reactants/products (1)", "dH labelled (1)", "uncatalysed Ea (1)", "catalysed Ea (1)", "correct exothermic shape (1)"], "Five marks; on the graph.", True, False),
    ("5.2.1", 2, "Reaction Rates", "Data/Graph Interpretation",
     "Maxwell-Boltzmann curve (37 C). What does the area under the curve represent?",
     True, [], "the total number of particles in the reaction", ["number of particles (2)"], "Two marks; graph is an image.", True, False),
    ("5.2.2", 2, "Reaction Rates", "Diagram-based",
     "Indicate the new activation energy for the catalysed reaction on the graph.",
     True, [], "Ea line shifted left (lower) for catalysed", ["new Ea indicated (2)"], "Two marks; on the graph.", True, False),
    ("5.2.3", 1, "Reaction Rates", "Short Answer",
     "'Catalysts speed up reactions by increasing the energy of molecules.' YES/NO?",
     True, [], "NO", ["NO (1)"], "One mark.", True, False),
    ("5.2.3b", 2, "Reaction Rates", "Explanation",
     "Support the answer to 5.2.3 with reference to theory and the graph.",
     True, [], "catalysts lower the activation energy by providing an alternative pathway; more particles have Ek >= Ea, but particle energy is unchanged",
     ["lowers Ea / alternative path (1)", "more particles Ek>=Ea; energy unchanged (1)"], "Two marks; graph is an image.", True, False),
    ("5.2.4", 2, "Reaction Rates", "Explanation",
     "Two ways the MB curve changes at 38 C (vs 37 C).",
     True, [], "lower/more spread peak; more particles at higher KE (area same)",
     ["lower peak / more spread (1)", "more particles high KE (1)"], "Two marks; graph is an image.", True, False),

    # ---------------- QUESTION 6: REACTION RATES (lactic acid) (17 marks) ----------------
    ("6.1", 2, "Reaction Rates", "Definition/Explain",
     "C3H6O3 -> C3H4O3 + H2. Define reaction rate in terms of this experiment.",
     False, [], "change in volume/concentration of reactant or product per unit time", ["change in conc/volume (1)", "per unit time (1)"], "Two marks.", False, False),
    ("6.2", 3, "Reaction Rates", "Calculation",
     "Average rate of H2 production with catalyst (50 cm3 in 40 s).",
     False, ["rate = Δv/Δt"], "1,25 cm3.s-1",
     ["rate = 50/40 (1)", "=1,25 (1)", "units cm3.s-1 (1)"], "Three marks.", False, False),
    ("6.3.1", 2, "Reaction Rates", "Explanation",
     "Does the catalyst affect the amount of product formed?",
     False, [], "unchanged (eventually 50 cm3 either way)", ["unchanged (1)", "same final volume (1)"], "Two marks.", False, False),
    ("6.3.2", 2, "Reaction Rates", "Explanation",
     "Does the catalyst affect the speed of the reaction?",
     False, [], "yes - with catalyst it finishes in 40 s (faster)", ["faster with catalyst (1)", "less time (1)"], "Two marks.", False, False),
    ("6.4", 4, "Reaction Rates", "Diagram-based",
     "Sketch volume of H2 vs time for both trials on the same axes (include all values).",
     True, [], "catalyst curve rises faster to 50 cm3 plateau; no-catalyst curve slower to ~16-50",
     ["axes/labels (1)", "catalyst curve (1)", "no-catalyst curve (1)", "plateau/values (1)"], "Four marks; on the graph.", True, False),
    ("6.5", 4, "Reaction Rates", "Explanation",
     "Predict the effect of 38 C (catalyst still functional); justify via collision theory.",
     False, [], "faster; higher T -> more particles with KE>=Ea -> more effective collisions/s -> higher rate",
     ["higher avg KE (1)", "more KE>=Ea (1)", "more effective collisions/s (1)", "rate increases (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 7: REDOX (14 marks) ----------------
    ("7.1", 6, "Bonding", "Short Answer",
     "Al + HCl -> AlCl3 + H2. Write oxidation, reduction and net ionic half-reactions.",
     False, [], "ox: Al -> Al3+ + 3e-; red: 2H+ + 2e- -> H2; net: 2Al + 6H+ -> 2Al3+ + 3H2",
     ["oxidation (2)", "reduction (2)", "net ionic balanced (2)"], "Six marks.", False, False),
    ("7.2", 2, "Bonding", "Short Answer",
     "Formulae of: reducing agent; spectator ion.",
     False, [], "reducing agent = Al; spectator ion = Cl-", ["Al (1)", "Cl- (1)"], "Two marks.", False, False),
    ("7.3", 4, "Bonding", "Explanation",
     "Explain why this reaction is spontaneous.",
     False, [], "Al is a stronger reducing agent than H2 (or H+ stronger oxidising than Al3+) so Al reduces H+ to H2",
     ["Al stronger reducing agent (1)", "than H2 (1)", "Al reduces H+ (1)", "to H2 (1)"], "Four marks.", False, False),
    ("7.4", 2, "Bonding", "Short Answer",
     "What happens to a reducing agent (oxidation number and electron transfer)?",
     False, [], "oxidation number increases; it donates/loses electrons", ["ON increases (1)", "loses electrons (1)"], "Two marks.", False, False),

    # ---------------- QUESTION 8: ELECTROLYSIS (21 marks) ----------------
    ("8.1.1", 2, "Bonding", "Short Answer",
     "Key electroplated with copper. Energy conversion in the electrolytic cell?",
     False, [], "electrical to chemical", ["electrical (1)", "chemical (1)"], "Two marks.", False, False),
    ("8.1.2", 2, "Bonding", "Diagram-based",
     "On the diagram, draw the battery needed for the cell to work.",
     True, [], "a DC battery connected to the electrodes (correct polarity)", ["battery drawn (2)"], "Two marks; on the diagram.", True, False),
    ("8.1.3", 2, "Bonding", "Short Answer",
     "Formula of a substance dissolved in water to form the electrolyte for copper plating.",
     False, [], "CuSO4 or Cu(NO3)2", ["copper salt (2)"], "Two marks.", False, False),
    ("8.1.4", 3, "Bonding", "Short Answer",
     "Half-reaction at the key, and whether oxidation or reduction.",
     False, [], "Cu2+ + 2e- -> Cu (reduction)", ["Cu2+ + 2e- (1)", "-> Cu (1)", "reduction (1)"], "Three marks.", False, False),
    ("8.2.1", 2, "Bonding", "Short Answer",
     "Material used to make the electrodes (molten PbBr2 cell).",
     False, [], "carbon / graphite / platinum", ["carbon/graphite/platinum (2)"], "Two marks.", False, False),
    ("8.2.2", 2, "Bonding", "Explanation",
     "Two reasons this electrode material is used.",
     False, [], "cheap/inert/good conductor/high MP (any two)", ["two valid reasons (2)"], "Two marks.", False, False),
    ("8.2.3", 2, "Bonding", "Explanation",
     "Why must PbBr2 be melted for electrolysis?",
     False, [], "to overcome electrostatic forces so ions are free to move and conduct", ["overcome electrostatic forces (1)", "ions free to move (1)"], "Two marks.", False, False),
    ("8.6.1", 1, "Bonding", "Short Answer",
     "What carries electricity in the wire?",
     False, [], "electrons", ["electrons (1)"], "One mark.", False, False),
    ("8.6.2", 1, "Bonding", "Short Answer",
     "What carries electricity in the electrode?",
     False, [], "electrons", ["electrons (1)"], "One mark.", False, False),
    ("8.6.3", 1, "Bonding", "Short Answer",
     "What carries electricity in molten lead bromide?",
     False, [], "ions", ["ions (1)"], "One mark.", False, False),
    ("8.7", 3, "Bonding", "Diagram-based",
     "Complete the table for electrolysis of molten PbBr2 (observations + half-reactions).",
     True, [], "neg electrode: silvery-grey liquid Pb forms (Pb2++2e->Pb); pos electrode: red-brown Br2 gas (2Br-->Br2+2e)",
     ["neg obs Pb (1)", "Pb half-reaction (1)", "Br half-reaction (1)"], "Three marks; table.", True, False),
]
