"""Pass 1 evidence table — Grade 11 Physical Sciences Paper 2 (Chemistry), 5 August 2019.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/Grade 11 Paper 2 July QP.pdf   (162 marks, Mr Ntombela)
Memo:   data/organized/chemistry/Grade 11 Paper 2  July MG.pdf  (162 marks, Mr Ntombela)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2019-AUG",
    "paper_path": "data/organized/chemistry/Grade 11 Paper 2 July QP.pdf",
    "memo_path": "data/organized/chemistry/Grade 11 Paper 2  July MG.pdf",
    "year": 2019,
    "exam_date": "5 August 2019",
    "exam_period": "june",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 162,
    "examiner": "Mr Ntombela",
    "moderator": "Mr Du Toit",
    "duration_stated": "150 minutes",
    "fidelity_rung": "A",
    "notes": (
        "School-set mid-year Paper 2 using the IEB NSC data sheet. Energy-profile and "
        "Maxwell-Boltzmann diagram sub-parts (4.2.2, 4.2.3, 4.3.2, 4.3.3, 4.3.4, 5.5.6) are "
        "diagram-based; the memo prints no text answer for them, so they are recorded as "
        "needs_visual with memo_answer unresolved."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (18 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Choose the correct exponent for the prefix nano. A 10^-12 / B 10^-9 / C 10^-6 / D 10^12",
     False, [], "B", ["10^-9"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Matter & Materials", "Multiple Choice",
     "Correct chemical formula for potassium permanganate. A KMnO4 / B KMnO2 / C K2MnO4 / D K2MnO2",
     False, [], "A", ["KMnO4"], "Memo gives the correct option only.", False, False),
    ("1.3", 2, "Stoichiometry", "Multiple Choice",
     "Which 20 g sample (calcium, bromine, silver) has the greatest number of moles? "
     "A calcium / B bromine / C silver / D all the same",
     False, [], "B", ["bromine: lowest M of the three"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Stoichiometry", "Multiple Choice",
     "Which best describes concentration? A mass/volume / B moles/mass / C g/mol / D moles/volume",
     False, [], "D", ["moles per unit volume"], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Reaction Rates", "Multiple Choice",
     "Maxwell-Boltzmann curve Z (ozone). Which change gives curve Y? A increase [O3] only / "
     "B increase T only / C increase [O3] and T / D addition of a catalyst",
     True, [], "A", ["concentration increase shifts the curve"], "Memo gives the correct option only; graph is an image.", True, False),
    ("1.6", 2, "Bonding", "Multiple Choice",
     "Anions are formed through... A oxidation of a metal / B oxidation of a non-metal / "
     "C reduction of a metal / D reduction of a non-metal",
     False, [], "D", ["reduction of a non-metal (gains electrons)"], "Memo gives the correct option only.", False, False),
    ("1.7", 2, "Bonding", "Multiple Choice",
     "During ionic bond formation electrons are: A shared equally / B shared unequally / "
     "C transferred metal->non-metal / D transferred non-metal->metal",
     False, [], "C", ["transferred from metal to non-metal"], "Memo gives the correct option only.", False, False),
    ("1.8", 2, "Energy & Chemical Change", "Multiple Choice",
     "Energy profile for X2 + 3Y2 -> 2XY3. Heat of reaction per mole of XY3 formed? "
     "A -92 / B -46 / C +92 / D +46 kJ",
     True, [], "B", ["-92 total / 2 mol XY3 = -46 per mole"], "Memo gives the correct option only; profile is an image.", True, False),
    ("1.9", 2, "Reaction Rates", "Multiple Choice",
     "2 g lump vs 1 g powdered zinc added to excess H2SO4; solid line is the 2 g lump. Which "
     "dotted line is the 1 g powder? (graph)",
     True, [], "B", ["powdered -> faster, lower total volume"], "Memo gives the correct option only; graph is an image.", True, False),

    # ---------------- QUESTION 2: BONDING / IMFs / STANDARD SOLUTION (23 marks) ----------------
    ("2.1.1", 2, "Bonding", "Definition/Explain",
     "CO2 and SiO2 melting/boiling points given. Define intramolecular bond.",
     False, [], "a bond between atoms within a molecule", ["bond within molecules (2)"], "Two-mark definition (AON).", False, False),
    ("2.1.2", 2, "Bonding", "Short Answer",
     "Name the specific type of intramolecular bonds in CO2 molecules.",
     False, [], "polar covalent bonds", ["polar covalent (2)"], "Two marks.", False, False),
    ("2.1.3", 1, "Matter & Materials", "Short Answer",
     "In what physical state is CO2 at room temperature (25 C)?",
     False, [], "gas", ["gas (1)"], "One mark.", False, False),
    ("2.1.4", 1, "Matter & Materials", "Short Answer",
     "In what physical state is SiO2 at 2000 C?",
     False, [], "liquid / molten", ["liquid or molten (1)"], "One mark.", False, False),
    ("2.1.5", 5, "Bonding", "Explanation",
     "Explain why SiO2 has a much higher melting point than CO2, referring to the lattice diagrams "
     "and relative strengths of the lattice structures.",
     True, [], "CO2: molecular lattice, molecules held by weak London forces; SiO2: atomic lattice, atoms held by strong covalent bonds; more energy to break strong bonds",
     ["CO2 molecular lattice (1)", "weak London forces (1)", "SiO2 atomic lattice (1)", "strong covalent bonds (1)", "more energy to break strong bonds (1)"],
     "Five marks; lattice diagrams are images.", True, False),
    ("2.2.1", 2, "Intermolecular Forces", "Definition/Explain",
     "Prepare 0,25 L of 0,2 mol/dm3 oxalic acid (COOH)2.2H2O. Define intermolecular force.",
     False, [], "weak force of attraction between discrete molecules, ions or noble-gas atoms",
     ["weak attraction between molecules/ions/atoms (2)"], "Two-mark definition (AON).", False, False),
    ("2.2.2", 2, "Intermolecular Forces", "Short Answer",
     "Name the intermolecular forces between solute and solvent in the solution.",
     False, [], "dipole-dipole forces", ["dipole-dipole (2)"], "Two marks.", False, False),
    ("2.2.3", 5, "Stoichiometry", "Calculation",
     "Calculate the mass of (COOH)2.2H2O required to make the standard solution (M = 90+36 = 126).",
     False, ["n=cV", "m=nM"], "6,3 g",
     ["n = c x V = 0,2 x 0,25 = 0,05 mol (1)", "M = 90+36 = 126 (1)", "m = 0,05 x 126 = 6,3 g (2)"],
     "Five marks across formula, substitution, molar mass, answer.", False, False),
    ("2.2.4", 3, "Stoichiometry", "Explanation",
     "When making a standard solution, must solute or water be added to the volumetric flask first? Explain.",
     False, [], "solute first — adding water first gives wrong concentration (particles add to total volume)",
     ["solute first (1)", "wrong concentration otherwise (1)", "particles add to total volume (1)"],
     "Three marks.", False, False),

    # ---------------- QUESTION 3: BONDING AND IMFs (24 marks) ----------------
    ("3.1", 4, "Bonding", "Explanation",
     "Use bonding principles to explain whether CH4 is polar or non-polar.",
     False, [], "non-polar — contains polar bonds but the molecule is electron-symmetry balanced",
     ["polar bonds (1)", "electron symmetry (1)", "non-polar (1)"], "Four marks.", False, False),
    ("3.2", 4, "Intermolecular Forces", "Explanation",
     "NH3 has a much higher boiling point than CH4. Account for this with the relevant IMF in each.",
     False, [], "NH3: hydrogen bonding (strong IMF) needs much energy to overcome; CH4: weak London forces",
     ["NH3 hydrogen bond, strong IMF (1)", "needs high energy (1)", "CH4 London forces (1)", "low Bpt (1)"],
     "Four marks.", False, False),
    ("3.3", 2, "Intermolecular Forces", "Short Answer",
     "From the table, which has the stronger IMF: PH3 or CH4? Explain briefly.",
     False, [], "PH3 (it has the higher boiling point)",
     ["PH3 higher Bpt (1)", "stronger IMF (1)"], "Two marks.", False, False),
    ("3.4.1", 2, "Intermolecular Forces", "Short Answer",
     "State two properties of the nitrogen atom responsible for the hydrogen-bond forces in liquid NH3.",
     False, [], "high electronegativity; small atom (or at least one lone pair)",
     ["high electronegativity (1)", "small atom / lone pair (1)"], "Two marks (any two).", False, False),
    ("3.4.2", 4, "Intermolecular Forces", "Diagram-based",
     "Show how two NH3 molecules interact in the liquid phase using Couper diagrams; show d+ and d-.",
     False, [], "H-bond N(delta-)...H(delta+) between the molecules",
     ["Couper structure correct (1)", "d- on N, d+ on H (1)", "interaction shown (1)"],
     "Three-mark structure; diagram-based.", False, False),
    ("3.4.3", 1, "Bonding", "Short Answer",
     "Are the bonds in ammonia sigma or pi bonds?",
     False, [], "sigma bonds", ["sigma (1)"], "One mark.", False, False),
    ("3.4.4", 2, "Bonding", "Definition/Explain",
     "Define covalent bond.",
     False, [], "sharing of at least one electron pair by two non-metal atoms",
     ["sharing electron pair (1)", "two non-metals (1)"], "Two marks.", False, False),
    ("3.4.5", 2, "Bonding", "Definition/Explain",
     "What is a dative covalent bond?",
     False, [], "when a lone pair of one atom overlaps the empty orbital of another atom",
     ["lone pair overlaps (1)", "empty orbital of another (1)"], "Two marks.", False, False),
    ("3.4.6", 3, "Bonding", "Diagram-based",
     "Draw the ammonium ion (NH4+) using Lewis notation.",
     False, [], "N central, four N-H single bonds, + charge",
     ["ion charge (1)", "electrons correct (1)", "4 H + 1 N (1)"], "Three marks; Lewis diagram.", False, False),

    # ---------------- QUESTION 4: STOICHIOMETRY + ENERGY PROFILE (28 marks) ----------------
    ("4.1.1", 2, "Stoichiometry", "Calculation",
     "CaCO3(s) + 2HCl -> CaCl2 + CO2 + H2O. 5 g CaCO3 added to 0,25 dm3 of 2 mol/dm3 HCl. "
     "Calculate moles of CaCO3 added.",
     False, ["n=m/M"], "0,05 mol", ["n = m/M (1)", "n = 5/100 (1)", "= 0,05 mol"], "Two marks (M CaCO3 = 100).", False, False),
    ("4.1.2", 4, "Stoichiometry", "Calculation",
     "Prove that CaCO3 is the limiting reagent.",
     False, ["n=cV"], "CaCO3 limiting",
     ["n(HCl) = cV = 2 x 0,25 = 0,5 mol (1)", "ratio 1:2 (1)", "0,05 CaCO3 needs 0,1 HCl; only 0,5 available but CaCO3 exhausts first (1)", "CaCO3 limiting (1)"],
     "Four marks; memo uses an option-table method.", False, False),
    ("4.1.3", 3, "Stoichiometry", "Calculation",
     "Determine the volume of unreacted HCl.",
     False, ["c=n/V"], "0,2 dm3",
     ["n(HCl) reacted = 0,5 - 0,1 = 0,4 mol (1)", "V = n/c (1)", "= 0,4/2 = 0,2 dm3 (1)"], "Three marks.", False, False),
    ("4.2.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define activated complex.",
     True, [], "temporary transition state between reactants and products",
     ["temporary (1)", "transition state (1)"], "Two marks; profile is an image.", True, False),
    ("4.2.2", 5, "Energy & Chemical Change", "Diagram-based",
     "The energy profile is labelled I-V. Provide the labels of these energies from I to V.",
     True, [], "unresolved (memo prints no text labels; relies on the profile diagram)",
     [], "Memo leaves this blank; the energy-profile diagram is an image.", True, False),
    ("4.2.3", 3, "Energy & Chemical Change", "Diagram-based",
     "Is the energy profile ENDOTHERMIC or EXOTHERMIC? Explain.",
     True, [], "unresolved (memo prints no text; conclusion depends on the profile diagram)",
     [], "Memo leaves this blank; profile is an image and not readable from the text layer.", True, False),
    ("4.3.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define catalyst.",
     False, [], "substance that increases the rate of reaction but is unchanged by the end",
     ["increases rate (1)", "unchanged at end (1)"], "Two marks.", False, False),
    ("4.3.2", 2, "Energy & Chemical Change", "Diagram-based",
     "On the answer sheet, draw a new graph to show the effect of a catalyst on the reaction.",
     True, [], "lower-activation-energy pathway drawn on the profile",
     ["catalyst curve drawn (1)"], "Two marks; on the diagram.", True, False),
    ("4.3.3", 3, "Energy & Chemical Change", "Explanation",
     "How would a catalyst affect the value of energy V? Explain.",
     True, [], "V (the enthalpy/heat of reaction) is unchanged — a catalyst lowers activation energy but not dH",
     ["V unchanged (1)", "catalyst lowers Ea (1)", "does not change dH (1)"],
     "Three marks; memo blank but standard result.", True, False),
    ("4.3.4", 2, "Reaction Rates", "Diagram-based",
     "On the answer sheet, draw the Maxwell-Boltzmann distribution for 100 C over the 25 C one.",
     True, [], "curve for 100 C below/right of the 25 C curve, same area, same activation-energy line",
     ["10-degree (higher-T) curve below 25 C curve (1)", "same activation energy (1)"],
     "Two marks; distribution is an image.", True, False),

    # ---------------- QUESTION 5: REACTION RATE (31 marks) ----------------
    ("5.1", 2, "Reaction Rates", "Definition/Explain",
     "Zn + 2HCl -> ZnCl2 + H2, dH<0. Define reaction rate.",
     False, [], "the change in concentration per unit time of a reactant or product",
     ["change in concentration (1)", "per unit time (1)"], "Two marks.", False, False),
    ("5.2", 2, "Reaction Rates", "Explanation",
     "Briefly explain why measuring mass over time is not suitable for measuring this reaction's rate.",
     False, [], "some mass is released as a gas (H2 leaves the system)",
     ["mass released as gas (1)", "H2 escapes (1)"], "Two marks.", False, False),
    ("5.3", 2, "Reaction Rates", "Short Answer",
     "Scott (1,0 M HCl, 0,5 g Zn granules) and Riley (2,0 M HCl, 0,6 g Zn powder) vary HCl concentration. "
     "What is the independent variable?",
     False, [], "concentration of HCl", ["concentration (1)", "of HCl (1)"], "Two marks.", False, False),
    ("5.4", 2, "Reaction Rates", "Short Answer",
     "State one variable controlled in both experiments other than volume of HCl.",
     False, [], "temperature (or volume of HCl already excluded)", ["temperature (1)", "or other controlled var (1)"], "Two marks.", False, False),
    ("5.5.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define heat of reaction.",
     False, [], "the net change in chemical potential energy of the system",
     ["net change (1)", "chemical potential energy (1)"], "Two marks (AON).", False, False),
    ("5.5.2", 2, "Reaction Rates", "Explanation",
     "Describe briefly why the reaction rate increases during the first two seconds (Scott's graph).",
     True, [], "the reaction is exothermic, so temperature initially rises, releasing heat",
     ["exothermic (1)", "temperature rises / releases heat (1)"], "Two marks; graph is an image.", True, False),
    ("5.5.3", 4, "Reaction Rates", "Explanation",
     "With reference to HCl, use collision theory to explain why the rate decreases after the first two seconds.",
     False, [], "HCl concentration falls -> fewer particles per volume -> fewer collisions/s -> fewer effective collisions/s -> decreasing rate",
     ["[HCl] decreases (1)", "fewer particles/volume (1)", "fewer collisions/s (1)", "fewer effective collisions (1)"],
     "Four marks across the collision-theory chain.", False, False),
    ("5.5.4", 5, "Stoichiometry", "Calculation",
     "Determine volume A of H2 produced (cm3), at STP. (0,5 g Zn, 65,4 g/mol)",
     False, ["n=m/M", "V=n.Vm"], "171,25 cm3 (171 cm3)",
     ["n(Zn)=0,5/65,4=7,65e-3 mol (1)", "ratio 1:1 -> n(H2)=7,65e-3 (1)", "V=n.Vm=0,171 dm3 (1)", "=171,25 cm3 (2)"],
     "Five marks; final two for the cm3 conversion.", False, False),
    ("5.5.5", 3, "Scientific Skills", "Calculation",
     "Teacher said A should have been 200 cm3. Calculate the percentage accuracy of Scott's results.",
     False, [], "14,38%",
     ["%acc = (200-171,225)/200 x 100 (1)", "= 14,38% (2)"], "Three marks.", False, False),
    ("5.5.6", 3, "Reaction Rates", "Diagram-based",
     "On the answer sheet, sketch the graph expected from Riley's experiment; label 'RILEY'.",
     True, [], "steeper, ends sooner, ends above A",
     ["steeper (1)", "ends sooner (1)", "ends above A (1)"], "Three marks; on the graph.", True, False),
    ("5.6", 4, "Scientific Skills", "Explanation",
     "Would Scott and Riley's investigation produce reliable results? Explain.",
     False, [], "No — the state of Zn was not controlled (surface area also affects rate); not repeated enough",
     ["No (1)", "Zn state not controlled (1)", "surface area affects rate (1)", "not repeated >3 times (1)"],
     "Four marks.", False, False),

    # ---------------- QUESTION 6: YIELD / STOICHIOMETRY (18 marks) ----------------
    ("6.1.1", 2, "Stoichiometry", "Definition/Explain",
     "Aspirin made from salicylic acid + acetic anhydride. Define molar mass.",
     False, [], "the mass (in grams) of one mole of a substance", ["mass of one mole in grams (2)"], "Two marks (all or nothing).", False, False),
    ("6.1.2", 2, "Stoichiometry", "Calculation",
     "Calculate the molar mass of salicylic acid (C7H6O3).",
     False, [], "138 g/mol", ["M = 7x12 + 6 + 3x16 (1)", "= 138 g/mol (1)"], "Two marks.", False, False),
    ("6.1.3", 6, "Stoichiometry", "Calculation",
     "3,86 g salicylic acid reacted (1:1) with excess acetic anhydride. Calculate mass of aspirin produced. (M aspirin = 180)",
     False, ["n=m/M", "m=nM"], "5,04 g",
     ["n = 3,86/138 = 0,028 mol (2)", "1:1 -> 0,028 mol aspirin (1)", "m = 0,028 x 180 = 5,04 g (2)"],
     "Six marks.", False, False),
    ("6.1.4", 3, "Stoichiometry", "Calculation",
     "Only 4,65 g aspirin produced. Calculate the percentage yield.",
     False, ["% yield = actual/theoretical x 100"], "92,26%",
     ["4,65/5,03 x 100 (1)", "= 92,26% (2)"], "Three marks.", False, False),
    ("6.2", 5, "Stoichiometry", "Calculation",
     "A tablet contains 300 mg aspirin. Calculate the number of hydrogen atoms in the tablet. (M aspirin = 180, 8 H per molecule)",
     False, ["n=m/M", "N=n.Na"], "8,03 x 10^21 H atoms",
     ["n = 0,3/180 = 0,00167 mol (1)", "1 mol aspirin = 8 mol H -> 0,0133 mol H (1)", "x 6,02x10^23 = 8,03x10^21 (2)"],
     "Five marks.", False, False),

    # ---------------- QUESTION 7: DILUTION / IONS (20 marks) ----------------
    ("7.1.1", 2, "Stoichiometry", "Definition/Explain",
     "500 cm3 of 1,5 mol/dm3 Na2SO4 diluted to 0,25 mol/dm3. Define solvent.",
     False, [], "the substance in which another substance is dissolved to form a solution",
     ["substance dissolving another (2)"], "Two marks.", False, False),
    ("7.1.2", 1, "Stoichiometry", "Short Answer",
     "Identify the solvent in the above solution.",
     False, [], "water", ["water (1)"], "One mark.", False, False),
    ("7.1.3", 5, "Stoichiometry", "Calculation",
     "Calculate how much water (dm3) was added to dilute to 0,25 mol/dm3.",
     False, ["c1v1=c2v2"], "2,5 dm3",
     ["n = 1,5 x 0,5 = 0,75 mol (1)", "0,25 = 0,75/V (1)", "V = 3 dm3 (1)", "added = 3 - 0,5 = 2,5 dm3 (1)"],
     "Five marks; moles conserved on dilution.", False, False),
    ("7.2.1", 4, "Bonding", "Short Answer",
     "Write the balanced dissociation equation for Mg(NO3)2 in water, with state symbols.",
     False, [], "Mg(NO3)2(s) -> Mg2+(aq) + 2NO3-(aq)",
     ["Mg2+(aq) (1)", "2NO3-(aq) (1)", "-> (1)", "state symbols correct (1)"], "Four marks; phase indicators required.", False, False),
    ("7.2.2", 3, "Stoichiometry", "Calculation",
     "200 cm3 of 0,15 mol/dm3 Mg(NO3)2. Calculate moles of nitrate ions (NO3-) in the solution.",
     False, ["n=cV"], "0,06 mol NO3-",
     ["n = 0,15 x 0,2 = 0,03 mol Mg(NO3)2 (1)", "x2 = 0,06 mol NO3- (1)"], "Three marks.", False, False),
    ("7.2.3", 5, "Stoichiometry", "Calculation",
     "NaNO3 dissolved; total [NO3-] becomes 0,50 mol/dm3, no volume change. Calculate mass of NaNO3 dissolved. (M = 85)",
     False, ["n=cV", "m=nM"], "3,4 g",
     ["x + 0,06x0,2... -> x = 0,04 mol NaNO3 (2)", "m = 0,04 x 85 = 3,4 g (2)"],
     "Five marks; memo uses x + 0,06*0,2 = 0,50.", False, False),
]
