"""Pass 1 evidence table — Grade 11 Physical Science Paper 2 (Chemistry), 19 July 2018.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/Gr 11 July exam chemistry 2018.pdf   (130 marks, Mrs Angelova)
Memo:   data/organized/chemistry/Gr 11 July exam chemistry 2018 MG .pdf  (130 marks, Mrs Angelova)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2018-JUL",
    "paper_path": "data/organized/chemistry/Gr 11 July exam chemistry 2018.pdf",
    "memo_path": "data/organized/chemistry/Gr 11 July exam chemistry 2018 MG .pdf",
    "year": 2018,
    "exam_date": "19 July 2018",
    "exam_period": "june",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 130,
    "examiner": "Mrs Angelova",
    "moderator": "Mr McCoy",
    "duration_stated": "120 minutes",
    "fidelity_rung": "A",
    "notes": (
        "School-set mid-year Paper 2 (Chemistry) with a data sheet. Question 6 refers to an "
        "ANSWER SHEET graph that is not part of the extractable text layer; graph-plotting "
        "sub-parts are recorded as needs_visual."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (12 marks) ----------------
    ("1.1", 2, "Reaction Rates", "Multiple Choice",
     "Blade investigated the rate of Zn(s) + 2HNO3(aq) -> Zn(NO3)2(aq) + H2(g) at 0 C and 10 C, "
     "1,0 M acid in excess; a graph shows volume of gas vs time. Which apparatus would he have "
     "used to collect the data shown in the graph? A Scale / B Pressure sensor / C Syringe / D Spectrometer",
     True, [], "C",
     ["Syringe collects the gas volume plotted on the graph"],
     "Memo gives the correct option only.", True, False),
    ("1.2", 2, "Reaction Rates", "Multiple Choice",
     "Which curve on the graph shows the reaction carried out at 10 C? (curves 1-4 labelled)",
     True, [], "A",
     ["higher temperature -> faster reaction -> steeper/sharper curve"],
     "Memo gives the correct option only; graph is an image.", True, False),
    ("1.3", 2, "Stoichiometry", "Multiple Choice",
     "What mass of zinc (g) did Blade use at 0 C? A 0,09 / B 0,17 / C 30,0 / D 87,1",
     False, [], "A",
     ["0,09 g from the stoichiometry of the gas volume"],
     "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Reaction Rates", "Multiple Choice",
     "Which curve shows the reaction when the same mass of zinc at 0 C is reacted with 0,5 M "
     "nitric acid (half the concentration)? A 1 / B 2 / C 3 / D 4",
     True, [], "D",
     ["lower concentration -> slower reaction"],
     "Memo gives the correct option only; graph is an image.", True, False),
    ("1.5", 2, "Bonding", "Multiple Choice",
     "Which does NOT contain a dative covalent bond? A CO2 / B SO2 / C SO3 / D NH4+",
     False, [], "A",
     ["CO2 has only double covalent bonds; NH4+ has a dative bond"],
     "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Matter & Materials", "Multiple Choice",
     "Chemical formula for ammonium dichromate? A (NH3)2Cr2O7 / B (NH4)2Cr2O7 / C NH4Cr2O7 / D NH3Cr2O7",
     False, [], "B",
     ["ammonium is NH4+; dichromate is Cr2O7 2-"],
     "Memo gives the correct option only.", False, False),

    # ---------------- QUESTION 2: BONDING AND IMFs (23 marks) ----------------
    ("2.1", 2, "Bonding", "Short Answer",
     "Nathan tests Group 1 reactivity (Li, Na, K) in oxygen. Describe one variable he should keep "
     "the same to ensure a fair test.",
     False, [], "size/amount of the metal cube (or heat intensity of the flame)",
     ["size/amount of cube (1)", "or flame heat intensity (1)"],
     "Two marks; either controlled variable accepted.", False, False),
    ("2.2", 2, "Bonding", "Explanation",
     "Explain why the table of results (colour/flame observations) cannot be used to determine "
     "which metal was most reactive.",
     False, [], "data only gives flame colour/presence; no indication of ease of reactivity (qualitative, not quantitative)",
     ["only flame colour given (1)", "no measure of ease of reactivity / data is qualitative not quantitative (1)"],
     "Two marks for the qualitative-vs-quantitative argument.", False, False),
    ("2.3.1", 2, "Bonding", "Definition/Explain",
     "Consider Li + O2 -> Li2O. Define the term oxidation.",
     False, [], "loss of electrons", ["loss of electrons (2)"],
     "Two-mark definition.", False, False),
    ("2.3.2", 2, "Bonding", "Short Answer",
     "Write the oxidation half reaction for formation of lithium oxide.",
     False, [], "Li -> Li+ + 1e-", ["Li (1)", "Li+ + e- (1)"],
     "Half-reaction with electron.", False, False),
    ("2.3.3", 3, "Bonding", "Short Answer",
     "Give the net ionic reaction for lithium + oxygen -> lithium oxide.",
     False, [], "2Li + O -> 2Li+ + O2- (then Li2O)",
     ["2Li + O (1)", "-> 2Li+ + O2- (1)", "balancing (1)"],
     "Three marks; balancing separately marked.", False, False),
    ("2.4.1", 2, "Bonding", "Explanation",
     "Use particle diagram A (sodium metal) to explain why sodium conducts electricity.",
     True, [], "free electrons move about the crystal / act as charge carriers",
     ["free/delocalised electrons move (1)", "they are the charge carriers (1)"],
     "Diagram A is an image; conduction explained via mobile electrons.", True, False),
    ("2.4.2", 4, "Intermolecular Forces", "Explanation",
     "Explain fully why sodium is a solid while oxygen is a gas at room temperature. Refer to "
     "intermolecular and intramolecular forces.",
     True, [], "sodium has metallic bonding (strong intramolecular); oxygen is discrete molecules with weak London IMFs; less energy needed to overcome oxygen's IMFs",
     ["sodium: metallic bonding, strong intramolecular (1)", "oxygen: discrete molecule, weak London IMFs (1)",
      "less energy to overcome IMFs in oxygen (1)", "compared to Na's intramolecular bond (1)"],
     "Four marks across the two substances and the energy comparison.", True, False),
    ("2.5.1", 3, "Bonding", "Short Answer",
     "Potassium burns in oxygen to form K2O. Write the dissociation reaction of K2O(s) dissolving "
     "in water, including state symbols.",
     False, [], "K2O(s) -> 2K+(aq) + O2-(aq)",
     ["K2O(s) (1)", "-> 2K+(aq) (1)", "+ O2-(aq) (1)"],
     "State symbols separately marked.", False, False),
    ("2.5.2", 3, "Bonding", "Explanation",
     "Diagram shows K2O dissolving; the ion is surrounded by water molecules. Is the ion the "
     "potassium ion or the oxide ion? Explain fully.",
     True, [], "potassium ion (K+) — water is polar with a negative region oriented towards the ion, so the ion must be positive",
     ["potassium ion (1)", "water is polar / has + and - regions (1)",
      "negative region toward the ion so ion is positive (1)"],
     "Three marks; reasoning from water polarity.", True, False),

    # ---------------- QUESTION 3: BONDING AND ENERGY (25 marks) ----------------
    ("3.1", 2, "Bonding", "Diagram-based",
     "Draw a Lewis diagram to show the bonding in ethene (C2H4).",
     False, [], "Lewis structure: C=C double bond, each C single-bonded to two H",
     ["correct C skeleton with double bond", "lone pairs shown"],
     "Memo shows the diagram; two marks for the structure.", False, False),
    ("3.2", 2, "Bonding", "Diagram-based",
     "On the Lewis diagram, label the pi and sigma bonds between the carbon atoms.",
     False, [], "sigma = head-on C-C overlap; pi = side-on overlap above/below the bond",
     ["pi bond labelled (1)", "sigma bond labelled (1)"],
     "Two marks for the two bond types.", False, False),
    ("3.3a", 2, "Bonding", "Calculation",
     "State the polarity of the C-H bond and use a calculation to substantiate. (electronegativities C=2,5, H=2,1)",
     False, [], "polar covalent; END = 2,5 - 2,1 = 0,4 > 0",
     ["END = 2,5 - 2,1 = 0,4 (1)", "polar covalent bond (1)"],
     "Two marks; calculation of electronegativity difference.", False, False),
    ("3.3b", 2, "Bonding", "Calculation",
     "State the polarity of the C=C bond and use a calculation to substantiate.",
     False, [], "pure covalent (non-polar); END = 0",
     ["END C=C = 0 (1)", "pure covalent bond (1)"],
     "Two marks.", False, False),
    ("3.4", 2, "Bonding", "Explanation",
     "Use 3.3 and other information to explain whether a molecule of ethene is polar or non-polar.",
     False, [], "non-polar — electron cloud is symmetrical",
     ["electron cloud symmetrical (1)", "non-polar molecule (1)"],
     "Two marks for the symmetry argument.", False, False),
    ("3.5.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define the term activated complex (for C2H5OH -> C2H4 + H2O, dH=+45 kJ/mol).",
     False, [], "a high-energy, unstable, temporary transition state between reactants and products",
     ["high energy / unstable (1)", "temporary transition state (1)"],
     "Two-mark definition.", False, False),
    ("3.5.2", 4, "Energy & Chemical Change", "Diagram-based",
     "Sketch a labelled energy profile diagram for the dehydration of ethanol (not to scale) "
     "without a catalyst. Include: activated complex, dH.",
     True, [], "products higher than reactants by +45 kJ/mol; peak labelled activated complex; dH arrow shown",
     ["axis labels (1)", "shape (1)", "activated complex labelled (1)", "dH shown (1)"],
     "Four marks; diagram is an image.", True, False),
    ("3.5.3", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define the term catalyst.",
     False, [], "substance that increases the rate of reaction but is unchanged at the end",
     ["increases rate (1)", "remains unchanged (1)"],
     "Two-mark definition.", False, False),
    ("3.5.4", 1, "Energy & Chemical Change", "Diagram-based",
     "On your diagram, show the effect of a catalyst using a dotted line.",
     True, [], "dotted lower-energy pathway on the diagram",
     ["catalyst line shown (1)"],
     "One mark; on the diagram.", True, False),
    ("3.5.5", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define the term enthalpy change.",
     False, [], "the net change in chemical potential energy of the system",
     ["net change (1)", "chemical potential energy of system (1)"],
     "Two-mark definition.", False, False),
    ("3.5.6", 1, "Energy & Chemical Change", "Short Answer",
     "Is energy released or absorbed when bonds within ethanol are broken?",
     False, [], "absorbed", ["absorbed (1)"],
     "One mark.", False, False),
    ("3.5.7", 1, "Energy & Chemical Change", "Short Answer",
     "Is energy released or absorbed when new bonds in ethene and water are formed?",
     False, [], "released", ["released (1)"],
     "One mark.", False, False),
    ("3.5.8", 2, "Energy & Chemical Change", "Explanation",
     "Use 3.5.6 and 3.5.7 to explain why the net enthalpy change for dehydration of ethanol is positive.",
     False, [], "more energy absorbed breaking bonds than released forming bonds (endothermic)",
     ["energy gained in endothermic step greater (1)", "more absorbed than released (1)"],
     "Two marks; links to dH=+45.", False, False),

    # ---------------- QUESTION 4: STOICHIOMETRY (27 marks) ----------------
    ("4.1", 2, "Stoichiometry", "Short Answer",
     "Give the chemical formula for aluminium oxide.",
     False, [], "Al2O3", ["Al2O3 (2)"],
     "Two marks for the formula.", False, False),
    ("4.2.1", 4, "Stoichiometry", "Calculation",
     "200 ml of 2,0 mol/dm3 NaOH reacts with excess Al2O3 and 12 g water: Al2O3 + 2NaOH + 3H2O "
     "-> 2NaAl(OH)4. Determine which reagent (NaOH or water) is limiting.",
     False, ["n=cV", "n=m/M"], "NaOH is limiting (0,4 mol NaOH available; needs 0,6 mol H2O but only 0,67 available)",
     ["n(NaOH)=2x0,2=0,4 mol (1)", "n(H2O)=12/18=0,67 mol (1)",
      "stoich 2:3 -> 0,4 NaOH needs 0,6 H2O (1)", "H2O enough, so NaOH limiting (1)"],
     "Four marks across the two mole calculations and the comparison.", False, False),
    ("4.2.2", 2, "Stoichiometry", "Definition/Explain",
     "Explain the term 'Yield' in the context of a chemical reaction.",
     False, [], "measure of the extent of reaction; compared to the maximum possible product",
     ["extent of reaction (1)", "vs amount possible (1)"],
     "Two-mark definition.", False, False),
    ("4.2.3", 5, "Stoichiometry", "Calculation",
     "If 45 g NaAl(OH)4 is produced, determine the percentage yield. (M of NaAl(OH)4 = 118)",
     False, ["m=nM", "% yield = actual/theoretical x 100"], "95,33%",
     ["theoretical: 0,4 mol NaAl(OH)4 (1)", "m = 0,4 x 118 = 47,2 g (1)",
      "% = 45/47,2 x 100 (1)", "= 95,33% (2)"],
     "Five marks; final two for the computed percentage.", False, False),
    ("4.3.1", 3, "Stoichiometry", "Calculation",
     "Fe2O3 + 3CO -> 2Fe + 3CO2. 1 kg Fe must be produced, 100% efficient, CO excess. Determine "
     "the amount of iron oxide required (in moles).",
     False, ["n=m/M"], "8,93 mol Fe2O3",
     ["n(Fe)=1000/56=17,86 mol (1)", "Fe:Fe2O3 = 2:1 (1)", "8,93 mol Fe2O3 (1)"],
     "Three marks.", False, False),
    ("4.3.2", 4, "Stoichiometry", "Calculation",
     "Determine the number of iron atoms required.",
     False, ["N=n.Na"], "1,075 x 10^25 Fe atoms",
     ["8,93 x 6,02x10^23 Fe2O3 units (1)", "x2 = 1,075x10^25 (1)"],
     "Four marks; both conversion steps.", False, False),
    ("4.3.3", 3, "Stoichiometry", "Calculation",
     "Determine the volume of CO2 produced at STP if 1 kg Fe produced.",
     False, ["V=n.Vm"], "600 dm3",
     ["moles CO2 = 26,79 (1)", "V = 26,79 x 22,4 (1)", "= 600 dm3 (1)"],
     "Three marks; Vm=22,4 dm3/mol at STP.", False, False),
    ("4.3.4", 4, "Stoichiometry", "Calculation",
     "What mass of iron oxide would be required if the reaction was only 70% efficient? 1 kg Fe "
     "still required.",
     False, ["m=nM"], "2041,14 g Fe2O3",
     ["8,93/0,7 = 12,75 mol (1)", "m = 12,75 x 160 (1)", "= 2041,14 g (2)"],
     "Four marks; efficiency handled via dividing by 0,7.", False, False),

    # ---------------- QUESTION 5: STOICHIOMETRY / TITRATION (17 marks) ----------------
    ("5.1", 2, "Stoichiometry", "Definition/Explain",
     "Explain what is meant by 'water of crystallization' (hydrated sodium carbonate Na2CO3.xH2O).",
     False, [], "water associated with crystal formation / found in the crystalline framework of a salt",
     ["associated with crystal formation (1)", "in the crystalline framework (1)"],
     "Two-mark definition.", False, False),
    ("5.2", 2, "Stoichiometry", "Short Answer",
     "Explain what is meant by the 'x' in Na2CO3.xH2O.",
     False, [], "number of water molecules per formula unit of the salt",
     ["number of water molecules (1)", "per unit of salt (1)"],
     "Two marks.", False, False),
    ("5.3", 1, "Stoichiometry", "Short Answer",
     "A solution of known concentration is referred to as a ...?",
     False, [], "standard solution", ["standard solution (1)"],
     "One mark.", False, False),
    ("5.4", 3, "Stoichiometry", "Calculation",
     "Determine the volume of water to add to 200 ml of 10 M HCl to prepare 2 M HCl. (c1v1=c2v2)",
     False, ["c1v1=c2v2"], "800 ml (0,8 dm3) added",
     ["c1v1=c2v2 (1)", "10x200=2xV2 -> V2=1000 ml (1)", "add 1000-200=800 ml (1)"],
     "Three marks; final for the volume added.", False, False),
    ("5.5", 3, "Stoichiometry", "Calculation",
     "23,5 ml of 2 M HCl reacted with hydrated Na2CO3: Na2CO3 + 2HCl -> 2NaCl + CO2 + H2O. "
     "Determine the moles of dehydrated Na2CO3 that reacted.",
     False, ["n=cV"], "0,0235 mol Na2CO3",
     ["n(HCl)=2x0,0235=0,047 mol (1)", "ratio 1:2 (1)", "0,0235 mol Na2CO3 (1)"],
     "Three marks.", False, False),
    ("5.6", 3, "Stoichiometry", "Calculation",
     "Mass of dehydrated Na2CO3 that reacted is 2,491 g. If the hydrated mass was 5 g, determine "
     "the moles of water in the water of crystallization.",
     False, ["n=m/M"], "0,139 mol H2O",
     ["mass water = 5 - 2,491 = 2,509 g (1)", "n = 2,509/18 (1)", "= 0,139 mol (1)"],
     "Three marks.", False, False),
    ("5.7", 3, "Stoichiometry", "Calculation",
     "Hence determine x in Na2CO3.xH2O.",
     False, [], "x = 6",
     ["ratio H2O:Na2CO3 = 0,139:0,0235 = 5,93:1 (1)", "whole number -> x=6 (2)"],
     "Three marks; memo requires a whole number.", False, False),

    # ---------------- QUESTION 6: SCIENTIFIC SKILLS / REACTION RATES (26 marks) ----------------
    ("6.1", 2, "Scientific Skills", "Definition/Explain",
     "Katlego investigated Mg + CuSO4 (rate via temperature rise). Define the term temperature.",
     False, [], "a measure of the average kinetic energy of the particles",
     ["measure (1)", "average kinetic energy of particles (1)"],
     "Two-mark definition.", False, False),
    ("6.2", 2, "Scientific Skills", "Short Answer",
     "Identify the independent variable in Katlego's experiment.",
     False, [], "mass of magnesium powder (increase/change in temperature is the dependent variable)",
     ["mass of magnesium (1)", "change in temperature (1)"],
     "Two marks; independent + dependent.", False, False),
    ("6.3", 2, "Scientific Skills", "Explanation",
     "Katlego concluded 2,0 g Mg gave the most accurate results. Comment on the validity of his statement.",
     False, [], "NOT valid — the 2,0 g results are precise, but he has no known true value to judge accuracy",
     ["not valid (1)", "results precise but accuracy needs a known normal (1)"],
     "Two marks; precision vs accuracy.", False, False),
    ("6.4.1", 2, "Scientific Skills", "Diagram-based",
     "On the answer-sheet graph: provide the axis labels.",
     True, [], "x: mass of Mg (g); y: average increase in temperature (C)",
     ["x-axis label (1)", "y-axis label (1)"],
     "Graph on answer sheet (image); two marks.", True, False),
    ("6.4.2", 1, "Scientific Skills", "Diagram-based",
     "Provide a suitable scale for the y axis.",
     True, [], "a scale covering 0-7 C in sensible increments",
     ["suitable y scale (1)"],
     "One mark; on the graph.", True, False),
    ("6.4.3", 2, "Scientific Skills", "Diagram-based",
     "Plot the missing values on the graph.",
     True, [], "all points plotted correctly",
     ["points plotted (2)"],
     "Two marks; plotting.", True, False),
    ("6.4.4", 2, "Scientific Skills", "Diagram-based",
     "Draw a best-fit curve for the data.",
     True, [], "smooth best-fit curve through the origin",
     ["curve of best fit (1)", "goes through origin (1)"],
     "Two marks.", True, False),
    ("6.5", 2, "Scientific Skills", "Data/Graph Interpretation",
     "Use your graph to find the mass of Mg to produce a 3 C temperature rise (two dotted lines).",
     True, [], "0,65-0,7 g",
     ["read from graph (1)", "0,65-0,7 g (1)"],
     "Two marks; from the plotted graph.", True, False),
    ("6.6", 2, "Reaction Rates", "Explanation",
     "Explain why the temperature rise stays relatively constant for the last three mass readings "
     "(1,5; 2,0; 2,5 g).",
     False, [], "CuSO4 became limiting — no more Mg could react",
     ["CuSO4 limiting (1)", "no more Mg could react (1)"],
     "Two marks.", False, False),
    ("6.7", 4, "Reaction Rates", "Explanation",
     "Explain fully why the temperature rise increased as Mg mass increased from 0 to 1,5 g.",
     False, [], "exothermic; more Mg particles -> more frequent successful collisions (more reactant, higher rate)",
     ["exothermic, produces heat (1)", "Mg limiting so more particles (1)",
      "more collisions with sufficient energy/orientation (1)", "rate increases (1)"],
     "Four marks across the collision-theory chain.", False, False),
    ("6.8", 2, "Reaction Rates", "Diagram-based",
     "On the graph, show the effect of using zinc GRANULES instead of zinc powder (label 'Question 6.8').",
     True, [], "less steep curve ending at the same point",
     ["less steep curve (1)", "ends at same point (1)"],
     "Two marks; surface-area effect on the graph.", True, False),
    ("6.9", 3, "Reaction Rates", "Explanation",
     "Explain your answer to 6.8.",
     False, [], "granules have smaller surface area -> fewer exposed particles -> fewer successful collisions per second",
     ["surface area decreased (1)", "less exposed solid (1)", "fewer successful collisions (1)"],
     "Three marks.", False, False),
]
