"""Pass 1 evidence table — Grade 11 Chemistry Final Examination, 27 November 2023.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/PS11 - Chemistry Exam Nov 2023 - QP Final(2).pdf (165 marks, Mr Ntombela)
Memo:   data/organized/chemistry/PS11 - Chemistry Exam Nov 2023 - MG.pdf        (165 marks, Mr Ntombela)

NOTE: the memo mislabels QUESTION 5 as "29 MARKS"; the question paper's printed
per-question total for Q5 is 13 and the memo's own marking for Q5 sums to 13. The
evidence is aligned to the paper's printed TOTAL of 165 (Q5 = 13 marks).

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2023-NOV",
    "paper_path": "data/organized/chemistry/PS11 - Chemistry Exam Nov 2023 - QP Final(2).pdf",
    "memo_path": "data/organized/chemistry/PS11 - Chemistry Exam Nov 2023 - MG.pdf",
    "year": 2023,
    "exam_date": "27 November 2023",
    "exam_period": "november",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 165,
    "examiner": "Mr Ntombela",
    "moderator": "Mr Hilder",
    "duration_stated": "2,5 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set final Chemistry paper (St Benedict's College). Lewis/Couper diagrams, "
        "energy-profile (Q3.7) and Maxwell-Boltzmann (Q3.10) sketches are diagram-based."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (20 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Correct formula for ammonium thiosulphate. A NH3SO3 / B (NH4)2SO4 / C NH3S2O3 / D (NH4)2S2O3",
     False, [], "D", ["(NH4)2S2O3"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Bonding", "Multiple Choice",
     "Which does NOT contain a dative covalent bond? A CO2 / B SO2 / C SO3 / D NH4+",
     False, [], "A", ["CO2"], "Memo gives the correct option only.", False, False),
    ("1.3", 2, "Stoichiometry", "Multiple Choice",
     "One mole of gas at STP... A 22,4 dm3 at 0 C, 1 atm / B 22,4 at 25 C, 101,3 atm / C 24,4 at 0 C, 101,3 atm / D 24,4 at 25 C, 1 atm",
     False, [], "A", ["22,4 dm3 at 0 C, 1 atm"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Intermolecular Forces", "Multiple Choice",
     "Which statement is NOT correct? A strongest IMF in NH3 = H-bond / B in HCl = permanent dipole-dipole / "
     "C in ethanol = permanent dipole-dipole / D in water = H-bond",
     False, [], "C", ["ethanol IMF is H-bond, not dipole-dipole"], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Bonding", "Multiple Choice",
     "Greatest number of lone pairs? A N2 / B O2 / C HCl / D H2",
     False, [], "B", ["O2 has 4 lone pairs"], "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Bonding", "Multiple Choice",
     "High MP in diamond/graphite due to... A strong covalent bonds / B ionic forces / C intermolecular forces / D H-bond",
     False, [], "A", ["strong covalent bonds"], "Memo gives the correct option only.", False, False),
    ("1.7", 2, "Reaction Rates", "Multiple Choice",
     "Maxwell-Boltzmann curve P -> Q after a change. Which change gave Q? A catalyst / B temp up / C Ea up / D [reactants] up",
     True, [], "D", ["increase in concentration"], "Memo gives D; graph is an image.", True, False),
    ("1.8", 2, "Organic Chemistry", "Multiple Choice",
     "Which is an alkane? A ethene / B 2-bromopentane / C 2-methyl-3,4-dichloropentane / D 2,3-dimethyl-4-ethyloctane",
     False, [], "D", ["2,3-dimethyl-4-ethyloctane"], "Memo gives the correct option only.", False, False),
    ("1.9", 2, "Organic Chemistry", "Multiple Choice",
     "Hexan-2-ol dehydration. Which CANNOT be a product? (A/B/C/D alkene structures)",
     True, [], "C", ["one structure cannot be formed"], "Memo gives C; structures are images.", True, False),
    ("1.10", 2, "Organic Chemistry", "Multiple Choice",
     "Which haloalkane CANNOT undergo dehydrohalogenation? A 2-bromobutane / B 2,2-dichloropropane / C trichloromethane / D 1,2-dibromobutane",
     False, [], "C", ["trichloromethane"], "Memo gives the correct option only.", False, False),

    # ---------------- QUESTION 2: CHEMICAL BONDING (30 marks) ----------------
    ("2.1.1", 1, "Intermolecular Forces", "Short Answer",
     "From NaCℓ(s), N2(g), Fe(s), NH3(g), C:diamond(s), Ne(g): substance with induced-dipole (London) forces between atoms.",
     False, [], "Ne", ["Ne (1)"], "One mark.", False, False),
    ("2.1.2", 1, "Intermolecular Forces", "Short Answer",
     "Substance with London forces between its molecules.",
     False, [], "N2", ["N2 (1)"], "One mark.", False, False),
    ("2.1.3", 1, "Bonding", "Short Answer",
     "Substance with a giant covalent network structure.",
     False, [], "C (diamond)", ["C (1)"], "One mark.", False, False),
    ("2.1.4", 1, "Bonding", "Short Answer",
     "Substance that conducts electricity in its liquid phase.",
     False, [], "NaCℓ", ["NaCℓ (1)"], "One mark.", False, False),
    ("2.1.5", 1, "Bonding", "Short Answer",
     "Substance with ionic bonds.",
     False, [], "NaCℓ", ["NaCℓ (1)"], "One mark.", False, False),
    ("2.1.6", 1, "Bonding", "Short Answer",
     "Substance with polar covalent bonds.",
     False, [], "NH3", ["NH3 (1)"], "One mark.", False, False),
    ("2.1.7", 1, "Bonding", "Short Answer",
     "Substance with pure covalent bonds.",
     False, [], "N2", ["N2 (1)"], "One mark.", False, False),
    ("2.2.1", 2, "Bonding", "Definition/Explain",
     "Define electronegativity.",
     False, [], "tendency of an atom to attract a bonding pair of electrons", ["tendency (1)", "attract bonding pair (1)"], "Two marks.", False, False),
    ("2.2.2", 2, "Bonding", "Diagram-based",
     "Draw the Lewis diagram of ethene.",
     True, [], "H2C=CH2 with full octets and shared pairs", ["correct Lewis (2)"], "Two marks; Lewis diagram.", True, False),
    ("2.2.3", 2, "Bonding", "Diagram-based",
     "Circle and label a sigma and a pi bond in the ethene Lewis diagram.",
     True, [], "sigma in C-C single pair; pi in double bond", ["sigma labelled (1)", "pi labelled (1)"], "Two marks; on the diagram.", True, False),
    ("2.2.4", 2, "Bonding", "Definition/Explain",
     "Define a dative covalent bond.",
     False, [], "a lone pair from one atom overlaps the empty orbital of another atom", ["lone pair (1)", "empty orbital (1)"], "Two marks.", False, False),
    ("2.2.5", 3, "Bonding", "Diagram-based",
     "Draw a Couper diagram of carbon monoxide.",
     True, [], "C≡O with arrow from O to C (dative)", ["C and O (1)", "triple bond (1)", "arrow O->C (1)"], "Three marks; Couper diagram.", True, False),
    ("2.2.6", 2, "Bonding", "Short Answer",
     "Indicate polarity of C and O in the CO diagram.",
     True, [], "delta+ on C; delta- on O", ["delta+ C (1)", "delta- O (1)"], "Two marks; on the diagram.", True, False),
    ("2.2.7", 5, "Bonding", "Explanation",
     "With reference to EN, intramolecular forces and shape, determine if CO2 is polar or non-polar.",
     False, [], "non-polar (END=1,0 -> polar bonds; linear -> symmetric -> non-polar)",
     ["END=3,5-2,5=1,0 polar bonds (1)", "symmetry (1)", "linear shape (1)", "non-polar (1)"], "Five marks.", False, False),
    ("2.4", 1, "Intermolecular Forces", "Short Answer",
     "What phase would neon be at -200 C? (graph of noble-gas Bpt vs size)",
     True, [], "liquid", ["liquid (1)"], "One mark; graph is an image.", True, False),
    ("2.5", 4, "Intermolecular Forces", "Explanation",
     "Explain the student's conclusion that noble-gas Bpt rises with atom size (via IMFs).",
     False, [], "all have London; more electrons down group -> stronger temporary dipoles -> stronger London -> higher Bpt",
     ["all London (1)", "more electrons down group (1)", "stronger temp dipoles (1)", "more energy to overcome (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 3: REACTION RATES (elephant toothpaste) (31 marks) ----------------
    ("3.1", 2, "Reaction Rates", "Definition/Explain",
     "Define catalyst.",
     False, [], "substance that increases rate but is unchanged at the end", ["increases rate (1)", "unchanged (1)"], "Two marks.", False, False),
    ("3.2", 3, "Reaction Rates", "Explanation",
     "Explain how the data would be collected under lab conditions (O2 evolved vs time).",
     True, [], "downward displacement of water; gas jar inverted over beehive shelf, O2 collected upwards",
     ["downward displacement (1)", "gas jar inverted (1)", "O2 collected upwards (1)"], "Three marks.", True, False),
    ("3.3", 1, "Reaction Rates", "Short Answer",
     "Which catalyst produces the most foam quickest? (graph of O2 vs time)",
     True, [], "MnO2", ["MnO2 (1)"], "One mark; from the graph.", True, False),
    ("3.4", 2, "Reaction Rates", "Definition/Explain",
     "Define rate of reaction.",
     False, [], "change in amount/concentration per unit time of reactant or product", ["change in conc (1)", "per unit time (1)"], "Two marks.", False, False),
    ("3.5", 3, "Reaction Rates", "Calculation",
     "Average rate for the catalyst in 3.3 over 0-4 ms. (graph: 40x10^-3 mol)",
     True, [], "10 mol.s-1", ["rate = 40e-3 / 4e-3 (1)", "=10 (1)", "units mol.s-1 (1)"], "Three marks; from the graph.", True, False),
    ("3.6", 3, "Energy & Chemical Change", "Explanation",
     "Correct Matthew: 'exothermic because energy is only released' (refer to breaking/forming bonds).",
     False, [], "energy absorbed to break bonds, released when new bonds form (net thermal out)",
     ["energy absorbed breaking bonds (1)", "energy released forming bonds (1)", "net thermal energy (1)"], "Three marks.", False, False),
    ("3.7", 5, "Energy & Chemical Change", "Diagram-based",
     "Complete and label the energy profile; show yeast (dashed) and KI (solid) on the same graph.",
     True, [], "exothermic profile; EA lowered for both catalysts (yeast lower than KI)", ["profile (1)", "dH labelled (1)", "EA labelled (1)", "yeast dashed lower (1)", "KI solid (1)"], "Five marks; on the graph.", True, False),
    ("3.8", 4, "Energy & Chemical Change", "Explanation",
     "How does a catalyst affect the heat of reaction? Explain fully.",
     False, [], "no change to dH; catalyst only lowers EA, provides alternative pathway, does not change product energy",
     ["no change (1)", "lowers EA (1)", "alternative pathway (1)", "product energy unchanged (1)"], "Four marks.", False, False),
    ("3.9", 4, "Reaction Rates", "Explanation",
     "Effect of increased [H2O2] on rate via collision theory (bullet points).",
     False, [], "more particles/volume -> more collisions/s -> more effective collisions/s -> faster rate",
     ["more particles/volume (1)", "more collisions/s (1)", "more effective collisions/s (1)", "faster rate (1)"], "Four marks.", False, False),
    ("3.10", 4, "Reaction Rates", "Diagram-based",
     "Draw Maxwell-Boltzmann curves T1 (original) and T2 (lower temperature).",
     True, [], "T2 shifted left with lower peak (same area)", ["two curves (1)", "T1 (1)", "T2 lower temp (1)", "correct shape (1)"], "Four marks; on the graph.", True, False),

    # ---------------- QUESTION 4: ORGANIC CHEMISTRY (22 marks) ----------------
    ("4.1", 4, "Organic Chemistry", "Short Answer",
     "IUPAC name for compound A (haloalkane structure).",
     True, [], "3-bromo-2,4-dimethylhexane", ["3-bromo (1)", "2,4-dimethyl (1)", "hexane (1)", "correct order (1)"], "Four marks; structure is an image.", True, False),
    ("4.2", 2, "Organic Chemistry", "Short Answer",
     "Draw the condensed structural formula for compound A.",
     True, [], "CH3CH2CH(CH3)CHBrCH(CH3)CH3", ["main chain (1)", "Br and CH3 substituents (1)"], "Two marks; from the structure.", True, False),
    ("4.3", 1, "Organic Chemistry", "Short Answer",
     "Name the homologous series of compound B (alkene).",
     True, [], "alkenes", ["alkenes (1)"], "One mark.", True, False),
    ("4.4", 2, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula for the unbranched CHAIN isomer of compound B.",
     True, [], "straight-chain alkene (e.g. hept-1-ene)", ["correct functional group (1)", "correct carbons/unbranched (1)"], "Two marks; from the structure.", True, False),
    ("4.5", 1, "Organic Chemistry", "Short Answer",
     "Name the functional group present in compound C.",
     True, [], "hydroxyl group", ["hydroxyl (1)"], "One mark.", True, False),
    ("4.6", 2, "Organic Chemistry", "Definition/Explain",
     "State what is meant by positional isomers.",
     False, [], "same molecular formula but different position of the same functional group/substituents",
     ["same mol formula (1)", "different position of FG (1)"], "Two marks.", False, False),
    ("4.7", 2, "Organic Chemistry", "Diagram-based",
     "Draw a structural formula for a POSITIONAL isomer of compound C.",
     True, [], "same alcohol, -OH at different carbon", ["correct FG (1)", "correct carbons (1)"], "Two marks; from the structure.", True, False),
    ("4.8", 4, "Intermolecular Forces", "Explanation",
     "Compound C more viscous than B. Account via predominant IMFs.",
     False, [], "B has London only; C has H-bonding (stronger) -> harder to flow -> higher viscosity",
     ["B London only (1)", "C H-bonding (1)", "H-bond stronger (1)", "harder to flow (1)"], "Four marks.", False, False),
    ("4.9", 4, "Organic Chemistry", "Calculation",
     "Balanced equation (molecular formulae) for complete combustion of compound B (C7H12).",
     False, [], "C7H12 + 10O2 -> 7CO2 + 6H2O", ["C7H12 (1)", "10O2 (1)", "7CO2 (1)", "6H2O (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 5: ORGANIC CHEMISTRY (flow chart) (19 marks) ----------------
    ("5.1", 2, "Organic Chemistry", "Definition/Explain",
     "Define hydrocarbon.",
     False, [], "compound/molecule containing only carbon and hydrogen atoms", ["only C and H (2)"], "Two marks.", False, False),
    ("5.2", 2, "Organic Chemistry", "Short Answer",
     "IUPAC name of compound Y (alkene).",
     True, [], "pent-1-ene", ["pent (1)", "1-ene (1)"], "Two marks; from the flow chart.", True, False),
    ("5.3", 1, "Organic Chemistry", "Short Answer",
     "Classify compound Y as saturated or unsaturated.",
     True, [], "unsaturated", ["unsaturated (1)"], "One mark.", True, False),
    ("5.4", 2, "Organic Chemistry", "Short Answer",
     "IUPAC name for hydrocarbon W.",
     True, [], "pentane", ["pentane (2)"], "Two marks; from the flow chart.", True, False),
    ("5.5.1", 2, "Organic Chemistry", "Short Answer",
     "General TYPE of reaction 1.",
     True, [], "substitution", ["substitution (2)"], "Two marks; from the flow chart.", True, False),
    ("5.5.2", 2, "Organic Chemistry", "Short Answer",
     "General TYPE of reaction 2.",
     True, [], "elimination", ["elimination (2)"], "Two marks; from the flow chart.", True, False),
    ("5.5.3", 2, "Organic Chemistry", "Short Answer",
     "General TYPE of reaction 5.",
     True, [], "addition", ["addition (2)"], "Two marks; from the flow chart.", True, False),
    ("5.6", 1, "Organic Chemistry", "Short Answer",
     "Specific type of addition reaction represented by reaction 3.",
     True, [], "hydrohalogenation", ["hydrohalogenation (1)"], "One mark; from the flow chart.", True, False),
    ("5.7", 2, "Organic Chemistry", "Short Answer",
     "IUPAC name of compound Z (from reactions 5,6,7).",
     True, [], "pentan-1-ol", ["pentan (1)", "1-ol (1)"], "Two marks; from the flow chart.", True, False),
    ("5.8", 2, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula of pentyl ethanoate.",
     False, [], "CH3COOCH2CH2CH2CH2CH3", ["ethanoate part (1)", "pentyl part (1)"], "Two marks.", False, False),
    ("5.9", 1, "Organic Chemistry", "Short Answer",
     "Reaction number that occurs with concentrated alcoholic KOH (elimination).",
     True, [], "2", ["2 (1)"], "One mark; from the flow chart.", True, False),

    # ---------------- QUESTION 6: STOICHIOMETRY (antacid) (15 marks) ----------------
    ("6.1", 1, "Stoichiometry", "Short Answer",
     "3NaHCO3 + H3C6H5O7 -> Na3C6H5O7 + 3CO2 + 3H2O. Formula of the fizz substance?",
     False, [], "CO2", ["CO2 (1)"], "One mark.", False, False),
    ("6.2", 1, "Stoichiometry", "Definition/Explain",
     "Describe 1 mole of a substance.",
     False, [], "amount of substance with the same number of particles (as 12 g C-12 / Avogadro)", ["same number of particles (1)"], "One mark.", False, False),
    ("6.3", 3, "Stoichiometry", "Calculation",
     "Antacid has 1,8 g citric acid + 3,36 g NaHCO3. Moles of NaHCO3? (M=84)",
     False, ["n=m/M"], "0,04 mol", ["n=3,36/84 (1)", "=0,04 (1)"], "Three marks.", False, False),
    ("6.4", 4, "Stoichiometry", "Calculation",
     "Limiting reagent? (citric acid M=192)",
     False, ["n=m/M"], "citric acid is limiting",
     ["n(acid)=1,8/192=0,01 (1)", "3:1 -> need 0,03 NaHCO3 (1)", "0,04 available > 0,03 (1)", "citric acid limiting (1)"], "Four marks.", False, False),
    ("6.5", 3, "Stoichiometry", "Calculation",
     "Mass of the reactant in excess.",
     False, ["m=nM"], "0,84 g",
     ["excess = 0,04-0,03 = 0,01 mol (1)", "m=0,01x84 (1)", "=0,84 g (1)"], "Three marks.", False, False),
    ("6.6", 3, "Stoichiometry", "Calculation",
     "Mass decrease of beaker contents on completion (CO2 escapes).",
     False, ["m=nM"], "1,32 g",
     ["m=nM (1)", "=0,03x44 (1)", "=1,32 g (1)"], "Three marks.", False, False),

    # ---------------- QUESTION 7: STOICHIOMETRY (aspirin) (19 marks) ----------------
    ("7.1.1", 2, "Stoichiometry", "Definition/Explain",
     "Define molar mass.",
     False, [], "mass (in grams) of one mole of a substance", ["mass in grams (1)", "one mole (1)"], "Two marks.", False, False),
    ("7.1.2", 4, "Stoichiometry", "Calculation",
     "Molar mass of salicylic acid (C7H6O3).",
     False, [], "138 g.mol-1", ["7x12 (1)", "6H (1)", "3x16 (1)", "=138 (1)"], "Four marks.", False, False),
    ("7.1.3", 5, "Stoichiometry", "Calculation",
     "Mass of aspirin expected from 3,86 g salicylic acid (aspirin M=180; 1:1).",
     False, ["n=m/M", "m=nM"], "5,04 g",
     ["n=3,86/138=0,028 (1)", "1:1 ratio (1)", "m=0,028x180 (1)", "=5,04 g (1)"], "Five marks.", False, False),
    ("7.1.4", 3, "Stoichiometry", "Calculation",
     "Percentage yield if only 4,65 g aspirin produced.",
     False, ["% yield = actual/theoretical x 100"], "92,26%",
     ["% = 4,65/5,03 (1)", "x100 (1)", "=92,26% (1)"], "Three marks.", False, False),
    ("7.2", 5, "Stoichiometry", "Calculation",
     "Aspirin tablet = 300 mg aspirin. Number of hydrogen atoms in the tablet (aspirin C9H8O4).",
     False, ["N=n.Na"], "8,03 x 10^21",
     ["n=0,3/180=0,00167 (1)", "1 mol aspirin = 8 mol H (1)", "0,00167x8=0,0133 mol H (1)", "x6,02e23 = 8,03e21 (1)"], "Five marks.", False, False),

    # ---------------- QUESTION 8: SOLUTIONS (9 marks) ----------------
    ("8.1", 1, "Stoichiometry", "Definition/Explain",
     "Define solvent.",
     False, [], "substance in which another is dissolved, forming a solution", ["dissolving substance (1)"], "One mark.", False, False),
    ("8.2", 1, "Stoichiometry", "Short Answer",
     "Identify the solvent used.",
     False, [], "water (H2O)", ["water (1)"], "One mark.", False, False),
    ("8.3", 3, "Bonding", "Short Answer",
     "Balanced dissociation of ammonium carbonate.",
     False, [], "(NH4)2CO3 -> 2NH4+ + CO3 2-", ["2NH4+ (1)", "CO3 2- (1)", "balanced (1)"], "Three marks.", False, False),
    ("8.4", 4, "Stoichiometry", "Calculation",
     "Solution A (0,2 M NH4OH, 0,25 dm3) + B (0,3 M (NH4)2CO3, 0,5 dm3). New [NH4+]?",
     False, ["n=cV", "c=n/V"], "0,47 mol.dm-3",
     ["n(NH4OH)=0,05 (1)", "n((NH4)2CO3)=0,15x2=0,3 (1)", "c=(0,05+0,3)/(0,25+0,5) (1)", "=0,47 (1)"], "Four marks.", False, False),
]
