"""Pass 1 evidence table — Grade 11 Chemistry Examination, 10 November 2025.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/G11 - Chemistry - Examination - QPV2 - 2025.pdf (135 marks, Mr Ntombela)
Memo:   data/organized/chemistry/G11 - Chemistry - Examination - MG2 - 2025.pdf  (135 marks, Mr Ntombela)

NOTE: the memo's Q1 numbering is off-by-one versus the question paper for the CO2 /
electronegativity block (memo 1.3 = Lewis CO2, 1.4 = EN def, ...; QP 1.4 = Lewis CO2,
1.5 = EN def, ...). The evidence uses the QP's numbering (1.4-1.8) so the marks sum to
the paper's printed TOTAL of 135. Compounds X and Y in Q5 are given as images.

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2025-NOV",
    "paper_path": "data/organized/chemistry/G11 - Chemistry - Examination - QPV2 - 2025.pdf",
    "memo_path": "data/organized/chemistry/G11 - Chemistry - Examination - MG2 - 2025.pdf",
    "year": 2025,
    "exam_date": "10 November 2025",
    "exam_period": "november",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 135,
    "examiner": "Mr Ntombela",
    "moderator": "Mr Hilder",
    "duration_stated": "2 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set final Chemistry paper (St Benedict's College). Compounds X and Y in Q5 are "
        "images; Maxwell-Boltzmann (Q2.8) and graph (Q6.3) sketches are diagram-based."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: BONDING / IMFs (27 marks) ----------------
    ("1.1.1", 1, "Intermolecular Forces", "Short Answer",
     "From NH3(A), methane(B), Cu(C), NaCl(D), I2(E), chloromethane(F): a non-polar molecule?",
     False, [], "B and E (methane, iodine)", ["B (1)", "E (1)"], "One mark.", False, False),
    ("1.1.2", 1, "Bonding", "Short Answer",
     "A non-polar molecule with polar covalent bonds?",
     False, [], "B (methane)", ["B (1)"], "One mark.", False, False),
    ("1.1.3", 1, "Bonding", "Short Answer",
     "A polar molecule with polar covalent bonds?",
     False, [], "A and F (NH3, chloromethane)", ["A (1)", "F (1)"], "One mark.", False, False),
    ("1.1.4", 1, "Intermolecular Forces", "Short Answer",
     "Has hydrogen-bond forces?",
     False, [], "A (NH3)", ["A (1)"], "One mark.", False, False),
    ("1.1.5", 1, "Bonding", "Short Answer",
     "Forms an ionic crystal lattice in solid form?",
     False, [], "D (NaCl)", ["D (1)"], "One mark.", False, False),
    ("1.1.6", 1, "Bonding", "Short Answer",
     "Exists as a solid in a metallic crystal lattice?",
     False, [], "C (Cu)", ["C (1)"], "One mark.", False, False),
    ("1.1.7", 1, "Intermolecular Forces", "Short Answer",
     "Solid at room temperature and soluble in CCl4?",
     False, [], "E (I2)", ["E (1)"], "One mark.", False, False),
    ("1.2.1", 2, "Bonding", "Short Answer",
     "Oxidation number of chromium in Cr2O7 2-.",
     False, [], "+6", ["+6 (2)"], "Two marks.", False, False),
    ("1.2.2", 2, "Bonding", "Short Answer",
     "Type(s) of bonds in potassium dichromate, K2Cr2O7.",
     False, [], "polar covalent bonds and ionic bonds", ["polar covalent (1)", "ionic (1)"], "Two marks.", False, False),
    ("1.2.3", 2, "Bonding", "Explanation",
     "Explain 1.2.2 with reference to subatomic particles.",
     False, [], "electrons shared between Cr and O; electrons transferred from K to Cr2O7",
     ["shared Cr-O (1)", "transferred K->Cr2O7 (1)"], "Two marks.", False, False),
    ("1.4", 2, "Bonding", "Diagram-based",
     "Draw the Lewis diagram of CO2; state mistakes in the AI image (single bonds drawn).",
     True, [], "O=C=O (double bonds); error = single bonds in the AI image",
     ["error: single bonds (1)", "correct sharing (1)"], "Two marks; Lewis diagram.", True, False),
    ("1.5", 1, "Bonding", "Definition/Explain",
     "Define electronegativity.",
     False, [], "tendency of an atom to attract a bonding pair of electrons", ["tendency (1)"], "One mark.", False, False),
    ("1.6", 2, "Bonding", "Calculation",
     "Bond polarity for the C-O bond (EN C 2,5, O 3,5).",
     False, [], "END = 3,5 - 2,5 = 1,0 -> polar covalent", ["END=1,0 (1)", "polar covalent (1)"], "Two marks.", False, False),
    ("1.7", 5, "Intermolecular Forces", "Explanation",
     "IMF between CO2 molecules and how they arise.",
     False, [], "London forces; random e- movement sets up temp dipoles, inducing dipoles in neighbours that attract",
     ["London forces (1)", "random e- movement (1)", "temp dipole (1)", "induced dipole (1)", "attract (1)"], "Five marks.", False, False),
    ("1.8", 4, "Intermolecular Forces", "Explanation",
     "Explain MP difference: CO2 (-78,9 C) vs CH4 (-182 C).",
     False, [], "both non-polar; CO2 has higher electron density -> stronger London -> more energy to overcome",
     ["both non-polar (1)", "CO2 higher e-density (1)", "stronger London (1)", "more energy (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 2: REACTION RATES (Al + NaOH) (23 marks) ----------------
    ("2.1", 1, "Reaction Rates", "Definition/Explain",
     "Define reaction rate for a chemical reaction.",
     False, [], "change in concentration per unit time of reactant or product", ["per unit time (1)"], "One mark.", False, False),
    ("2.2", 2, "Reaction Rates", "Short Answer",
     "Balance: Al + NaOH + H2O -> 2Na[Al(OH)4] + H2 (dH<0).",
     False, [], "2Al + 2NaOH + 6H2O -> 2Na[Al(OH)4] + 3H2", ["2Al,2NaOH,6H2O (1)", "3H2 (1)"], "Two marks.", False, False),
    ("2.3", 1, "Energy & Chemical Change", "Short Answer",
     "EXOTHERMIC or ENDOTHERMIC? (circle)",
     False, [], "EXOTHERMIC", ["EXOTHERMIC (1)"], "One mark.", False, False),
    ("2.4", 1, "Energy & Chemical Change", "Short Answer",
     "Explain 2.3.",
     False, [], "heat of reaction is less than zero (dH<0)", ["dH<0 (1)"], "One mark.", False, False),
    ("2.5", 2, "Reaction Rates", "Explanation",
     "Explain how to use the gas syringe apparatus to measure the rate.",
     False, [], "measure the volume/amount of gas collected in the syringe at set time intervals",
     ["measure gas volume (1)", "every few seconds (1)"], "Two marks.", False, False),
    ("2.6", 2, "Reaction Rates", "Explanation",
     "Why a concentration-vs-time graph for all species except water would be incorrect?",
     False, [], "Al is a solid and water a liquid; concentrations of solids/liquids do not change",
     ["Al solid / water liquid (1)", "conc cannot change (1)"], "Two marks.", False, False),
    ("2.7", 2, "Reaction Rates", "Calculation",
     "Rate of reaction for aluminium (0,5 mol in 70 s).",
     False, ["rate = Δn/Δt"], "7,14 x 10^-3 mol.s-1",
     ["0,5/70 (1)", "=7,14e-3 (1)"], "Two marks.", False, False),
    ("2.8", 4, "Reaction Rates", "Diagram-based",
     "Draw labelled Maxwell-Boltzmann curves T1 (original) and T2 (decreased temperature).",
     True, [], "T2 shifted left/lower peak; same area; EA labelled",
     ["axes (1)", "correct shapes (1)", "T1+T2 (1)", "EA labelled (1)"], "Four marks; on the graph.", True, False),
    ("2.9", 2, "Reaction Rates", "Definition/Explain",
     "How does a catalyst affect the rate?",
     False, [], "increases rate by providing an alternative reaction pathway (lower Ea)",
     ["increases rate (1)", "alternative path (1)"], "Two marks.", False, False),
    ("2.10", 2, "Reaction Rates", "Diagram-based",
     "Effect of a catalyst on the graph on the previous page.",
     False, [], "the activation-energy line shifts to the right (lower Ea)",
     ["Ea shifts right / lower (2)"], "Two marks.", False, False),
    ("2.11", 4, "Reaction Rates", "Explanation",
     "Use collision theory to explain whether a change in surface area affects the rate.",
     False, [], "more surface area exposes more solid particles -> more collisions/s -> more effective collisions/s -> faster rate",
     ["more surface area (1)", "more collisions/s (1)", "more effective collisions/s (1)", "rate increases (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 3: STOICHIOMETRY / SOLUTIONS (24 marks) ----------------
    ("3.1.1", 6, "Stoichiometry", "Calculation",
     "MgCl2 + 2AgNO3 -> 2AgCl + Mg(NO3)2. 55 cm3 0,25 M MgCl2 + 70 cm3 0,15 M AgNO3. Prove AgNO3 limiting.",
     False, ["n=cV"], "AgNO3 is limiting",
     ["n(MgCl2)=0,25x0,055=0,01375 (1)", "n(AgNO3)=0,15x0,070=0,0105 (1)", "ratio 1:2 (1)", "need 5,25e-3 MgCl2 (1)", "0,01375 available -> enough -> AgNO3 limiting (1)"], "Six marks.", False, False),
    ("3.1.2", 3, "Stoichiometry", "Calculation",
     "Mass of AgCl that can form.",
     False, ["m=nM"], "1,51 g",
     ["ratio 2:2 (1)", "n(AgCl)=0,0105 (1)", "m=0,0105x143,5=1,51 g (1)"], "Three marks.", False, False),
    ("3.1.3", 2, "Stoichiometry", "Calculation",
     "Percentage yield if 1,49 g AgCl recovered.",
     False, ["% yield = actual/theoretical x 100"], "98,98%",
     ["1,49/1,51 (1)", "x100=98,98% (1)"], "Two marks.", False, False),
    ("3.2.1", 1, "Stoichiometry", "Short Answer",
     "Why are the two given solutions standard solutions?",
     False, [], "they have known concentrations", ["known concentrations (1)"], "One mark.", False, False),
    ("3.2.2", 2, "Stoichiometry", "Definition/Explain",
     "Define solvent.",
     False, [], "substance in which another is dissolved, forming a solution", ["dissolving substance (1)", "forms solution (1)"], "Two marks.", False, False),
    ("3.2.3", 1, "Stoichiometry", "Short Answer",
     "Identify the solvent used in the two solutions.",
     False, [], "water", ["water (1)"], "One mark.", False, False),
    ("3.2.4", 4, "Bonding", "Short Answer",
     "Balanced dissociation of ammonium carbonate (include phases).",
     False, [], "(NH4)2CO3(s) -> 2NH4+(aq) + CO3 2-(aq)", ["(NH4)2CO3(s) (1)", "2NH4+ (1)", "CO3 2- (1)", "phases (1)"], "Four marks.", False, False),
    ("3.2.5", 5, "Stoichiometry", "Calculation",
     "Solution A (0,2 M NH4OH, 0,25 dm3) + B (0,3 M (NH4)2CO3, 0,5 dm3). New [NH4+]?",
     False, ["n=cV", "c=n/V"], "0,47 mol.dm-3",
     ["n(NH4OH)=0,05 (1)", "n((NH4)2CO3)=0,15x2=0,3 (1)", "c=(0,05+0,3)/(0,25+0,5) (1)", "=0,47 (1)"], "Five marks.", False, False),

    # ---------------- QUESTION 4: REDOX / ELECTROLYSIS (23 marks) ----------------
    ("4.1.1", 4, "Bonding", "Short Answer",
     "Zn in CuSO4. Write oxidation and reduction half-reactions.",
     False, [], "ox: Zn -> Zn2+ + 2e-; red: Cu2+ + 2e- -> Cu",
     ["Zn -> Zn2+ + 2e- (2)", "Cu2+ + 2e- -> Cu (2)"], "Four marks.", False, False),
    ("4.1.2", 2, "Bonding", "Explanation",
     "Use standard reduction potentials: why spontaneous, and why H2 does not react?",
     False, [], "Zn has lower reduction potential (better reducing agent) than Cu, so reduces Cu2+; H2 is not a better reducing agent",
     ["Zn lower reduction potential (1)", "spontaneously reduces Cu2+ (1)"], "Two marks.", False, False),
    ("4.2.1", 1, "Bonding", "Definition/Explain",
     "Define reducing agent.",
     False, [], "a substance that donates electrons (is oxidised)", ["donates electrons (1)"], "One mark.", False, False),
    ("4.2.2", 2, "Bonding", "Explanation",
     "Why is the positive electrode made of silver (Ag electroplating)?",
     False, [], "the silver electrode provides a continuous source of Ag+ ions for plating",
     ["continuous Ag+ source (2)"], "Two marks.", False, False),
    ("4.2.3", 1, "Bonding", "Short Answer",
     "Direction of silver-ion flow in the solution (anode -> cathode / to the key).",
     False, [], "Ag+ flows from the silver anode towards the key (cathode)", ["anode to cathode/key (1)"], "One mark.", False, False),
    ("4.2.4", 2, "Bonding", "Short Answer",
     "Half-reaction at the cathode (Ag plating).",
     False, [], "Ag+ + e- -> Ag(s)", ["Ag+ + e- (1)", "-> Ag(s) (1)"], "Two marks.", False, False),
    ("4.2.5", 2, "Bonding", "Explanation",
     "Is the key the reducing agent during electroplating? (Give a reason.)",
     False, [], "no - the key is the cathode (reduction occurs there); the power source supplies the electrons",
     ["no (1)", "key is cathode / source supplies e- (1)"], "Two marks.", False, False),
    ("4.3.1", 1, "Bonding", "Short Answer",
     "Concentrated CuBr2 electrolysed (graphite). Which electrode is the cathode? (P or Q)",
     True, [], "P", ["P (1)"], "One mark; from the diagram.", True, False),
    ("4.3.2", 2, "Bonding", "Short Answer",
     "Half-reaction at the anode.",
     False, [], "2Br- -> Br2 + 2e-", ["2Br- (1)", "-> Br2 + 2e- (1)"], "Two marks.", False, False),
    ("4.3.3", 1, "Bonding", "Definition/Explain",
     "Define oxidation number.",
     False, [], "the charge an atom would have if electrons were transferred completely (or loss/gain of electrons)",
     ["charge/electron bookkeeping (1)"], "One mark.", False, False),
    ("4.3.4", 3, "Bonding", "Explanation",
     "Use oxidation number: which substance is oxidised/reduced?",
     False, [], "Cu2+ (+2->0) is reduced; Br- (-1->0) is oxidised",
     ["Cu2+ reduced (1)", "Br- oxidised (1)", "correct ON changes (1)"], "Three marks.", False, False),
    ("4.3.5", 2, "Bonding", "Short Answer",
     "Balanced net ionic equation for the electrolysis.",
     False, [], "Cu2+ + 2Br- -> Cu + Br2", ["Cu2+ + 2Br- (1)", "-> Cu + Br2 (1)"], "Two marks.", False, False),

    # ---------------- QUESTION 5: ORGANIC CHEMISTRY (19 marks) ----------------
    ("5.1", 2, "Organic Chemistry", "Definition/Explain",
     "Define homologous series.",
     False, [], "similar compounds with same functional group and general formula, differing by CH2",
     ["same FG + general formula (1)", "differ by CH2 (1)"], "Two marks.", False, False),
    ("5.2", 2, "Organic Chemistry", "Short Answer",
     "General formula for the homologous series of compound X (structure given).",
     True, [], "CnH2n+2 (alkane)", ["CnH2n+2 (2)"], "Two marks; X is an image.", True, False),
    ("5.3", 2, "Organic Chemistry", "Short Answer",
     "Classify compound X as saturated or unsaturated.",
     True, [], "saturated", ["saturated (2)"], "Two marks; X is an image.", True, False),
    ("5.4", 2, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula for the POSITIONAL ISOMER of compound X.",
     True, [], "same carbon skeleton, substituent at a different carbon",
     ["correct structure (2)"], "Two marks; X is an image.", True, False),
    ("5.5", 2, "Organic Chemistry", "Diagram-based",
     "Condensed formula for a CHAIN isomer of compound X.",
     True, [], "chain isomer (different carbon skeleton), e.g. CH3CH2C(CH3)(CH2CH3)CH2CH3",
     ["correct chain isomer (2)"], "Two marks; X is an image (memo condensed formula has a typo).", True, False),
    ("5.6", 1, "Organic Chemistry", "Short Answer",
     "Describe the functional group of compound Y (structure given).",
     True, [], "carbon-carbon double bond (C=C)", ["C=C double bond (1)"], "One mark; Y is an image.", True, False),
    ("5.7", 3, "Organic Chemistry", "Short Answer",
     "IUPAC name for compound Y.",
     True, [], "3-ethylhexa-1,3-diene", ["3-ethyl (1)", "hexa (1)", "1,3-diene (1)"], "Three marks; Y is an image.", True, False),
    ("5.8", 1, "Organic Chemistry", "Short Answer",
     "Which compound (X or Y) has the higher boiling point?",
     True, [], "Y", ["Y (1)"], "One mark.", True, False),
    ("5.9", 4, "Intermolecular Forces", "Explanation",
     "Explain 5.8.",
     False, [], "both non-polar (London only); Y is more linear/less branched -> larger surface area -> stronger dispersion -> higher Bpt", 
     ["both London (1)", "Y more linear/less branched (1)", "larger surface area (1)", "stronger dispersion -> higher Bpt (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 6: ORGANIC / INTERMOLECULAR (19 marks) ----------------
    ("6.1", 2, "Intermolecular Forces", "Short Answer",
     "Predominant IMF in CH3F.",
     False, [], "dipole-dipole interactions", ["dipole-dipole (2)"], "Two marks.", False, False),
    ("6.2", 1, "Intermolecular Forces", "Short Answer",
     "Is fluorobutane a GAS or LIQUID at 25 C (BP 33 C)?",
     False, [], "liquid", ["liquid (1)"], "One mark.", False, False),
    ("6.3", 5, "Intermolecular Forces", "Diagram-based",
     "Plot boiling point vs molecular mass for CH3F..C5H11F; line of best fit.",
     True, [], "straight line through the four points (rising)",
     ["axes (1)", "scale (1)", "two points (1)", "two points (1)", "LOBF (1)"], "Five marks; on the graph.", True, False),
    ("6.4", 2, "Intermolecular Forces", "Data/Graph Interpretation",
     "Use the graph to find the boiling point of C3H7F (mol mass 48).",
     True, [], "-4 ± 2 C", ["-4 ± 2 C (2)"], "Two marks; from the graph.", True, False),
    ("6.5.1", 1, "Scientific Skills", "Short Answer",
     "Can this graph accurately give chloromethane's BP? YES/NO.",
     False, [], "NO", ["NO (1)"], "One mark.", False, False),
    ("6.5.2", 2, "Scientific Skills", "Explanation",
     "Explain 6.5.1.",
     False, [], "the graph has only fluoroalkane data, not chloroalkanes (different haloalkane)",
     ["only fluoroalkanes (1)", "different haloalkane (1)"], "Two marks.", False, False),
    ("6.6.1", 2, "Organic Chemistry", "Definition/Explain",
     "Define structural isomers.",
     False, [], "compounds with the same molecular formula but different structural formulae",
     ["same molecular formula (1)", "different structural (1)"], "Two marks.", False, False),
    ("6.6.2", 3, "Organic Chemistry", "Diagram-based",
     "Draw TWO structural isomers of C3H7F.",
     True, [], "two distinct C3H7F structures (e.g. 1-fluoropropane and 2-fluoropropane)",
     ["two isomers (1)", "isomer 1 (1)", "isomer 2 (1)"], "Three marks; diagram.", True, False),
    ("6.6.3", 1, "Organic Chemistry", "Short Answer",
     "Type of structural isomers drawn in 6.6.2.",
     True, [], "positional isomers", ["positional isomers (1)"], "One mark.", True, False),
]
