"""Pass 1 evidence table — Grade 11 Physical Sciences Paper 2 (Chemistry), 23 November 2020.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/PS11 Chemistry Nov 2020 Exam QP.pdf   (200 marks, Mr du Toit)
Memo:   data/organized/chemistry/PS11 Chemistry Nov 2020 Exam MG.pdf   (200 marks, Mr du Toit)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)

NOTE: Grade 11 chemistry papers assess Organic Chemistry (Q7-Q9 here). The
TWO_PASS_PROMPTS chemistry topic list omits it, so it is added as a documented
topic extension (recorded in knowledge/chemistry/PASS2_REPORT.md).
"""

PAPER = {
    "paper_key": "CHE-2020-NOV",
    "paper_path": "data/organized/chemistry/PS11 Chemistry Nov 2020 Exam QP.pdf",
    "memo_path": "data/organized/chemistry/PS11 Chemistry Nov 2020 Exam MG.pdf",
    "year": 2020,
    "exam_date": "23 November 2020",
    "exam_period": "nov",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 200,
    "examiner": "Mr du Toit",
    "moderator": "Mr McCoy",
    "duration_stated": "3 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set November Paper 2. Contains organic-chemistry questions (Q7-Q9) and "
        "energy-profile diagram sub-parts (Q4.2.1/2, Q4.5; Q5.8)."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (20 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Chemical formula for aluminium hydrogen sulphate. A Al(HSO4)3 / B Al3H2SO4 / "
     "C Al2(HSO4)3 / D Al2H2(SO4)3",
     False, [], "A", ["Al2(HSO4)3"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Bonding", "Multiple Choice",
     "Sequence of Group 18 elements showing gradual DECREASE in boiling points. "
     "A Ar,Kr,Ne,Xe / B Ne,Ar,Kr,Xe / C Xe,Kr,Ar,Ne / D Kr,Xe,Ar,Ne",
     False, [], "C", ["Xe,Kr,Ar,Ne (decreasing Bpt)"], "Memo gives the correct option only.", False, False),
    ("1.3", 2, "Reaction Rates", "Multiple Choice",
     "Mg added to HCl under various conditions (ribbon/powder, concentration, temperature). "
     "In which experiments would Mg react in the SHORTEST time? A I&II / B III&IV / C III&V / D II&IV",
     False, [], "B", ["III (powder, 70C) and IV (0,5 M, powder) fastest"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Reaction Rates", "Multiple Choice",
     "Maxwell-Boltzmann curve at room temperature. Which curve applies at a LOWER temperature? (graph A/B/C/D)",
     True, [], "C", ["lower T -> shifted left/down"], "Memo gives the correct option only; graph is an image.", True, False),
    ("1.5", 2, "Stoichiometry", "Multiple Choice",
     "Which represents one mole? A 22,4 g liquid water / B 22,4 dm3 liquid water / "
     "C 18 g liquid water / D 18 dm3 liquid water",
     False, [], "C", ["18 g water = 1 mol"], "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Stoichiometry", "Multiple Choice",
     "How many atoms in 2 mol hydrated oxalic acid (COOH)2.2H2O? A 1,20e24 / B 1,69e25 / "
     "C 3,37e25 / D 5,78e25",
     False, [], "B", ["2 mol x 12 atoms/molecule x 6,02e23"], "Memo gives the correct option only.", False, False),
    ("1.7", 2, "Organic Chemistry", "Multiple Choice",
     "Which is an alkane? A ethene / B 2-bromopentane / C 2-methyl-3,4-dichloropentane / D 2,3-dimethyl-4-ethyloctane",
     False, [], "D", ["only D is saturated (all single bonds)"], "Memo gives the correct option only.", False, False),
    ("1.8", 2, "Organic Chemistry", "Multiple Choice",
     "Hexan-2-ol dehydration with conc H2SO4. Which CANNOT be a product? (structures A/B/C/D)",
     True, [], "C", ["C not an alkene from this dehydration"], "Memo gives the correct option only; structures are images.", True, False),
    ("1.9", 2, "Organic Chemistry", "Multiple Choice",
     "Which haloalkane CANNOT undergo dehydrohalogenation? A 2-bromobutane / B 2,2-dichloropropane / "
     "C trichloromethane / D 1,2-dibromobutane",
     False, [], "C", ["trichloromethane has no beta-H to eliminate"], "Memo gives the correct option only.", False, False),
    ("1.10", 2, "Organic Chemistry", "Multiple Choice",
     "2-methylbutane and pentane illustrate which isomerism? A chain / B positional / C functional group / D stereoisomerism",
     False, [], "A", ["chain isomerism"], "Memo gives the correct option only.", False, False),

    # ---------------- QUESTION 2: BONDING / INTERMOLECULAR FORCES (21 marks) ----------------
    ("2.1.1", 2, "Intermolecular Forces", "Multiple Choice",
     "Given molecules A K2SO4, B KI, C SiO2, D Mg, E NH3, F H2O, G HCOOCH3: which exhibit "
     "hydrogen bonding between molecules? (multiple correct)",
     False, [], "E, F", ["E (NH3)", "F (H2O)"], "Multiple-answer; -1 per error.", False, False),
    ("2.1.2", 2, "Bonding", "Multiple Choice",
     "Which conduct electricity in the molten state? (multiple correct)",
     False, [], "A, B, D", ["A K2SO4", "B KI", "D Mg"], "Multiple-answer; -1 per error.", False, False),
    ("2.1.3", 2, "Bonding", "Multiple Choice",
     "Which are polar molecules? (multiple correct)",
     False, [], "E, F, G", ["E NH3", "F H2O", "G HCOOCH3"], "Multiple-answer; -1 per error.", False, False),
    ("2.1.4", 2, "Bonding", "Multiple Choice",
     "Which consists of positive kernels and a sea of delocalised electrons? (multiple correct)",
     False, [], "D", ["D Mg (metallic bonding)"], "Multiple-answer; -1 per error.", False, False),
    ("2.1.5", 2, "Bonding", "Multiple Choice",
     "Which is a giant covalent structure with a high melting point? (multiple correct)",
     False, [], "C", ["C SiO2"], "Multiple-answer; -1 per error.", False, False),
    ("2.2.1", 2, "Bonding", "Definition/Explain",
     "Diagram of two HCl molecules in liquid phase (X = intramolecular, Y = intermolecular). "
     "Define intramolecular bond.",
     False, [], "a bond between atoms within molecules", ["between atoms (1)", "within molecules (1)"], "Two-mark definition.", False, False),
    ("2.2.2", 2, "Bonding", "Short Answer",
     "Name the specific type of intramolecular bond represented by X in the diagram.",
     True, [], "polar covalent bond", ["polar covalent (2)"], "Two marks; diagram shows HCl.", True, False),
    ("2.2.3", 3, "Bonding", "Explanation",
     "Explain 2.2.2 by referring to electronegativity.",
     True, [], "Cl more electronegative than H (END>0); Cl attracts the bonding pair more",
     ["electronegativity difference Cl>H (1)", "Cl attracts bonding pair (1)", "comparison (1)"], "Three marks.", True, False),
    ("2.2.4", 2, "Intermolecular Forces", "Definition/Explain",
     "Define intermolecular force.",
     False, [], "weak force of attraction between molecules, ions or noble-gas atoms",
     ["weak attraction (1)", "between molecules/ions/atoms (1)"], "Two marks.", False, False),
    ("2.2.5", 1, "Intermolecular Forces", "Short Answer",
     "Name the specific type of intermolecular force represented by Y in the diagram.",
     True, [], "dipole-dipole force", ["dipole-dipole (1)"], "One mark.", True, False),
    ("2.2.6", 1, "Bonding", "Short Answer",
     "What is the partial charge (d+ or d-) on the hydrogen atom in the HCl molecule?",
     True, [], "d+", ["d+ (1)"], "One mark; H is delta-positive in HCl.", True, False),

    # ---------------- QUESTION 3: REDOX / IONIC LATTICE (20 marks) ----------------
    ("3.1", 2, "Bonding", "Definition/Explain",
     "Sodium fluoride from oxidation/reduction half reactions. Define oxidation.",
     False, [], "loss of electrons", ["loss of electrons (2)"], "Two marks (AON).", False, False),
    ("3.2", 2, "Bonding", "Short Answer",
     "Write the oxidation half reaction of the sodium atom.",
     False, [], "Na -> Na+ + e-", ["Na (1)", "Na+ + e- (1)"], "Two marks.", False, False),
    ("3.3", 2, "Bonding", "Definition/Explain",
     "Define oxidising agent.",
     False, [], "a substance that accepts electrons", ["accepts electrons (2)"], "Two marks (AON).", False, False),
    ("3.4", 1, "Bonding", "Short Answer",
     "Which atom is the oxidising agent? (SODIUM or FLUORINE)",
     False, [], "FLUORINE", ["fluorine (1)"], "One mark.", False, False),
    ("3.5.1", 3, "Bonding", "Explanation",
     "Under which conditions can sodium fluoride conduct electricity? Explain.",
     True, [], "aqueous or molten state — ions are free to move",
     ["aqueous or molten (1)", "ions free to move (1)"], "Three marks; lattice diagram is an image.", True, False),
    ("3.5.2", 1, "Bonding", "Short Answer",
     "Provide a label for Z in the crystal-lattice diagram.",
     True, [], "ionic bond (or electrostatic force/attraction)", ["ionic bond (1)"], "One mark.", True, False),
    ("3.5.3", 3, "Bonding", "Explanation",
     "With reference to the lattice, explain why sodium fluoride has a very high melting point (1000 C).",
     True, [], "many strong ionic bonds / electrostatic forces; more energy to overcome them",
     ["many strong ionic bonds (1)", "more energy to break/overcome (1)"], "Three marks.", True, False),
    ("3.6.1", 2, "Bonding", "Data/Graph Interpretation",
     "Graph of melting points of sodium halides. Describe the trend.",
     True, [], "as atomic radius of the halide increases, the melting point decreases",
     ["radius increases (1)", "Bpt decreases (1)"], "Two marks; order matters (memo -1 if reversed).", True, False),
    ("3.6.2", 4, "Bonding", "Explanation",
     "Use electrostatics to explain the trend in 3.6.1.",
     True, [], "greater radius -> greater distance between ions -> weaker electrostatic forces -> less energy to overcome",
     ["greater radius (1)", "greater distance between ions (1)", "weaker electrostatic forces (1)", "less energy (1)"],
     "Four marks.", True, False),

    # ---------------- QUESTION 4: ENERGY PROFILE + STOICHIOMETRY (30 marks) ----------------
    ("4.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "CaCO3 + 2HCl -> CaCl2 + CO2 + H2O. Define the energy labelled V on the profile.",
     True, [], "the net change in chemical potential energy of the system (heat of reaction)",
     ["net change (1)", "chemical potential energy (1)"], "Two marks; profile is an image.", True, False),
    ("4.2.1", 4, "Energy & Chemical Change", "Diagram-based",
     "On the profile (labelled I-IV), name the energies I to IV.",
     True, [], "I energy of reactants; II activation energy; III energy released; IV energy of products",
     ["I reactants (1)", "II activation energy (1)", "III energy released (1)", "IV products (1)"],
     "Four marks; on the diagram.", True, False),
    ("4.2.2", 2, "Energy & Chemical Change", "Diagram-based",
     "Provide labels for A and B on the profile.",
     True, [], "A reactants; B reaction coordinate", ["A reactants (1)", "B reaction coordinate (1)"], "Two marks.", True, False),
    ("4.3.1", 1, "Energy & Chemical Change", "Short Answer",
     "Name the position on the graph labelled X.",
     True, [], "activated complex", ["activated complex (1)"], "One mark.", True, False),
    ("4.3.2", 3, "Energy & Chemical Change", "Short Answer",
     "State two conditions of reacting particles that must be met for X to form.",
     True, [], "collide; with sufficient kinetic energy; and correct orientation",
     ["collide (1)", "sufficient kinetic energy (1)", "correct orientation (1)"], "Three marks.", True, False),
    ("4.3.3", 2, "Energy & Chemical Change", "Short Answer",
     "What two processes occur simultaneously at X?",
     True, [], "bonds breaking and forming", ["breaking (1)", "forming (1)"], "Two marks.", True, False),
    ("4.4", 3, "Energy & Chemical Change", "Explanation",
     "Name the type of reaction this graph represents. Explain.",
     True, [], "exothermic — energy released > absorbed (products lower than reactants, dH<0)",
     ["exothermic (1)", "energy released > absorbed (1)", "products lower / dH<0 (1)"], "Three marks.", True, False),
    ("4.5", 2, "Energy & Chemical Change", "Diagram-based",
     "On the profile, show with a dotted line how the graph changes with a catalyst.",
     True, [], "dotted line with lower activation energy; reactants and products unchanged",
     ["lower Ea (1)", "reactants/products unchanged (1)"], "Two marks; on the diagram.", True, False),
    ("4.6", 3, "Energy & Chemical Change", "Explanation",
     "How would a catalyst affect the energy labelled V? Explain.",
     True, [], "no effect — reactants and products unaffected; catalyst only lowers Ea",
     ["no effect (1)", "reactants/products unaffected (1)", "catalyst lowers Ea only (1)"], "Three marks.", True, False),
    ("4.7.1", 3, "Stoichiometry", "Calculation",
     "3 g CaCO3 reacts; 0,5 dm3 CO2 collected at STP. Calculate moles of CO2 formed.",
     False, ["n=V/Vm"], "0,02 mol",
     ["n = V/Vm (1)", "0,5/22,4 (1)", "= 0,02 mol (1)"], "Three marks.", False, False),
    ("4.7.2", 5, "Stoichiometry", "Calculation",
     "Hence calculate the percentage purity of the 3 g sample.",
     False, ["n=m/M", "% purity = pure/impure x 100"], "74,40%",
     ["1:1 ratio CaCO3:CO2 (1)", "n(CaCO3)=0,02 mol (1)", "m=0,02x100=2,23 g (1)",
      "% = 2,23/3 x 100 (1)", "= 74,40% (1)"], "Five marks.", False, False),

    # ---------------- QUESTION 5: REACTION RATE (29 marks) ----------------
    ("5.1", 2, "Reaction Rates", "Definition/Explain",
     "Zn + H2SO4 (flasks A and B, equal Zn, different surface area). Define reaction rate.",
     False, [], "change in concentration per unit time of a reactant or product",
     ["change in concentration (1)", "per unit time (1)"], "Two marks.", False, False),
    ("5.2", 3, "Reaction Rates", "Short Answer",
     "Write the balanced equation for zinc + sulphuric acid.",
     False, [], "Zn + H2SO4 -> ZnSO4 + H2", ["Zn + H2SO4 (1)", "-> ZnSO4 (1)", "+ H2 (1)"], "Three marks.", False, False),
    ("5.3.1", 1, "Reaction Rates", "Short Answer",
     "Identify the independent variable.",
     False, [], "surface area of zinc", ["surface area (1)"], "One mark.", False, False),
    ("5.3.2", 1, "Reaction Rates", "Short Answer",
     "Identify the dependent variable.",
     False, [], "reaction rate", ["reaction rate (1)"], "One mark.", False, False),
    ("5.3.3", 2, "Reaction Rates", "Short Answer",
     "Identify two controlled variables.",
     False, [], "temperature, [H2SO4], amount of Zn, equal time (any two)",
     ["any two controlled vars (1 each)"], "Two marks (any two).", False, False),
    ("5.4", 2, "Reaction Rates", "Explanation",
     "Explain why the 5.3.3 variables must be controlled.",
     False, [], "they all affect reaction rate; controlling keeps the test fair",
     ["both affect rate (1)", "keeps test fair (1)"], "Two marks.", False, False),
    ("5.5", 3, "Reaction Rates", "Explanation",
     "Can rate be measured by mass lost over time? Agree/disagree and explain.",
     False, [], "No — H2 is a light gas; the mass decrease would be negligible",
     ["No (1)", "H2 light gas (1)", "negligible mass change (1)"], "Three marks.", False, False),
    ("5.6", 3, "Reaction Rates", "Calculation",
     "Calculate the average rate in flask A between 0 and 3 minutes (30 cm3 produced).",
     True, [], "10 cm3.min-1 (or 1,6e-4 dm3.s-1)",
     ["rate = 30/3 (1)", "= 10 (1)", "units cm3.min-1 (1)"], "Three marks; from the graph.", True, False),
    ("5.7", 2, "Reaction Rates", "Explanation",
     "Explain why the gradient of the graph decreases over time.",
     True, [], "gradient = rate; [acid] decreases as reactants are used up",
     ["gradient = rate (1)", "[acid] decreases (1)"], "Two marks.", True, False),
    ("5.8", 3, "Reaction Rates", "Diagram-based",
     "On the answer sheet, sketch the graph for flask B (powdered Zn).",
     True, [], "starts at zero, steeper gradient, ends sooner, ends at 30 cm3",
     ["starts at zero (1)", "steeper, ends sooner (1)", "ends at 30 cm3 (1)"], "Three marks; on the graph.", True, False),
    ("5.9", 4, "Reaction Rates", "Explanation",
     "Explain 5.8 using collision theory.",
     False, [], "powdered Zn has greater surface area -> more exposed particles -> more collisions -> more effective collisions/s",
     ["greater surface area (1)", "more particles exposed (1)", "more collisions (1)", "more effective collisions/s (1)"],
     "Four marks.", False, False),
    ("5.10", 3, "Reaction Rates", "Explanation",
     "Evaluate: 'increasing the volume of acid in a 100% efficient reaction always gives more product because "
     "there will be more moles of solute'.",
     False, [], "not always — more moles overall but not per unit volume; only if the limiting reagent's volume increases",
     ["statement corrected: not always (1)", "more moles overall (1)", "but not per unit volume / only if limiting reagent increased (1)"],
     "Three marks.", False, False),

    # ---------------- QUESTION 6: STOICHIOMETRY / STANDARD SOLUTIONS (28 marks) ----------------
    ("6.1.1", 6, "Stoichiometry", "Calculation",
     "55 cm3 0,25 M MgCl2 + 70 cm3 0,15 M AgNO3: MgCl2 + 2AgNO3 -> 2AgCl + Mg(NO3)2. "
     "Prove AgNO3 is the limiting reactant.",
     False, ["n=cV"], "AgNO3 limiting",
     ["n(MgCl2)=0,25x0,055=0,01375 (1)", "n(AgNO3)=0,15x0,070=0,0105 (1)",
      "ratio 1:2 -> need 5,25e-3 MgCl2 (1)", "0,01375 available > needed -> AgNO3 limiting (1)"],
     "Six marks; ratio method.", False, False),
    ("6.1.2", 3, "Stoichiometry", "Calculation",
     "Hence calculate the mass of AgCl formed.",
     False, ["n=m/M"], "1,51 g (unrounded 1,44 g)",
     ["2:2 ratio AgNO3:AgCl (1)", "n=0,0105 mol (1)", "m=0,0105x143,5=1,51 g (1)"], "Three marks.", False, False),
    ("6.1.3", 3, "Stoichiometry", "Calculation",
     "1,49 g AgCl recovered. Calculate the percentage yield.",
     False, ["% yield = actual/theoretical x 100"], "98,98%",
     ["1,49/1,51 (1)", "x100 (1)", "= 98,98% (1)"], "Three marks.", False, False),
    ("6.2.1", 1, "Stoichiometry", "Short Answer",
     "Why are the given solutions standard solutions?",
     False, [], "they have known concentrations", ["known concentrations (1)"], "One mark.", False, False),
    ("6.2.2", 2, "Stoichiometry", "Definition/Explain",
     "Define solvent.",
     False, [], "the substance in which another is dissolved, forming a solution",
     ["substance dissolving another (1)", "forming a solution (1)"], "Two marks.", False, False),
    ("6.2.3", 1, "Stoichiometry", "Short Answer",
     "Identify the solvent used.",
     False, [], "water (H2O)", ["water (1)"], "One mark.", False, False),
    ("6.2.4", 4, "Stoichiometry", "Short Answer",
     "Give the method for making a standard solution in four bullet points.",
     False, [], "mass required solid; transfer to volumetric flask; rinse with distilled water; make up to volume",
     ["mass solid (1)", "transfer to flask (1)", "rinse (1)", "make up to mark (1)"], "Four marks.", False, False),
    ("6.2.5", 3, "Bonding", "Short Answer",
     "Write the balanced dissociation equation for ammonium carbonate (NH4)2CO3.",
     False, [], "(NH4)2CO3 -> 2NH4+ + CO3 2-",
     ["(NH4)2CO3 (1)", "2NH4+ (1)", "CO3 2- (1)"], "Three marks.", False, False),
    ("6.2.6", 5, "Stoichiometry", "Calculation",
     "Solution A: 0,2 M NH4OH, 0,25 dm3. Solution B: 0,3 M (NH4)2CO3, 0,5 dm3. Calculate the new "
     "[NH4+] after mixing (no volume change).",
     False, ["n=cV", "c=n/V"], "0,47 mol.dm-3",
     ["n(NH4OH)=0,2x0,25=0,05 (1)", "n((NH4)2CO3)=0,3x0,5=0,15 x2=0,3 (1)",
      "c=(0,05+0,3)/(0,25+0,5) (1)", "=0,47 mol.dm-3 (1)"], "Five marks.", False, False),

    # ---------------- QUESTION 7: ORGANIC CHEMISTRY (13 marks) ----------------
    ("7.1", 2, "Organic Chemistry", "Definition/Explain",
     "Given compounds with an -OH group. Define functional group.",
     False, [], "an atom or group of atoms forming the centre of chemical activity in a molecule",
     ["atom/group of atoms (1)", "centre of chemical activity (1)"], "Two marks.", False, False),
    ("7.2", 1, "Organic Chemistry", "Diagram-based",
     "Using a structural formula, draw the functional group of the compounds.",
     True, [], "R-O-H (hydroxyl)", ["R-O-H (1)"], "One mark; drawing required.", True, False),
    ("7.3", 1, "Organic Chemistry", "Short Answer",
     "Name the functional group drawn in 7.2.",
     False, [], "hydroxyl", ["hydroxyl (1)"], "One mark.", False, False),
    ("7.4", 4, "Organic Chemistry", "Short Answer",
     "Give the IUPAC name of compound B (a diol drawn with two -OH groups).",
     True, [], "butane-1,3-diol", ["but- (1)", "-ane (1)", "1,3- (1)", "diol (1)"], "Four marks; structure is an image.", True, False),
    ("7.5.1", 1, "Organic Chemistry", "Short Answer",
     "Compounds A and B have similar molecular masses. Name the predominant IMF between their molecules.",
     False, [], "hydrogen bond forces", ["hydrogen bonding (1)"], "One mark.", False, False),
    ("7.5.2", 4, "Organic Chemistry", "Explanation",
     "Which compound (A or B) has the higher boiling point? Explain fully.",
     True, [], "B — it has two hydroxyl groups, so more hydrogen bonds, needing more energy to overcome",
     ["B (1)", "two hydroxyl groups (1)", "more H-bonds (1)", "more energy to overcome (1)"],
     "Four marks.", True, False),

    # ---------------- QUESTION 8: ORGANIC CHEMISTRY (17 marks) ----------------
    ("8.1", 2, "Organic Chemistry", "Short Answer",
     "Compound with pineapple flavour (ester drawn). Give its IUPAC name.",
     True, [], "ethyl butanoate", ["ethyl (1)", "butanoate (1)"], "Two marks; structure is an image.", True, False),
    ("8.2", 1, "Organic Chemistry", "Short Answer",
     "What homologous series does the compound belong to?",
     False, [], "ester", ["ester (1)"], "One mark.", False, False),
    ("8.3", 2, "Organic Chemistry", "Short Answer",
     "Give the IUPAC name of the carboxylic acid used to make it.",
     False, [], "butanoic acid", ["butan- (1)", "oic acid (1)"], "Two marks.", False, False),
    ("8.4", 4, "Organic Chemistry", "Diagram-based",
     "Using structural formulae, draw the two reactants required to make this ester.",
     True, [], "butan-1-ol (four carbons, hydroxyl) + butanoic acid (four carbons, carboxyl)",
     ["four carbons (1)", "carboxyl group (1)", "two carbons (1)", "hydroxyl group (1)"], "Four marks; structures.", True, False),
    ("8.5", 2, "Organic Chemistry", "Short Answer",
     "Give the formula of the acid catalyst used in ester formation.",
     False, [], "H2SO4", ["H2SO4 (2)"], "Two marks (name alone = 1).", False, False),
    ("8.6", 2, "Organic Chemistry", "Definition/Explain",
     "Define structural isomers.",
     False, [], "compounds with the same molecular formula but different structural formulae",
     ["same molecular formula (1)", "different structural formula (1)"], "Two marks.", False, False),
    ("8.7", 2, "Organic Chemistry", "Short Answer",
     "Give the IUPAC name of one positional isomer of this ester.",
     False, [], "butyl ethanoate (or methyl pentanoate / propyl propanoate / pentyl methanoate)",
     ["any positional isomer name (2)"], "Two marks.", False, False),
    ("8.8", 2, "Organic Chemistry", "Short Answer",
     "Give the condensed structural formula of the functional isomer of this compound.",
     False, [], "CH3(CH2)4COOH (pentanoic acid)", ["CH3(CH2)4COOH (2)"], "Two marks.", False, False),

    # ---------------- QUESTION 9: ORGANIC CHEMISTRY / REACTIONS (22 marks) ----------------
    ("9.1", 2, "Organic Chemistry", "Explanation",
     "Flow diagram with CH3CH=CHCH3. Explain why it is an unsaturated hydrocarbon.",
     False, [], "contains only C and H and has at least one C=C double bond",
     ["only C and H (1)", "has a double bond (1)"], "Two marks.", False, False),
    ("9.2.1", 1, "Organic Chemistry", "Short Answer",
     "Give the general name for Reaction 1 (elimination of H2O from an alcohol).",
     False, [], "Elimination", ["Elimination (1)"], "One mark.", False, False),
    ("9.2.2", 1, "Organic Chemistry", "Short Answer",
     "Give the general name for Reaction 2 (cracking).",
     False, [], "Elimination", ["Elimination (1)"], "One mark.", False, False),
    ("9.3", 2, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula for Product 1 (butan-2-ol).",
     True, [], "four-carbon chain with -OH on carbon 2", ["four carbons (1)", "OH on C2 (1)"], "Two marks; structure.", True, False),
    ("9.4", 2, "Organic Chemistry", "Short Answer",
     "Give the reaction conditions for Reaction 1 (elimination).",
     False, [], "concentrated alkali (NaOH/KOH in ethanol) and heat", ["conc alkali/NaOH/KOH in ethanol (1)", "heat (1)"], "Two marks.", False, False),
    ("9.5.1", 1, "Organic Chemistry", "Short Answer",
     "Give the formula of Reactant X (added to alkene to make alcohol).",
     False, [], "HCl", ["HCl (1)"], "One mark.", False, False),
    ("9.5.2", 1, "Organic Chemistry", "Short Answer",
     "Give the formula of Reactant Y (added to make alkane).",
     False, [], "H2", ["H2 (1)"], "One mark.", False, False),
    ("9.6", 3, "Organic Chemistry", "Calculation",
     "Write a balanced equation for complete combustion of CH3CH=CHCH3 (C4H8) using molecular formula.",
     False, [], "C4H8 + 6O2 -> 4CO2 + 4H2O",
     ["reactants (1)", "balanced (1)", "products (1)"], "Three marks.", False, False),
    ("9.7.1", 2, "Organic Chemistry", "Short Answer",
     "CH3CH=CHCH3 + Br2 bubbled through bromine water. What is observed?",
     False, [], "rapid decolourising (of the red-brown bromine water)",
     ["rapid (1)", "decolourising (1)"], "Two marks.", False, False),
    ("9.7.2", 1, "Organic Chemistry", "Short Answer",
     "What specific TYPE of organic reaction is this?",
     False, [], "Halogenation", ["Halogenation (1)"], "One mark.", False, False),
    ("9.7.3", 2, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula of Product 2 (dibromoalkane).",
     True, [], "two bromides on C2 and C3 of a four-carbon chain",
     ["two bromides on C2,C3 (1)", "four carbons (1)"], "Two marks; structure.", True, False),
    ("9.7.4", 2, "Organic Chemistry", "Short Answer",
     "Give the IUPAC name of Product 2.",
     False, [], "2,3-dibromobutane", ["2,3-dibromo (1)", "butane (1)"], "Two marks.", False, False),
    ("9.8.1", 1, "Organic Chemistry", "Short Answer",
     "Reaction 2 is a cracking reaction. What type of cracking is taking place?",
     False, [], "Thermal cracking", ["Thermal cracking (1)"], "One mark.", False, False),
    ("9.8.2", 1, "Organic Chemistry", "Short Answer",
     "Give the general formula for hydrocarbon Z (an alkene from cracking).",
     False, [], "CnH2n", ["CnH2n (1)"], "One mark.", False, False),
]
