"""Pass 1 evidence table — Grade 11 Chemistry Examination, 11 November 2024.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/G11 - Chemistry - Examination - QP - 2024(Print).pdf (135 marks, Mr McCoy)
Memo:   data/organized/chemistry/G11 - Chemistry - Nov Examination - MG  - 2024.pdf (135 marks, Mr McCoy)

NOTE: the memo mislabels QUESTION 5 as "29 MARKS"; the question paper's printed
per-question total for Q5 is 13 and the memo's own marking for Q5 sums to 13. The
evidence is aligned to the paper's printed TOTAL of 135 (Q5 = 13 marks). The memo's
Q6.4.1 prints "CnH2n+2O2" for the carboxylic-acid general formula, which is incorrect;
the correct general formula is CnH2nO2 (recorded here).

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2024-NOV",
    "paper_path": "data/organized/chemistry/G11 - Chemistry - Examination - QP - 2024(Print).pdf",
    "memo_path": "data/organized/chemistry/G11 - Chemistry - Nov Examination - MG  - 2024.pdf",
    "year": 2024,
    "exam_date": "11 November 2024",
    "exam_period": "november",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 135,
    "examiner": "Mr McCoy",
    "moderator": "Mr Ntombela",
    "duration_stated": "2 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set final Chemistry paper (St Benedict's College). Q6 depends on a flow-diagram "
        "image: sub-questions that cannot be resolved from text are flagged needs_visual. "
        "Boltzmann/energy-profile sketches (Q2.4) are diagram-based."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: BONDING / IMFs (22 marks) ----------------
    ("1.1", 4, "Intermolecular Forces", "Diagram-based",
     "Complete the diagram: one NH3 hydrogen-bonded to one ethanol molecule (lone pairs + partial charges).",
     True, [], "linear O-H...N (or N-H...O) with delta charges and lone pairs on N/O",
     ["lone pairs + partial charges (1)", "dotted H-bond line (1)", "linear O-H...N (1)", "correct atoms (1)"], "Four marks; on the diagram.", True, False),
    ("1.2.1", 2, "Bonding", "Definition/Explain",
     "Define electronegativity (Table 1: H 2,1; C 2,5; N 3,0; O 3,5; Br 2,8).",
     False, [], "tendency of an atom to attract a bonding pair of electrons", ["tendency (1)", "attract bonding pair (1)"], "Two marks.", False, False),
    ("1.2.2", 1, "Bonding", "Short Answer",
     "Two atoms from Table 1 that form the most polar bond.",
     False, [], "H and O", ["H and O (1)"], "One mark.", False, False),
    ("1.2.3", 2, "Bonding", "Explanation",
     "C-Br bond is polar. Explain why CBr4 is not a polar molecule.",
     False, [], "CBr4 is symmetrical (tetrahedral) -> even electron density -> non-polar",
     ["symmetrical (1)", "even electron density (1)"], "Two marks.", False, False),
    ("1.2.4", 5, "Intermolecular Forces", "Explanation",
     "Why CBr4 has a higher Bpt than CHBr3 (refer to IMFs).",
     False, [], "CBr4 has larger e-cloud -> stronger London forces than CHBr3 (London+dipole-dipole); more energy to overcome",
     ["CBr4 London only (1)", "CHBr3 London + dipole (1)", "CBr4 larger e-cloud (1)", "stronger London (1)", "more energy (1)"], "Five marks.", False, False),
    ("1.2.5", 1, "Bonding", "Short Answer",
     "Name the physical form of carbon that conducts electricity.",
     False, [], "graphite", ["graphite (1)"], "One mark.", False, False),
    ("1.2.6", 2, "Bonding", "Explanation",
     "Explain how carbon conducts electricity in that form.",
     False, [], "graphite has delocalised electrons (only 3 of 4 bonds used); free to move",
     ["delocalised electrons (1)", "free to move (1)"], "Two marks.", False, False),
    ("1.3.1", 2, "Bonding", "Short Answer",
     "AsH3 + H+ -> AsH4+. Classify the specific bonds in AsH3.",
     False, [], "polar covalent", ["polar (1)", "covalent (1)"], "Two marks.", False, False),
    ("1.3.2", 3, "Bonding", "Diagram-based",
     "A dative covalent bond forms. Lewis diagram of AsH4+ (electrons of each element different).",
     True, [], "As with lone pair donating to H+; AsH4+ with + charge",
     ["H has 1 e- (1)", "As has 5 e- (1)", "lone pair + charge (1)"], "Three marks; Lewis diagram.", True, False),

    # ---------------- QUESTION 2: REACTION RATES (Mg + HCl) (26 marks) ----------------
    ("2.1", 2, "Reaction Rates", "Definition/Explain",
     "Mg + 2HCl -> MgCl2 + H2. Define reaction rate.",
     False, [], "change in amount/concentration per unit time of reactant or product", ["change in conc (1)", "per unit time (1)"], "Two marks.", False, False),
    ("2.2", 4, "Reaction Rates", "Explanation",
     "Use collision theory to explain how [HCl] affects the rate.",
     False, [], "more/less particles per volume -> more/less collisions/s -> more/less effective collisions/s -> rate up/down",
     ["particles per volume (1)", "collisions/s (1)", "effective collisions/s (1)", "rate change (1)"], "Four marks.", False, False),
    ("2.3", 2, "Reaction Rates", "Explanation",
     "Why an increase in temperature increases the rate.",
     False, [], "more particles have KE >= activation energy", ["more particles (1)", "KE >= Ea (1)"], "Two marks.", False, False),
    ("2.4", 3, "Reaction Rates", "Diagram-based",
     "Sketch Boltzmann curves for high and low temperature; label them.",
     True, [], "low temp curve shifted left/lower peak; high temp broader/higher",
     ["axes correct (1)", "correct curves (1)", "Ea labelled larger for high T (1)"], "Three marks; on the graph.", True, False),
    ("2.5", 2, "Scientific Skills", "Short Answer",
     "Two control variables for a fair comparison.",
     False, [], "same surface area of Mg; constant temperature for each reaction",
     ["surface area of Mg (1)", "constant temperature (1)"], "Two marks.", False, False),
    ("2.6", 2, "Reaction Rates", "Data/Graph Interpretation",
     "From the graph, which [HCl] is fastest? Explain via gradient.",
     True, [], "2 mol.dm-3 (steepest gradient)", ["2 mol.dm-3 (1)", "steepest gradient (1)"], "Two marks; from the graph.", True, False),
    ("2.7", 2, "Reaction Rates", "Diagram-based",
     "Draw the expected graph for 1,5 mol.dm-3 HCl.",
     True, [], "curve starting at 0, between the 1 and 2 mol.dm-3 curves, ending at the same level",
     ["between 1 and 2 (1)", "same final level (1)"], "Two marks; on the graph.", True, False),
    ("2.8", 2, "Reaction Rates", "Definition/Explain",
     "What is a catalyst and how does it affect rate?",
     False, [], "substance that increases rate but is unchanged; provides an alternative pathway",
     ["definition (1)", "alternative pathway (1)"], "Two marks.", False, False),
    ("2.9", 2, "Reaction Rates", "Diagram-based",
     "If a catalyst is added to half the volume of 2 M HCl, draw/label the new line.",
     True, [], "steeper initial gradient than 2 M, but half the total H2 volume",
     ["steeper initial gradient (1)", "half the volume (1)"], "Two marks; on the graph.", True, False),
    ("2.10", 3, "Reaction Rates", "Explanation",
     "Why the rate decreases over time even at high [acid].",
     False, [], "rate proportional to effective collisions/s; as [reactants] falls, fewer particles -> slower",
     ["proportional to effective collisions (1)", "conc decreases (1)", "fewer particles -> slower (1)"], "Three marks.", False, False),
    ("2.11", 2, "Reaction Rates", "Explanation",
     "Why downward displacement of water suits collecting H2 here.",
     False, [], "H2 is non-polar, not significantly soluble in water, so it displaces water effectively",
     ["H2 non-polar (1)", "not soluble -> displaces water (1)"], "Two marks.", False, False),

    # ---------------- QUESTION 3: QUANTITATIVE CHEMISTRY (25 marks) ----------------
    ("3.1.1", 4, "Stoichiometry", "Calculation",
     "Al2O3 + 2NaOH + 3H2O -> 2NaAl(OH)4. 200 ml 2,0 M NaOH + 12 g H2O. Limiting reagent?",
     False, ["n=cV", "n=m/M"], "NaOH is limiting",
     ["n(NaOH)=0,4 (1)", "n(H2O)=0,67 (1)", "2:3 -> 0,4 needs 0,6 (1)", "NaOH limiting (1)"], "Four marks.", False, False),
    ("3.1.2", 2, "Stoichiometry", "Definition/Explain",
     "Explain 'yield' in a reaction.",
     False, [], "extent of reaction; product obtained vs product possible", ["extent (1)", "actual vs possible (1)"], "Two marks.", False, False),
    ("3.1.3", 5, "Stoichiometry", "Calculation",
     "If 45 g NaAl(OH)4 produced, percentage yield? (M=118)",
     False, ["% yield = actual/theoretical x 100"], "95,33%",
     ["ratio 1:1 (1)", "theoretical = 0,4 mol = 47,2 g (1)", "% = 45/47,2 (1)", "x100 (1)", "=95,33% (1)"], "Five marks.", False, False),
    ("3.2.1", 3, "Stoichiometry", "Calculation",
     "Fe2O3 + 3CO -> 2Fe + 3CO2. 1 kg Fe, 100% efficient, CO excess. Fe2O3 required?",
     False, ["n=m/M"], "8,93 mol (= 1428,8 g)",
     ["n(Fe)=1000/56=17,86 (1)", "2:1 -> 8,93 mol (1)", "m=8,93x160 (1)"], "Three marks.", False, False),
    ("3.2.2", 4, "Stoichiometry", "Calculation",
     "Number of iron atoms required for 1 kg Fe.",
     False, ["N=n.Na"], "1,075 x 10^25 Fe atoms",
     ["n(Fe2O3)=8,93 (1)", "x6,02e23 units (1)", "x2 Fe atoms (1)", "=1,075e25 (1)"], "Four marks.", False, False),
    ("3.2.3", 3, "Stoichiometry", "Calculation",
     "Volume of CO2 produced at STP.",
     False, ["V=n.Vm"], "600 dm3",
     ["n(CO2)=26,79 (1)", "V=26,79x22,4 (1)", "=600 (1)"], "Three marks.", False, False),
    ("3.2.4", 4, "Stoichiometry", "Calculation",
     "Mass of Fe2O3 if only 70% efficient (still 1 kg Fe).",
     False, ["m=nM"], "2041,14 g",
     ["100% mass = 1428,8 g (1)", "mass x 0,7 = 1428,8 (1)", "mass = 2041,14 g (1)"], "Three/four marks.", False, False),

    # ---------------- QUESTION 4: ELECTROCHEMISTRY / REDOX (15 marks) ----------------
    ("4.1.1", 1, "Bonding", "Short Answer",
     "Silver spoon electroplated with gold. Should A be the POSITIVE or NEGATIVE terminal? (circle)",
     False, [], "NEGATIVE", ["NEGATIVE (1)"], "One mark; spoon is the cathode.", False, False),
    ("4.1.2", 2, "Bonding", "Short Answer",
     "Half-reaction at the anode.",
     False, [], "Au -> Au3+ + 3e-", ["Au (1)", "Au3+ + 3e- (1)"], "Two marks.", False, False),
    ("4.1.3", 2, "Bonding", "Definition/Explain",
     "Define electrolyte.",
     False, [], "substance that conducts electricity due to free/mobile ions when molten or dissolved",
     ["conducts via ions (1)", "molten or dissolved (1)"], "Two marks.", False, False),
    ("4.1.4", 2, "Bonding", "Short Answer",
     "Formula of an appropriate electrolyte for gold plating.",
     False, [], "Au(NO3)3 / AuCl3 / AuBr3 / NaAuCl4 / KAu(CN)2", ["gold ion (1)", "balanced anion (1)"], "Two marks.", False, False),
    ("4.2.1", 2, "Bonding", "Short Answer",
     "Dissociation equation for copper(II) nitrate (state symbols).",
     False, [], "Cu(NO3)2(s) -> Cu2+(aq) + 2NO3-(aq)", ["Cu2+ (1)", "2NO3- + states (1)"], "Two marks.", False, False),
    ("4.2.2", 4, "Bonding", "Explanation",
     "Ni rod in Cu(NO3)2. Use oxidation numbers: which is oxidised/reduced?",
     False, [], "Ni oxidised (Ni0 -> Ni2+, ON up); Cu2+ reduced (Cu2+ -> Cu0, ON down)",
     ["Ni oxidised (1)", "Ni0->Ni2+ (1)", "Cu2+ reduced (1)", "Cu2+->Cu0 (1)"], "Four marks.", False, False),
    ("4.2.3", 2, "Bonding", "Short Answer",
     "Balanced net ionic equation for the reaction.",
     False, [], "Cu2+ + Ni -> Ni2+ + Cu", ["reactants (1)", "products (1)"], "Two marks.", False, False),

    # ---------------- QUESTION 5: ORGANIC CHEMISTRY (13 marks) ----------------
    ("5.1", 3, "Organic Chemistry", "Explanation",
     "Pentane vs pent-1-ene (both colourless liquids). Describe a chemical test to distinguish.",
     False, [], "add bromine water; pent-1-ene decolourises it (reddish-brown -> colourless) faster",
     ["bromine water (1)", "pent-1-ene decolourises (1)", "colourless (1)"], "Three marks.", False, False),
    ("5.2", 2, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula of dimethylpropane (C5H12).",
     False, [], "(CH3)4C (central C with four CH3 groups)", ["central C (1)", "four CH3 (1)"], "Two marks.", False, False),
    ("5.3.1", 2, "Organic Chemistry", "Definition/Explain",
     "Define isomers.",
     False, [], "same molecular formula but different structural formula", ["same mol formula (1)", "different structural (1)"], "Two marks.", False, False),
    ("5.3.2", 2, "Organic Chemistry", "Diagram-based",
     "Draw the third chain isomer of pentane.",
     False, [], "2-methylbutane", ["correct structure (2)"], "Two marks.", False, False),
    ("5.4", 4, "Intermolecular Forces", "Explanation",
     "Why pentan-1-ol has a lower Bpt than butanoic acid despite equal molar mass.",
     False, [], "both H-bond, but butanoic acid forms two H-bonds/molecule vs one in pentan-1-ol -> more energy",
     ["both H-bond (1)", "butanoic acid 2 H-bonds (1)", "pentan-1-ol 1 (1)", "more energy (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 6: ORGANIC CHEMISTRY (flow diagram) (34 marks) ----------------
    ("6.1", 2, "Organic Chemistry", "Definition/Explain",
     "Define homologous series.",
     False, [], "series of similar compounds with same functional group and general formula, differing by CH2",
     ["same FG + general formula (1)", "differ by CH2 (1)"], "Two marks.", False, False),
    ("6.2", 1, "Organic Chemistry", "Short Answer",
     "To which homologous series does bromoethane belong?",
     False, [], "haloalkanes", ["haloalkanes (1)"], "One mark.", False, False),
    ("6.3", 2, "Organic Chemistry", "Definition/Explain",
     "Define functional group.",
     False, [], "an atom/group of atoms forming the centre of chemical activity in the molecule",
     ["atom/group (1)", "centre of activity (1)"], "Two marks.", False, False),
    ("6.4.1", 1, "Organic Chemistry", "Short Answer",
     "General formula for CH3(CH2)3COOH.",
     False, [], "CnH2nO2 (carboxylic acids)",
     ["CnH2nO2 (memo prints CnH2n+2O2, which is incorrect)"], "One mark.", False, True),
    ("6.4.2", 2, "Organic Chemistry", "Diagram-based",
     "Draw the functional group of CH3(CH2)3COOH.",
     False, [], "carboxyl group -COOH", ["correct -COOH (2)"], "Two marks.", False, False),
    ("6.5.1", 1, "Organic Chemistry", "Short Answer",
     "Specific type of reaction B.",
     True, [], "dehydration", ["dehydration (1)"], "One mark; from the flow diagram.", True, False),
    ("6.5.2", 1, "Organic Chemistry", "Short Answer",
     "Specific type of reaction D.",
     True, [], "hydrolysis", ["hydrolysis (1)"], "One mark; from the flow diagram.", True, False),
    ("6.6", 2, "Organic Chemistry", "Short Answer",
     "Two reaction conditions for reaction B.",
     True, [], "heat the alcohol with excess concentrated H2SO4 or H3PO4", ["heat alcohol (1)", "excess conc H2SO4/H3PO4 (1)"], "Two marks; from the flow diagram.", True, False),
    ("6.7.1", 1, "Organic Chemistry", "Short Answer",
     "Reaction A: name of the inorganic reactant.",
     True, [], "water", ["water (1)"], "One mark; from the flow diagram.", True, False),
    ("6.7.2", 1, "Organic Chemistry", "Short Answer",
     "Reaction A: chemical formula of the catalyst needed.",
     True, [], "H2SO4 or H3PO4", ["H2SO4/H3PO4 (1)"], "One mark; from the flow diagram.", True, False),
    ("6.8.1", 3, "Organic Chemistry", "Diagram-based",
     "Reaction C: write a balanced equation (structural formula).",
     True, [], "UNRESOLVED - depends on the flow-diagram reaction C (esterification/hydrolysis not legible from text)",
     ["flow-diagram image not readable in text"], "Three marks; needs the flow diagram.", True, True),
    ("6.8.2", 1, "Organic Chemistry", "Short Answer",
     "Why no water should be present during reaction C.",
     True, [], "to avoid forming the hydroxyl group / an alcohol", ["avoid -OH / alcohol (1)"], "One mark; from the flow diagram.", True, False),
    ("6.9.1", 1, "Organic Chemistry", "Short Answer",
     "Reaction E (alcohol -> X): type of reaction.",
     True, [], "esterification", ["esterification (1)"], "One mark; from the flow diagram.", True, False),
    ("6.9.2", 1, "Organic Chemistry", "Short Answer",
     "Reaction E: chemical formula of the catalyst needed.",
     True, [], "H2SO4", ["H2SO4 (1)"], "One mark; from the flow diagram.", True, False),
    ("6.9.3", 2, "Organic Chemistry", "Diagram-based",
     "Reaction E: structural formula of compound X.",
     True, [], "CH3(CH2)3COOCH2CH3 (ethyl pentanoate)", ["acid part (1)", "ethyl part (1)"], "Two marks.", True, False),
    ("6.9.4", 2, "Organic Chemistry", "Short Answer",
     "Reaction E: IUPAC name of compound X.",
     True, [], "ethyl pentanoate", ["ethyl (1)", "pentanoate (1)"], "Two marks; from the flow diagram.", True, False),
    ("6.10", 3, "Organic Chemistry", "Short Answer",
     "Reaction F (warm concentrated NaOH): balanced equation (condensed formula).",
     True, [], "CH3CH2Br + NaOH -> CH2=CH2 + NaBr + H2O (elimination)",
     ["CH3CH2Br (1)", "CH2=CH2 (1)", "NaBr + H2O (1)"], "Three marks; from the flow diagram.", True, False),
    ("6.11.1", 2, "Organic Chemistry", "Short Answer",
     "Catalytic cracking: CH3(CH2)6CH3 -> CH2=CH2 + Y. IUPAC name of Y.",
     False, [], "hexane (or any C6H14 branched alkane e.g. 2-methylpentane)",
     ["hexane / C6H14 (2)"], "Two marks.", False, False),
    ("6.11.2", 2, "Organic Chemistry", "Explanation",
     "Why shorter-chained alkenes/branched alkanes are more suitable for petrol.",
     False, [], "less surface area / weaker IMFs / lower activation energy -> more flammable",
     ["less surface area / weaker IMF (1)", "more flammable (1)"], "Two marks.", False, False),
    ("6.12.1", 1, "Organic Chemistry", "Short Answer",
     "'Heating under reflux' diagram: which reaction (A-F) uses it?",
     True, [], "reaction A", ["A (1)"], "One mark; from the flow diagram.", True, False),
    ("6.12.2", 2, "Organic Chemistry", "Explanation",
     "Why organic reactions are done under reflux/water bath.",
     True, [], "allows extended heating and maintains reaction concentration",
     ["extended heating (1)", "maintains concentration (1)"], "Two marks; from the flow diagram.", True, False),
]
