"""Pass 1 evidence table — Grade 11 Physical Science: Chemistry Mid-Year, 25 July 2023.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/G11- Mid-Year Examination - QP - 2023.pdf   (165 marks, Mr McCoy)
Memo:   data/organized/chemistry/G11- Mid-Year Examination - MG. - 2023.pdf (165 marks, Mr McCoy)

NOTE: the memo mislabels QUESTION 4 as "15 MARKS", but the question paper's printed
per-question total for Q4 is 31 and its sub-question marks sum to 31. The evidence is
aligned to the paper's printed TOTAL of 165, so Q4 is recorded at 31 marks.

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2023-JUL",
    "paper_path": "data/organized/chemistry/G11- Mid-Year Examination - QP - 2023.pdf",
    "memo_path": "data/organized/chemistry/G11- Mid-Year Examination - MG. - 2023.pdf",
    "year": 2023,
    "exam_date": "25 July 2023",
    "exam_period": "july",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 165,
    "examiner": "Mr McCoy",
    "moderator": "Mr Hilder",
    "duration_stated": "2,5 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set mid-year Chemistry paper (St Benedict's College). Energy-profile, "
        "Maxwell-Boltzmann and graph-sketch sub-parts are diagram-based."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (16 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Formula for magnesium sulphite. A Mg(SO3)2 / B MgSO4 / C Mg3SO2 / D MgSO3",
     False, [], "D", ["MgSO3"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Matter & Materials", "Multiple Choice",
     "Formula of ammonium dichromate. A (NH4)3Cr2O7 / B NH4Cr2O7 / C (NH4)2Cr2O7 / D NH4(Cr2O7)2",
     False, [], "C", ["(NH4)2Cr2O7"], "Memo gives the correct option only.", False, False),
    ("1.3", 2, "Bonding", "Multiple Choice",
     "Bonds in nitrate ion NO3- are best classified as... A ionic / B pure covalent / C polar covalent / D London",
     False, [], "C", ["polar covalent"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Bonding", "Multiple Choice",
     "Ionic bonding: particles and electrons. A non-metal ions only / transferred; B metal+non-metal / shared; "
     "C non-metal only / shared; D metal+non-metal / transferred",
     False, [], "D", ["metal and non-metal ions; electrons transferred"], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Stoichiometry", "Multiple Choice",
     "Number of atoms in 10 g NH3. A 10/10x6,02e23x4 / B 10/17x4 / C 10/17x6,02e23x4 / D 10/17x6,02e23",
     False, [], "C", ["(10/17) x 6,02e23 x 4"], "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Energy & Chemical Change", "Multiple Choice",
     "Ep vs reaction coordinate graph. Which statement is correct? A forward exothermic / "
     "B heat = R-Q / C Ea = R-Q / D heat = Q-P",
     True, [], "D", ["heat of reaction = Q - P"], "Memo gives D; graph is an image.", True, False),
    ("1.7", 2, "Reaction Rates", "Multiple Choice",
     "Maxwell-Boltzmann curves at four temperatures, min E marked. Which curve = highest rate?",
     True, [], "D", ["highest-temperature curve (most area beyond E)"], "Memo gives the correct option; graph is an image.", True, False),
    ("1.8", 2, "Matter & Materials", "Multiple Choice",
     "5 kg rice, 0,2x10^6 grains. Average mass per grain? A 2,5e-5 g / B 25 000 ug / C 0,025 kg / D 250 mg",
     False, [], "B", ["5000 g / 200 000 = 0,025 g = 25 000 ug"], "Memo gives the correct option only.", False, False),

    # ---------------- QUESTION 2: CHEMICAL BONDING (Fe/Fe oxides) (21 marks) ----------------
    ("2.1", 4, "Bonding", "Short Answer",
     "Iron + oxygen -> iron (III) oxide. Balanced equation with state symbols.",
     False, [], "2Fe + 3O2 -> 2Fe2O3", ["2Fe (1)", "3O2 (1)", "2Fe2O3 (1)", "balanced (1)"], "Four marks.", False, False),
    ("2.2", 4, "Bonding", "Explanation",
     "Explain in terms of bonding/structure why iron (III) oxide has a high melting point.",
     False, [], "ionic bonding; many strong electrostatic forces needing much energy to overcome",
     ["ionic bonding (1)", "many strong forces (1)", "need energy to overcome (1)", "high MP (1)"], "Four marks.", False, False),
    ("2.2b", 1, "Bonding", "Short Answer",
     "Why does iron (III) oxide NOT conduct electricity when solid?",
     False, [], "ions are fixed in position (not free to move)", ["ions fixed in lattice (1)"], "One mark.", False, False),
    ("2.3", 4, "Bonding", "Explanation",
     "Iron conducts when solid and molten. Describe solid iron's bonding and why it conducts.",
     False, [], "metallic bonding: positive kernels + sea of delocalised electrons free to move",
     ["metallic bonding (1)", "positive kernels (1)", "sea of electrons (1)", "free to move (1)"], "Four marks.", False, False),
    ("2.4a", 3, "Bonding", "Diagram-based",
     "Use Lewis diagrams to show formation of iron (II) oxide (1565 C vs 1377 C).",
     False, [], "Fe -> Fe2+ + 2e-; O + 2e- -> O2-; lattice formed", ["Lewis diagrams (3)"], "Three marks; Lewis diagrams.", False, False),
    ("2.4b", 2, "Bonding", "Explanation",
     "Describe the bonding in iron (II) oxide.",
     False, [], "ionic; electrostatic attraction between Fe2+ and O2-", ["ionic (1)", "electrostatic attraction (1)"], "Two marks.", False, False),
    ("2.4c", 3, "Bonding", "Explanation",
     "Explain why the two oxides have different melting points.",
     False, [], "Fe2O3 has Fe3+ (greater charge) -> stronger attraction to O2- -> higher MP",
     ["Fe3+ charge (1)", "greater force (1)", "higher MP (1)"], "Three marks.", False, False),

    # ---------------- QUESTION 3: CHEMICAL BONDING (N2 / NH3) (24 marks) ----------------
    ("3.1", 1, "Bonding", "Short Answer",
     "N2 + 3H2 -> 2NH3. This bond (non-polar covalent) is found between nitrogen (ATOMS/MOLECULE).",
     False, [], "ATOMS", ["ATOMS (1)"], "One mark.", False, False),
    ("3.2", 2, "Bonding", "Explanation",
     "Explain why the N-N bond is called a covalent bond.",
     False, [], "electron pairs shared between two non-metal atoms", ["shared (1)", "non-metals (1)"], "Two marks.", False, False),
    ("3.3", 2, "Bonding", "Explanation",
     "Explain why the N-N bond is non-polar.",
     False, [], "electrons equally shared because zero electronegativity difference", ["equally shared (1)", "zero EN diff (1)"], "Two marks.", False, False),
    ("3.4", 3, "Bonding", "Calculation",
     "Ammonia is polar. Determine bond polarity (EN N=3,0, H=2,1).",
     False, [], "END = 3 - 2,1 = 0,9 > 0 -> polar bonds", ["END = 3-2,1 (1)", "= 0,9 (1)", "polar (1)"], "Three marks.", False, False),
    ("3.4b", 4, "Bonding", "Explanation",
     "Use a Couper diagram and explanation to show why NH3 is a polar molecule.",
     False, [], "pyramidal shape -> no electron-cloud symmetry -> net dipole",
     ["pyramidal shape (1)", "no symmetry (1)", "net dipole (1)", "explanation (1)"], "Four marks.", False, False),
    ("3.4a", 1, "Intermolecular Forces", "Short Answer",
     "Name the specific IMF in liquid ammonia.",
     False, [], "hydrogen bonding", ["H-bonding (1)"], "One mark.", False, False),
    ("3.4c", 3, "Intermolecular Forces", "Diagram-based",
     "Draw three NH3 molecules to show the H-bond arrangement.",
     True, [], "three NH3 with H-bonds between H and lone pair on N", ["three molecules (1)", "H-bonds (1)", "arrangement (1)"], "Three marks; diagram.", True, False),
    ("3.5", 1, "Intermolecular Forces", "Short Answer",
     "Name the specific IMF in liquid nitrogen.",
     False, [], "London forces", ["London (1)"], "One mark.", False, False),
    ("3.5b", 4, "Intermolecular Forces", "Explanation",
     "Explain, in terms of origin of IMFs, how nitrogen liquefies.",
     False, [], "as N2 molecules approach, e-cloud disperses -> induced/temporary dipoles -> attraction",
     ["molecules approach (1)", "e-dispersion (1)", "induced dipoles (1)", "attract (1)"], "Four marks.", False, False),
    ("3.6", 3, "Intermolecular Forces", "Explanation",
     "Account for the difference in liquefying temperatures of NH3 (-33,1) and N2 (-195,8).",
     False, [], "NH3 has H-bonding (stronger), N2 only London; H-bond stronger -> NH3 liquefies first",
     ["NH3 H-bond (1)", "N2 London (1)", "H-bond stronger -> NH3 first (1)"], "Three marks.", False, False),

    # ---------------- QUESTION 4: ENERGY AND RATES (citric acid + bicarbonate) (31 marks) ----------------
    ("4.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define heat of reaction.",
     False, [], "the net change in chemical potential energy of the system", ["net change (1)", "chem PE of system (1)"], "Two marks.", False, False),
    ("4.2", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define endothermic reaction.",
     False, [], "reactions that transform thermal energy into chemical potential energy", ["thermal -> chem PE (1)", "chem PE (1)"], "Two marks.", False, False),
    ("4.3", 1, "Energy & Chemical Change", "Short Answer",
     "Reaction absorbs more than released. Classify ENDOTHERMIC or EXOTHERMIC.",
     False, [], "ENDOTHERMIC", ["ENDOTHERMIC (1)"], "One mark.", False, False),
    ("4.4", 1, "Energy & Chemical Change", "Short Answer",
     "Is bond breaking an ENDOTHERMIC or EXOTHERMIC process?",
     False, [], "ENDOTHERMIC", ["ENDOTHERMIC (1)"], "One mark.", False, False),
    ("4.5a", 3, "Reaction Rates", "Explanation",
     "Equipment diagram: which quantities are measured and why is it possible?",
     True, [], "loss of mass, because CO2 (heavy gas) escapes the vessel", ["loss of mass (1)", "CO2 escapes (1)", "possible (1)"], "Three marks; diagram is an image.", True, False),
    ("4.5b", 3, "Reaction Rates", "Explanation",
     "Why is cotton wool placed at the mouth of the conical flask?",
     True, [], "so lost mass is only from escaping gas; splashes trapped", ["only gas escapes (1)", "traps splashes (1)", "explanation (1)"], "Three marks; diagram is an image.", True, False),
    ("4.5c", 1, "Reaction Rates", "Short Answer",
     "Additional equipment needed to measure the rate.",
     True, [], "a timer", ["timer (1)"], "One mark.", True, False),
    ("4.5d", 2, "Reaction Rates", "Short Answer",
     "Alternative equipment and the measured quantity.",
     True, [], "inverted measuring cylinder (gas volume) OR gas syringe", ["equipment (1)", "gas volume (1)"], "Two marks.", True, False),
    ("4.6a", 2, "Reaction Rates", "Diagram-based",
     "Draw Maxwell-Boltzmann curve T2 (lower temp) on the graph.",
     True, [], "curve shifted left/lower peak at lower temp", ["T2 curve (2)"], "Two marks; on the graph.", True, False),
    ("4.6b", 2, "Reaction Rates", "Diagram-based",
     "Draw curve T3 (increased concentration) on the graph.",
     True, [], "same shape as T1 (conc does not change distribution)", ["T3 curve (2)"], "Two marks; on the graph.", True, False),
    ("4.6c", 2, "Reaction Rates", "Diagram-based",
     "Indicate Ea position at lower temperature T2. Label H.",
     True, [], "H at same Ea position (Ea independent of T)", ["H position (2)"], "Two marks; on the graph.", True, False),
    ("4.6d", 2, "Reaction Rates", "Definition/Explain",
     "Define activation energy.",
     True, [], "minimum energy to start a reaction (or to form activated complex)", ["minimum energy (1)", "form activated complex (1)"], "Two marks.", True, False),
    ("4.6e", 2, "Reaction Rates", "Definition/Explain",
     "Define catalyst.",
     True, [], "substance that increases rate but is unchanged at the end", ["increases rate (1)", "unchanged (1)"], "Two marks.", True, False),
    ("4.6f", 2, "Reaction Rates", "Diagram-based",
     "Indicate Ea position when a catalyst is used. Label C.",
     True, [], "C at a lower Ea position", ["C position (2)"], "Two marks; on the graph.", True, False),
    ("4.6g", 4, "Reaction Rates", "Explanation",
     "Explain how a catalyst speeds the reaction via MB curve + collision theory.",
     False, [], "more particles with Ek >= Ea -> more effective collisions per unit time -> faster rate",
     ["more particles >= Ea (1)", "more effective collisions (1)", "per unit time (1)", "faster rate (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 5: SOLUTIONS (8 marks) ----------------
    ("5.1", 4, "Bonding", "Short Answer",
     "Write dissociation reactions for (NH4)3PO4 and NH4NO3.",
     False, [], "(NH4)3PO4 -> 3NH4+ + PO4 3- ; NH4NO3 -> NH4+ + NO3-",
     ["3NH4+ (1)", "PO4 3- (1)", "NH4+ (1)", "NO3- (1)"], "Four marks.", False, False),
    ("5.2", 4, "Stoichiometry", "Calculation",
     "Beaker A: 250 cm3 0,75 M (NH4)3PO4. Beaker B: 500 ml 20 g NH4NO3. [NH4+] when combined?",
     False, ["n=cV", "c=n/V"], "1,08 mol.dm-3",
     ["A: 0,75x0,25x3=0,5625 (1)", "B: 20/80=0,25 (1)", "c=(0,5625+0,25)/(0,25+0,5) (1)", "=1,08 (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 6: ENERGY AND RATES (thiosulphate) (21 marks) ----------------
    ("6.1a", 2, "Reaction Rates", "Calculation",
     "Priyesh's thiosulphate results: missing average time for 0,50 M (trials 23,5; 24,8; 26,7).",
     False, [], "25,0 s", ["(23,5+24,8+26,7)/3 = 25,0 (2)"], "Two marks.", False, False),
    ("6.1b", 2, "Reaction Rates", "Short Answer",
     "Equation used to calculate the Reaction Rate values.",
     False, [], "Reaction rate = 1 / time (or 1/average time)", ["rate = 1/time (2)"], "Two marks.", False, False),
    ("6.1c", 7, "Reaction Rates", "Diagram-based",
     "Complete graph of concentration vs reaction rate: y-axis scale, plot 5 points, line of best fit.",
     True, [], "linear graph through (0,10)…(0,50,~36) with LOBF", ["y heading (1)", "y scale (1)", "heading (1)", "2nd point (1)", "3rd point (1)", "5th point (1)", "LOBF (1)"], "Seven marks; graph.", True, False),
    ("6.2a", 2, "Reaction Rates", "Diagram-based",
     "Draw the line for a colder day. Label 'Cold'.",
     True, [], "line below the original (lower rates at each conc)", ["Cold line (2)"], "Two marks; on the graph.", True, False),
    ("6.2b", 4, "Reaction Rates", "Explanation",
     "Explain, via collision theory, the effect of a decrease in temperature on rate.",
     False, [], "lower KE -> fewer collisions/s -> fewer effective collisions -> slower rate",
     ["lower KE (1)", "fewer collisions (1)", "fewer effective collisions (1)", "slower rate (1)"], "Four marks.", False, False),
    ("6.3a", 2, "Reaction Rates", "Explanation",
     "Priyesh: why was Experiment 2 time lower than Experiment 1? (volumes doubled)",
     True, [], "looking through greater volume -> more precipitate in line of sight -> cross disappears quicker",
     ["greater volume (1)", "more precipitate in sight (1)"], "Two marks.", True, False),
    ("6.3b", 2, "Reaction Rates", "Short Answer",
     "Write Byron's Experiment 2 time.",
     True, [], "10 s", ["10 s (2)"], "Two marks.", True, False),

    # ---------------- QUESTION 7: QUANTITATIVE CHEMISTRY (Al/Fe extraction) (27 marks) ----------------
    ("7.1", 2, "Stoichiometry", "Short Answer",
     "Formula for aluminium oxide.",
     False, [], "Al2O3", ["Al2O3 (2)"], "Two marks.", False, False),
    ("7.2a", 4, "Stoichiometry", "Calculation",
     "Al2O3 + 2NaOH + 3H2O -> 2NaAl(OH)4. 200 ml 2,0 M NaOH + 12 g H2O. Limiting reagent?",
     False, ["n=cV", "n=m/M"], "NaOH is limiting",
     ["n(NaOH)=0,4 (1)", "n(H2O)=12/18=0,67 (1)", "2:3 ratio -> 0,4 needs 0,6 (1)", "NaOH limiting (1)"], "Four marks.", False, False),
    ("7.2b", 2, "Stoichiometry", "Definition/Explain",
     "Explain 'yield' in a chemical reaction.",
     False, [], "extent of reaction; product obtained vs product possible", ["extent (1)", "actual vs possible (1)"], "Two marks.", False, False),
    ("7.2c", 5, "Stoichiometry", "Calculation",
     "If 45 g NaAl(OH)4 produced, percentage yield? (M=118)",
     False, ["% yield = actual/theoretical x 100"], "95,33%",
     ["theoretical = 0,4 mol x 118 = 47,2 g (1)", "% = 45/47,2 (1)", "x100 (1)", "=95,33% (1)"], "Five marks.", False, False),
    ("7.3a", 3, "Stoichiometry", "Calculation",
     "Fe2O3 + 3CO -> 2Fe + 3CO2. 1 kg Fe, 100% efficient, CO excess. Fe2O3 required?",
     False, ["n=m/M"], "8,93 mol (= 1428,8 g)",
     ["n(Fe)=1000/56=17,86 (1)", "2:1 -> 8,93 mol Fe2O3 (1)", "m=8,93x160 (1)"], "Three marks.", False, False),
    ("7.3b", 4, "Stoichiometry", "Calculation",
     "Number of iron atoms required for 1 kg Fe.",
     False, ["N=n.Na"], "1,075 x 10^25 Fe atoms",
     ["n(Fe2O3)=8,93 (1)", "x 6,02e23 units (1)", "x 2 Fe atoms (1)", "=1,075e25 (1)"], "Four marks.", False, False),
    ("7.3c", 3, "Stoichiometry", "Calculation",
     "Volume of CO2 produced at STP.",
     False, ["V=n.Vm"], "600 dm3",
     ["n(CO2)=26,79 mol (1)", "V=26,79x22,4 (1)", "=600 dm3 (1)"], "Three marks.", False, False),
    ("7.3d", 4, "Stoichiometry", "Calculation",
     "Mass of Fe2O3 required if only 70% efficient (still 1 kg Fe).",
     False, ["m=nM"], "2041,14 g",
     ["100% mass = 1428,8 g (1)", "mass x 0,7 = 1428,8 (1)", "mass = 2041,14 g (1)"], "Three/four marks.", False, False),

    # ---------------- QUESTION 8: QUANTITATIVE CHEMISTRY (hydrated Na2CO3) (17 marks) ----------------
    ("8.1", 2, "Stoichiometry", "Definition/Explain",
     "Explain 'water of crystallization'.",
     False, [], "water associated with crystal formation (in the crystal framework)", ["associated with crystal (1)", "in framework (1)"], "Two marks.", False, False),
    ("8.2", 2, "Stoichiometry", "Definition/Explain",
     "Explain the 'x' in Na2CO3.xH2O.",
     False, [], "number of water molecules per formula unit of the salt", ["number of water molecules (1)", "per formula unit (1)"], "Two marks.", False, False),
    ("8.3", 1, "Stoichiometry", "Short Answer",
     "A solution of known concentration is called a...?",
     False, [], "standard solution", ["standard solution (1)"], "One mark.", False, False),
    ("8.4", 3, "Stoichiometry", "Calculation",
     "Volume of water to add to 200 ml 10 M HCl to make 2 M HCl.",
     False, ["c1v1=c2v2"], "800 cm3 (0,8 dm3)",
     ["10x200 = 2xv2 (1)", "v2 = 1000 ml (1)", "add 1000-200 = 800 ml (1)"], "Three marks.", False, False),
    ("8.5", 3, "Stoichiometry", "Calculation",
     "23,5 ml 2 M HCl reacted. Moles of dehydrated Na2CO3 that reacted (1:2).",
     False, ["n=cV"], "0,0235 mol",
     ["n(HCl)=2x0,0235=0,047 (1)", "1:2 ratio (1)", "n(Na2CO3)=0,0235 (1)"], "Three marks.", False, False),
    ("8.6", 3, "Stoichiometry", "Calculation",
     "Mass of hydrated Na2CO3 = 5 g; dehydrated = 2,491 g. Moles of water in crystallisation.",
     False, ["n=m/M"], "0,139 mol",
     ["water = 5-2,491 = 2,509 g (1)", "n=2,509/18 (1)", "=0,139 (1)"], "Three marks.", False, False),
    ("8.7", 3, "Stoichiometry", "Calculation",
     "Hence determine x in Na2CO3.xH2O.",
     False, [], "x = 6",
     ["ratio H2O:Na2CO3 = 0,139:0,0235 (1)", "= 5,93:1 (1)", "x=6 (whole number) (1)"], "Three marks.", False, False),
]
