"""Pass 1 evidence table — Grade 11 Chemistry Mid-Year Exam, 22 July 2022.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/Gr11-Chemistry-June_Exam-QP-2022.pdf   (165 marks, Mr Hilder)
Memo:   data/organized/chemistry/Gr11-Chemistry-June_Exam-MG-2022.pdf   (165 marks, Mr Hilder)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "CHE-2022-JUN",
    "paper_path": "data/organized/chemistry/Gr11-Chemistry-June_Exam-QP-2022.pdf",
    "memo_path": "data/organized/chemistry/Gr11-Chemistry-June_Exam-MG-2022.pdf",
    "year": 2022,
    "exam_date": "22 July 2022",
    "exam_period": "june",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 165,
    "examiner": "Mr Hilder",
    "moderator": "Mr McCoy",
    "duration_stated": "150 minutes",
    "fidelity_rung": "A",
    "notes": (
        "School-set mid-year Chemistry paper. Energy-profile (Q6.2), Maxwell-Boltzmann "
        "(implicit) and graph-sketch sub-parts are diagram-based."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (16 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Chemical formula for magnesium phosphate. A Mg(PO4)2 / B Mg2(PO4)3 / C MgPO4 / D Mg3(PO4)2",
     False, [], "D", ["Mg3(PO4)2"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Matter & Materials", "Multiple Choice",
     "Correct exponent for the prefix micro. A 10^-9 / B 10^-6 / C 10^-3 / D 10^-2",
     False, [], "B", ["micro = 10^-6"], "Memo gives the correct option only.", False, False),
    ("1.3", 2, "Atomic Structure", "Multiple Choice",
     "Number of neutrons in C-14. A 6 / B 7 / C 8 / D 14",
     False, [], "C", ["14-6=8"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Bonding", "Multiple Choice",
     "Which has a tetrahedral shape? A H3O+ / B NH4+ / C CO2 / D AlCl3",
     False, [], "B", ["NH4+ tetrahedral"], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Reaction Rates", "Multiple Choice",
     "Maxwell-Boltzmann curve Z (F2). Which change gives curve Y? A [F2] only / B T only / "
     "C [F2] and T / D catalyst",
     True, [], "A", ["increase in concentration only"], "Memo gives the correct option only; graph is an image.", True, False),
    ("1.6", 2, "Bonding", "Multiple Choice",
     "Half-reaction Sn4+ + 2e- -> Sn2+ shows the... A oxidation metal ion / B oxidation non-metal ion / "
     "C reduction metal ion / D reduction non-metal ion",
     False, [], "C", ["reduction of a metal ion"], "Memo gives the correct option only.", False, False),
    ("1.7", 2, "Stoichiometry", "Multiple Choice",
     "20 g of calcium, oxygen gas, or sodium fluoride: greatest number of moles? A calcium / B oxygen / C NaF / D all same",
     False, [], "B", ["calcium has the smallest molar mass"], "Memo gives the correct option only.", False, False),
    ("1.8", 2, "Stoichiometry", "Multiple Choice",
     "Atoms in 6,4 mol H2SO4. A 1,16e24 / B 3,84e24 / C 4,21e24 / D 2,70e25",
     False, [], "D", ["6,4 x 7 x 6,02e23 = 2,70e25"], "Memo gives the correct option only.", False, False),

    # ---------------- QUESTION 2: BONDING (HCN) (19 marks) ----------------
    ("2.1", 2, "Bonding", "Definition/Explain",
     "Define the term chemical bond.",
     False, [], "a bond which occurs between atoms within molecules", ["between atoms within molecules (2)"], "Two-mark definition.", False, False),
    ("2.2", 2, "Bonding", "Diagram-based",
     "Draw the Lewis structures for HCN.",
     False, [], "H-C≡N with lone pairs on N (and C if needed)", ["correct Lewis (2)"], "Two marks; Lewis diagram.", False, False),
    ("2.3", 1, "Bonding", "Short Answer",
     "What is the shape of the HCN molecule?",
     False, [], "linear", ["linear (1)"], "One mark.", False, False),
    ("2.4", 2, "Bonding", "Calculation",
     "Calculate the electronegativity difference for the CN bond (EN: C=2,5, N=3,0).",
     False, [], "0,5", ["END = N - C = 3 - 2,5 (1)", "= 0,5 (1)"], "Two marks.", False, False),
    ("2.5", 1, "Bonding", "Short Answer",
     "Is HCN POLAR or NON-POLAR? (circle)",
     False, [], "POLAR", ["POLAR (1)"], "One mark.", False, False),
    ("2.6", 2, "Bonding", "Explanation",
     "Explain why the bond energy of CN is more than CH (CH 413, CN 890 kJ/mol).",
     False, [], "CN is a triple bond, CH a single bond; triple bonds need more energy to break",
     ["CN triple bond (1)", "CH single bond (1)"], "Two marks.", False, False),
    ("2.7", 2, "Bonding", "Explanation",
     "Explain the difference in bond length of CH vs CN (CH 0,109 nm, CN 0,116 nm).",
     False, [], "H is a smaller atom (1 shell) than N (2 shells); C can be closer to H, so C-H shorter",
     ["H smaller / fewer shells (1)", "C closer to H (1)"], "Two marks.", False, False),
    ("2.8", 1, "Intermolecular Forces", "Short Answer",
     "Will HCN be soluble in water? (circle YES/NO)",
     False, [], "YES", ["YES (1)"], "One mark.", False, False),
    ("2.9", 2, "Intermolecular Forces", "Explanation",
     "Explain 2.8.",
     False, [], "HCN is polar, water is polar; like dissolves like", ["HCN polar (1)", "like dissolves like (1)"], "Two marks.", False, False),
    ("2.10.1", 2, "Bonding", "Diagram-based",
     "Graph of Ep vs internuclear distance for C-H. What do labelled points X and Y represent?",
     True, [], "X = bond energy; Y = bond length", ["X bond energy (1)", "Y bond length (1)"], "Two marks; graph is an image.", True, False),
    ("2.10.2", 2, "Bonding", "Diagram-based",
     "Draw another curve for carbon and nitrogen moving towards each other.",
     True, [], "vertex lower on y-axis and further right on x-axis", ["lower vertex (1)", "further right (1)"], "Two marks; on the graph.", True, False),

    # ---------------- QUESTION 3: INTERMOLECULAR FORCES (12 marks) ----------------
    ("3.1.1", 4, "Intermolecular Forces", "Explanation",
     "O2 + 2H2 -> 2H2O. Bpt: H2 -252,9, O2 -195,8, H2O 100. Explain the Bpt difference between H2O and O2 via IMFs.",
     False, [], "H2O has H-bonds (strong), O2 only London; more energy to overcome H-bonds -> H2O higher Bpt",
     ["O2 London (1)", "H2O H-bond (1)", "H-bond stronger (1)", "H2O higher Bpt (1)"], "Four marks.", False, False),
    ("3.1.2", 4, "Intermolecular Forces", "Explanation",
     "Explain why H2 evaporates faster than O2 (refer to IMF type and strength).",
     False, [], "both non-polar with London; O2 larger e-cloud -> stronger London -> slower evaporate; H2 faster",
     ["both non-polar London (1)", "O2 larger e-cloud (1)", "stronger London in O2 (1)", "H2 evaporates faster (1)"], "Four marks.", False, False),
    ("3.2.1", 2, "Bonding", "Short Answer",
     "HCl added to water gives hydronium. What properties are required for a dative covalent bond to form?",
     False, [], "empty orbital on one atom; lone pair of electrons on the other", ["empty orbital (1)", "lone pair (1)"], "Two marks.", False, False),
    ("3.2.2", 2, "Bonding", "Diagram-based",
     "Draw a Lewis diagram of the hydronium ion (H3O+).",
     False, [], "[H3O]+ with dative bond from O to H", ["3 H and O (1)", "dative symbol, + charge (1)"], "Two marks; Lewis diagram.", False, False),

    # ---------------- QUESTION 4: REDOX / IONIC (11 marks) ----------------
    ("4.1.1", 1, "Bonding", "Definition/Explain",
     "Calcium + chlorine -> calcium chloride. Define reducing agent.",
     False, [], "a substance that donates electrons", ["donates electrons (1)"], "One mark.", False, False),
    ("4.1.2", 2, "Bonding", "Short Answer",
     "Write the oxidation half reaction for formation of calcium chloride.",
     False, [], "Ca -> Ca2+ + 2e-", ["Ca (1)", "Ca2+ + 2e- (1)"], "Two marks.", False, False),
    ("4.1.3", 3, "Bonding", "Short Answer",
     "Give the net ionic equation for the reaction.",
     False, [], "Ca + Cl2 -> Ca2+ + 2Cl-", ["Ca (1)", "Cl2 (1)", "Ca2+ + 2Cl- balanced (1)"], "Three marks.", False, False),
    ("4.2.1", 2, "Bonding", "Explanation",
     "Use diagram A (sodium metal) to explain why sodium conducts electricity.",
     True, [], "it has delocalised electrons able to flow (sea of electrons moves past positive kernels)",
     ["delocalised electrons (1)", "able to flow (1)"], "Two marks; diagram is an image.", True, False),
    ("4.2.2", 2, "Bonding", "Explanation",
     "Solid sodium chloride does not conduct. Explain with reference to the sub-atomic particle/s.",
     False, [], "ions are fixed in the crystal lattice by strong ionic bonds; not free to move",
     ["ions fixed in lattice (1)", "not free to move (1)"], "Two marks.", False, False),
    ("4.2.3", 1, "Bonding", "Short Answer",
     "Name a state in which sodium chloride is electrically conductive.",
     False, [], "molten (liquid) or aqueous", ["molten/aqueous (1)"], "One mark.", False, False),

    # ---------------- QUESTION 5: REACTION RATE (Mg + CuSO4) (26 marks) ----------------
    ("5.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Mg + CuSO4 -> MgSO4 + Cu, dH<0. Define exothermic reaction.",
     False, [], "a reaction that converts chemical potential energy into thermal energy", ["chem PE -> thermal (2)"], "Two marks.", False, False),
    ("5.2", 2, "Reaction Rates", "Short Answer",
     "Identify the dependent variable in the experiment (mass of Mg vs temperature rise).",
     False, [], "temperature (of the solution)", ["temperature (2)"], "Two marks.", False, False),
    ("5.3", 3, "Scientific Skills", "Explanation",
     "Student concluded 2,0 g Mg gave the most accurate results. Comment on validity.",
     False, [], "precise but not accurate — no control to test against",
     ["precise (1)", "not accurate (1)", "no control (1)"], "Three marks.", False, False),
    ("5.4.1", 2, "Scientific Skills", "Diagram-based",
     "Complete the graph: provide axis labels.",
     True, [], "x: mass of Mg (g); y: increase in temperature (C)", ["x label (1)", "y label (1)"], "Two marks; on the graph.", True, False),
    ("5.4.2", 2, "Scientific Skills", "Diagram-based",
     "Provide a suitable scale for the x-axis.",
     True, [], "0-2,5 g in sensible increments", ["suitable x scale (2)"], "Two marks; on the graph.", True, False),
    ("5.4.3", 2, "Scientific Skills", "Diagram-based",
     "Plot the missing values.",
     True, [], "all points plotted correctly", ["points plotted (2)"], "Two marks; plotting.", True, False),
    ("5.4.4", 1, "Scientific Skills", "Diagram-based",
     "Draw a best-fit curve for the data.",
     True, [], "smooth best-fit curve", ["curve of best fit (1)"], "One mark; on the graph.", True, False),
    ("5.5", 2, "Scientific Skills", "Data/Graph Interpretation",
     "Use the graph to find the mass of Mg for a 3 C rise (two dotted lines).",
     True, [], "0,75 g", ["0,75 g (2)"], "Two marks; from the graph.", True, False),
    ("5.6", 2, "Reaction Rates", "Explanation",
     "Why does the temperature rise stay constant for the last three masses (1,5; 2,0; 2,5 g)?",
     False, [], "CuSO4 is used up (limiting) — reaction complete", ["CuSO4 used up (1)", "limiting (1)"], "Two marks.", False, False),
    ("5.7", 3, "Reaction Rates", "Explanation",
     "Explain fully why the temperature rise increased as Mg increased from 0 to 1,5 g.",
     False, [], "more Mg -> more reactions (effective collisions)/s -> more heat released per unit time",
     ["more Mg (1)", "more reactions/collisions (1)", "more heat (1)"], "Three marks.", False, False),
    ("5.8", 2, "Reaction Rates", "Diagram-based",
     "On the graph, show the effect of using Mg GRANULES instead of powder. Label 'Q5.8'.",
     True, [], "less steep curve (lower final rise)", ["less steep curve (2)"], "Two marks; on the graph.", True, False),
    ("5.9", 3, "Reaction Rates", "Explanation",
     "Explain 5.8.",
     False, [], "granules have less surface area -> fewer reactions/s -> slower rate",
     ["less surface area (1)", "fewer reactions/s (1)", "slower rate (1)"], "Three marks.", False, False),

    # ---------------- QUESTION 6: ENERGY PROFILE (Haber) (17 marks) ----------------
    ("6.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "N2 + 3H2 -> 2NH3, dH=-92,4, Ea=242,6. Define activation energy.",
     True, [], "the minimum energy required to start a reaction (or to form the activated complex)",
     ["minimum energy (1)", "to start reaction (1)"], "Two marks.", True, False),
    ("6.2", 5, "Energy & Chemical Change", "Diagram-based",
     "Sketch the energy profile; label activation energy, heat of reaction, activated complex.",
     True, [], "exothermic curve (products lower than reactants by 92,4); EA, dH, activated complex labelled",
     ["exothermic shape (1)", "EA labelled (1)", "dH labelled (1)", "activated complex labelled (1)", "correct values (1)"],
     "Five marks; on the graph (max 3 if endothermic drawn).", True, False),
    ("6.3", 1, "Energy & Chemical Change", "Short Answer",
     "Is energy RELEASED or ABSORBED when bonds within ammonia are formed? (circle)",
     True, [], "RELEASED", ["RELEASED (1)"], "One mark.", True, False),
    ("6.4", 2, "Energy & Chemical Change", "Calculation",
     "Calculate the activation energy for the reverse reaction.",
     True, [], "335 kJ.mol-1", ["242,6 - (-92,4) (1)", "= 335 (1)"], "Two marks.", True, False),
    ("6.5", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define catalyst.",
     False, [], "a substance that increases the rate but remains unchanged at the end", ["increases rate (1)", "unchanged (1)"], "Two marks.", False, False),
    ("6.6", 2, "Energy & Chemical Change", "Explanation",
     "Learner: 'A catalyst lowers Ea which results in more collisions per second.' Explain why incorrect.",
     False, [], "the actual Ea of the reaction does not change; a catalyst provides an alternative path of lower Ea",
     ["actual Ea unchanged (1)", "alternative path lower Ea (1)"], "Two marks.", False, False),
    ("6.7", 3, "Energy & Chemical Change", "Explanation",
     "Pt catalyst Ea 70,6; Os catalyst 104,6. Which is most effective? Explain.",
     True, [], "platinum — lower Ea -> higher rate (less energy to reach activated complex)",
     ["Pt (1)", "lower Ea -> higher rate (1)", "less energy to activated complex (1)"], "Three marks.", True, False),

    # ---------------- QUESTION 7: REACTION RATE (Zn + HCl) (12 marks) ----------------
    ("7.1", 2, "Reaction Rates", "Definition/Explain",
     "2HCl + Zn -> ZnCl2 + H2. Define reaction rate.",
     False, [], "change in concentration per unit time of a reactant or product", ["change in concentration (1)", "per unit time (1)"], "Two marks.", False, False),
    ("7.2", 3, "Reaction Rates", "Calculation",
     "Calculate average rate for Trial 1 between 0 and 3 minutes (45 cm3 produced).",
     True, [], "15 cm3.min-1 (or 0,25 cm3.s-1)", ["rate = quantity/time (1)", "= 45/3 (1)", "= 15 cm3.min-1 (1)"], "Three marks; from the graph.", True, False),
    ("7.3", 2, "Reaction Rates", "Explanation",
     "Why does the gradient of Trial 1 decrease over time?",
     True, [], "[reactants] decreases as they are used up, so rate decreases", ["[reactants] decreases (1)", "rate decreases (1)"], "Two marks.", True, False),
    ("7.4", 1, "Reaction Rates", "Short Answer",
     "Did [HCl] INCREASE or DECREASE in Trial 2? (circle)",
     True, [], "DECREASE", ["DECREASE (1)"], "One mark.", True, False),
    ("7.5", 4, "Reaction Rates", "Explanation",
     "Explain 7.4 via collision theory.",
     False, [], "lower [HCl] -> fewer particles/volume -> fewer collisions/s -> fewer effective collisions -> slower rate",
     ["less particles/volume (1)", "fewer collisions/s (1)", "fewer effective collisions (1)", "slower rate (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 8: STOICHIOMETRY (antacid) (13 marks) ----------------
    ("8.1", 1, "Stoichiometry", "Short Answer",
     "3NaHCO3 + H3C6H5O7 -> Na3C6H5O7 + 3CO2 + 3H2O. Formula of the substance that causes the fizz?",
     False, [], "CO2", ["CO2 (1)"], "One mark.", False, False),
    ("8.2", 2, "Stoichiometry", "Definition/Explain",
     "Define molar mass.",
     False, [], "the mass in grams of one mole of a substance", ["mass of 1 mol in grams (2)"], "Two marks.", False, False),
    ("8.3", 3, "Stoichiometry", "Calculation",
     "Antacid has 3,36 g NaHCO3. Moles of NaHCO3? (M=84)",
     False, ["n=m/M"], "0,04 mol", ["M=84 (1)", "n=3,36/84 (1)", "=0,04 (1)"], "Three marks.", False, False),
    ("8.4", 4, "Stoichiometry", "Calculation",
     "Determine the limiting reagent (1,8 g citric acid, M=192).",
     False, ["n=m/M"], "citric acid is limiting",
     ["n(acid)=1,8/192=0,009 (1)", "ratio 3:1 (1)", "0,04 NaHCO3 needs 0,013 acid (1)", "acid insufficient -> limiting (1)"], "Four marks.", False, False),
    ("8.5", 3, "Stoichiometry", "Calculation",
     "Calculate the mass of the reactant in excess.",
     False, ["m=nM"], "1,092 g (or 0,84 g if rounded)",
     ["excess = 0,04 - 0,027 = 0,013 mol (1)", "m = 0,013 x 84 (1)", "= 1,092 g (1)"], "Three marks.", False, False),

    # ---------------- QUESTION 9: SOLUTIONS / STANDARD SOLUTION (19 marks) ----------------
    ("9.1", 2, "Stoichiometry", "Definition/Explain",
     "Define concentration.",
     False, [], "amount of solute per unit volume of solution", ["amount solute (1)", "per unit volume (1)"], "Two marks.", False, False),
    ("9.2", 3, "Stoichiometry", "Calculation",
     "8 g Na2S2O3 in 500 cm3. Concentration? (M=158)",
     False, ["c=m/(MV)"], "0,1 mol.dm-3",
     ["V=0,5 dm3 (1)", "c=8/(158x0,5) (1)", "=0,1 (1)"], "Three marks.", False, False),
    ("9.3.1", 1, "Stoichiometry", "Short Answer",
     "Why are the given solutions standard solutions?",
     False, [], "they have known concentrations", ["known concentrations (1)"], "One mark.", False, False),
    ("9.3.2", 2, "Stoichiometry", "Definition/Explain",
     "Define solvent.",
     False, [], "the substance in which another is dissolved, forming a solution", ["dissolving substance (1)", "forming solution (1)"], "Two marks.", False, False),
    ("9.3.3", 1, "Stoichiometry", "Short Answer",
     "Identify the solvent used.",
     False, [], "water", ["water (1)"], "One mark.", False, False),
    ("9.3.4", 4, "Stoichiometry", "Short Answer",
     "Give the method for making a standard solution (four bullets).",
     False, [], "measure precise mass; transfer to beaker; rinse into volumetric flask; fill to mark",
     ["measure mass (1)", "transfer to beaker (1)", "rinse into flask (1)", "fill to line (1)"], "Four marks.", False, False),
    ("9.3.5", 2, "Bonding", "Short Answer",
     "Write the balanced dissociation of ammonium carbonate.",
     False, [], "(NH4)2CO3 + H2O -> 2NH4+ + CO3 2-", ["2NH4+ (1)", "CO3 2- (1)"], "Two marks.", False, False),
    ("9.3.6", 4, "Stoichiometry", "Calculation",
     "Solution A (0,2 M NH4OH, 0,25 dm3) + B (0,3 M (NH4)2CO3, 0,5 dm3). New [NH4+]?",
     False, ["n=cV", "c=n/V"], "0,47 mol.dm-3",
     ["n(NH4OH)=0,05 (1)", "n((NH4)2CO3)=0,15 x2=0,3 (1)", "c=(0,05+0,3)/(0,25+0,5) (1)", "=0,47 (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 10: STOICHIOMETRY (Na2CO3/HCl) (20 marks) ----------------
    ("10.1", 3, "Stoichiometry", "Short Answer",
     "Write a balanced equation for Na2CO3 + HCl with phase symbols.",
     False, [], "Na2CO3(s) + 2HCl(aq) -> 2NaCl(aq) + CO2(g) + H2O(l)",
     ["Na2CO3 + 2HCl (1)", "-> 2NaCl + CO2 + H2O (1)", "phases (1)"], "Three marks.", False, False),
    ("10.2.1", 3, "Stoichiometry", "Calculation",
     "15,9 g Na2CO3 reacts completely with excess HCl. Initial moles of Na2CO3? (M=106)",
     False, ["n=m/M"], "0,15 mol", ["n=15,9/106 (1)", "=0,15 (1)"], "Three marks.", False, False),
    ("10.2.2", 4, "Stoichiometry", "Calculation",
     "Theoretical volume of CO2 produced (at STP).",
     False, ["n=V/Vm"], "3,36 dm3",
     ["1:1 ratio (1)", "n(CO2)=0,15 (1)", "V=0,15x22,4 (1)", "=3,36 dm3 (1)"], "Four marks.", False, False),
    ("10.2.3", 5, "Stoichiometry", "Calculation",
     "Only 15 g NaCl produced. Percentage yield?",
     False, ["% yield = actual/theoretical x 100"], "85,47%",
     ["theoretical NaCl = 0,3 mol = 17,55 g (1)", "% = 15/17,55 (1)", "x100 (1)", "=85,47% (1)"], "Five marks.", False, False),
    ("10.3", 5, "Stoichiometry", "Calculation",
     "14,2 g Na2CO3.xH2O heated; 5,3 g solid remained. Moles of water of crystallisation? (M Na2CO3=106)",
     False, ["n=m/M"], "Na2CO3.10H2O (≈10 water molecules)",
     ["water = 14,2-5,3 = 8,9 g (1)", "n(H2O)=8,9/18=0,49 (1)", "n(Na2CO3)=5,3/106=0,05 (1)", "ratio 9,8≈10 (1)", "Na2CO3.10H2O (1)"],
     "Five marks; memo rounds to x=10.", False, False),
]
