"""Pass 1 evidence table — Grade 11 Physical Sciences Paper 2 (Chemistry), 22 November 2021.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/PS11 Chemistry November Exam 2021 QP (1).pdf  (200 marks, Mrs Govender)
Memo:   data/organized/chemistry/PS 11 Chemistry NOVEMBER 2021 MG.pdf        (200 marks, Mrs Govender)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)

NOTE: "Organic Chemistry" is used as a topic (see 2020 module note) — it is a
documented extension to the TWO_PASS_PROMPTS chemistry topic list.
"""

PAPER = {
    "paper_key": "CHE-2021-NOV",
    "paper_path": "data/organized/chemistry/PS11 Chemistry November Exam 2021 QP (1).pdf",
    "memo_path": "data/organized/chemistry/PS 11 Chemistry NOVEMBER 2021 MG.pdf",
    "year": 2021,
    "exam_date": "22 November 2021",
    "exam_period": "nov",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 200,
    "examiner": "Mrs Govender",
    "moderator": "Mr du Toit / Mr McCoy",
    "duration_stated": "3 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set November Paper 2. Energy-profile (Q4.2) and several structure-labelling "
        "sub-parts are diagram-based; the memo prints no text for them, so they are recorded "
        "as needs_visual. 1.6 MCQ: memo marks D, though (NH4)2SO4 stoichiometry gives 15 atoms "
        "(option C) — recorded as the memo states, with the discrepancy flagged."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (20 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Chemical formula for sodium sulphite. A NaSO3 / B Na2SO3 / C NaSO4 / D Na2S",
     False, [], "B", ["Na2SO3"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Bonding", "Multiple Choice",
     "Which best describes the particles and electron involvement in chemical bonding? (diagram)",
     True, [], "B", ["describes particles and electrons in bonding"], "Memo gives the correct option only.", True, False),
    ("1.3", 2, "Bonding", "Multiple Choice",
     "Which conducts electricity as a SOLID? A diamond / B graphite / C dry ice / D NaCl",
     False, [], "B", ["graphite (delocalised electrons in solid)"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Energy & Chemical Change", "Multiple Choice",
     "Best explanation of 'heat-of-reaction'? A chem PE -> thermal / B net change kinetic energy / "
     "C thermal -> chem PE / D net change chem PE of system",
     False, [], "D", ["net change in chemical potential energy"], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Bonding", "Multiple Choice",
     "Which contains the MOST polar covalent bonds? A HF / B CH4 / C SO2 / D SI2",
     False, [], "A", ["HF (largest electronegativity difference)"], "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Stoichiometry", "Multiple Choice",
     "How many atoms in 1 mol (NH4)2SO4? A 6,02e23 / B 5,42e24 / C 9,03e24 / D 8,43e24",
     False, [], "D", ["memo marks D (8,43e24)"],
     "Memo marks D; stoichiometry gives 15 atoms/mol -> 9,03e24 (C). Possible memo error, recorded as given.", False, False),
    ("1.7", 2, "Reaction Rates", "Multiple Choice",
     "Maxwell-Boltzmann curves at T1 and T2. Which statement is INCORRECT? "
     "A T1<T2 / B shaded area A = particles able to react at T1 / C avg KE at T1 > T2 / D rate at T1 < T2",
     True, [], "C", ["C is incorrect (T1<T2 so avg KE lower)"], "Memo gives the correct option only; graph is an image.", True, False),
    ("1.8", 2, "Reaction Rates", "Multiple Choice",
     "Zn + 2HCl -> ZnCl2 + H2. Best description of reaction rate? A time to use up reactants / "
     "B decrease in [Zn]/time / C time for one reactant / D increase in [ZnCl2]/time",
     False, [], "D", ["increase in product concentration per unit time"], "Memo gives the correct option only.", False, False),
    ("1.9", 2, "Organic Chemistry", "Multiple Choice",
     "IUPAC name of the molecule shown (a chloro-methyl pentadiene). "
     "A 3-chloro-4-methylpenta-1,4-diene / B 2-methyl-3-chloro-1,4-pentene / "
     "C 3-chloro-2-methylpenta-1,4-diene / D 2-methyl-3-chloropenta-1,4-diene",
     True, [], "C", ["3-chloro-2-methylpenta-1,4-diene"], "Memo gives the correct option only; structure is an image.", True, False),
    ("1.10", 2, "Organic Chemistry", "Multiple Choice",
     "Which reaction will NOT take place with an alkene? A hydration / B hydrogenation / C combustion / D dehydration",
     False, [], "D", ["dehydration (alkenes don't dehydrate)"], "Memo gives the correct option only.", False, False),

    # ---------------- QUESTION 2: BONDING / INTERMOLECULAR FORCES (23 marks) ----------------
    ("2.1.1", 2, "Bonding", "Explanation",
     "Melting points of Li2O, SnO2, SiO2. Explain why Li2O does not conduct electricity as a solid.",
     False, [], "solid Li2O has no free ions (ions fixed in the crystal lattice) to carry current",
     ["no free ions (1)", "ions fixed in lattice (1)"], "Two marks.", False, False),
    ("2.1.2a", 1, "Bonding", "Short Answer",
     "Lithium loses one electron to form Li+ when Li2O forms. Name the process.",
     False, [], "oxidation", ["oxidation (1)"], "One mark.", False, False),
    ("2.1.2b", 2, "Bonding", "Short Answer",
     "Write an equation to show the process (lithium losing an electron).",
     False, [], "Li -> Li+ + e-", ["Li (1)", "Li+ + e- (1)"], "Two marks.", False, False),
    ("2.1.3", 1, "Bonding", "Short Answer",
     "Name the intramolecular bond in SiO2.",
     False, [], "covalent bond", ["covalent (1)"], "One mark.", False, False),
    ("2.1.4", 3, "Bonding", "Explanation",
     "Explain why SiO2 has a higher melting point than SnO2 and Li2O.",
     False, [], "SiO2 is a giant covalent lattice with many strong covalent bonds; more energy to break than the ionic bonds in SnO2/Li2O",
     ["giant covalent lattice (1)", "many strong covalent bonds (1)", "more energy than ionic bonds (1)"], "Three marks.", False, False),
    ("2.2.1", 2, "Bonding", "Definition/Explain",
     "Graph of hydrogen-halide boiling points. Define an intramolecular bond.",
     True, [], "a bond between atoms within molecules", ["between atoms (1)", "within molecules (1)"], "Two marks; graph is an image.", True, False),
    ("2.2.2", 2, "Bonding", "Short Answer",
     "Use electronegativity differences to identify the type of intramolecular bond in HCl.",
     True, [], "polar covalent bond (END = 3,0 - 2,1 = 0,9)",
     ["END = 3,0-2,1 = 0,9 (1)", "polar covalent (1)"], "Two marks.", True, False),
    ("2.2.3", 1, "Intermolecular Forces", "Short Answer",
     "Name the specific IMF found in HF but not HCl, HBr or HI.",
     False, [], "hydrogen bond force", ["hydrogen bond (1)"], "One mark.", False, False),
    ("2.2.4", 3, "Intermolecular Forces", "Explanation",
     "Explain the origin of the hydrogen bond force.",
     False, [], "small highly electronegative atom attracts the bonding pair; a naked proton is exposed and attracted to a lone pair on another small electronegative atom",
     ["small electronegative atom attracts pair (1)", "exposed proton (1)", "attracted to lone pair (1)"], "Three marks.", False, False),
    ("2.2.5", 2, "Bonding", "Diagram-based",
     "Draw the Lewis diagram for one HCl molecule.",
     False, [], "H-Cl with three lone pairs on Cl",
     ["Lewis structure (2)"], "Two marks; drawing required.", False, False),
    ("2.2.6", 1, "Bonding", "Diagram-based",
     "Indicate the slightly + and slightly - atoms on the HCl Lewis diagram.",
     False, [], "H is d+; Cl is d-", ["H d+ (1)", "Cl d- (1)"], "One mark; on the diagram.", False, False),
    ("2.2.7", 3, "Intermolecular Forces", "Explanation",
     "Explain the difference in boiling point between HBr and HI via their IMFs.",
     False, [], "both have dipole-dipole + London; HI is larger/more electrons -> larger temporary dipole -> higher Bpt",
     ["both dipole-dipole + London (1)", "HI larger/more electrons (1)", "larger temporary dipole -> higher Bpt (1)"], "Three marks.", False, False),

    # ---------------- QUESTION 3: METALLIC + DATIVE BONDING (12 marks) ----------------
    ("3.1.1", 2, "Bonding", "Definition/Explain",
     "Metallic lattice for Na and Mg. Define metallic bonding.",
     True, [], "bonding between a positive kernel and a sea of delocalised electrons",
     ["positive kernel (1)", "sea of delocalised electrons (1)"], "Two marks; lattice diagrams are images.", True, False),
    ("3.1.2", 2, "Bonding", "Explanation",
     "Explain what is meant by a positive kernel.",
     True, [], "the nucleus and core electrons", ["nucleus (1)", "core electrons (1)"], "Two marks.", True, False),
    ("3.1.3", 1, "Bonding", "Short Answer",
     "Provide a label for X in the diagram.",
     True, [], "delocalised electrons", ["delocalised electrons (1)"], "One mark.", True, False),
    ("3.1.4", 2, "Bonding", "Explanation",
     "Use the diagrams to explain why the metallic bond in Mg is stronger than in Na.",
     True, [], "Mg has a bigger charge (+2) -> greater attraction between nucleus and electron cloud",
     ["Mg charge +2 (1)", "greater attraction (1)"], "Two marks.", True, False),
    ("3.2.1", 2, "Bonding", "Short Answer",
     "Two requirements for dative covalent bonding (in SO3).",
     True, [], "an empty orbital; and a lone pair of electrons",
     ["empty orbital (1)", "lone pair of electrons (1)"], "Two marks.", True, False),
    ("3.2.2a", 1, "Bonding", "Diagram-based",
     "Label the dative bond on the SO3 diagram (answer sheet).",
     True, [], "dative bond labelled", ["dative bond (1)"], "One mark; on the diagram.", True, False),
    ("3.2.2b", 1, "Bonding", "Diagram-based",
     "Label the sigma bond on the SO3 diagram (answer sheet).",
     True, [], "sigma bond labelled", ["sigma bond (1)"], "One mark; on the diagram.", True, False),
    ("3.2.2c", 1, "Bonding", "Diagram-based",
     "Label the pi bond on the SO3 diagram (answer sheet).",
     True, [], "pi bond labelled", ["pi bond (1)"], "One mark; on the diagram.", True, False),

    # ---------------- QUESTION 4: ENERGY PROFILE (25 marks) ----------------
    ("4.1", 2, "Energy & Chemical Change", "Short Answer",
     "CaCO3 + 2HCl -> CaCl2 + CO2 + H2O. Provide a label for the y axis of the energy profile.",
     True, [], "Potential Energy (kJ)", ["Potential Energy (1)", "kJ (1)"], "Two marks; profile is an image.", True, False),
    ("4.2", 5, "Energy & Chemical Change", "Diagram-based",
     "The profile is labelled i-v. Identify each energy on the profile (answer sheet).",
     True, [], "unresolved (memo prints blank; standard labels: i energy of reactants, ii activation energy, iii energy released, iv energy of products, v reaction coordinate)",
     [], "Memo leaves this blank; profile is an image.", True, False),
    ("4.3", 2, "Energy & Chemical Change", "Explanation",
     "Using collision theory, explain why the reaction must gain potential energy between A and B.",
     True, [], "only particles with Ek >= Ea (equal to B) are effective; energy must be gained to reach the activated complex",
     ["particles need Ek >= Ea (1)", "to reach B/activated complex (1)"], "Two marks.", True, False),
    ("4.4", 2, "Energy & Chemical Change", "Short Answer",
     "Name the position labelled B and what significant process occurs there.",
     True, [], "activated complex; old bonds break and new bonds form",
     ["activated complex (1)", "bonds break and form (1)"], "Two marks.", True, False),
    ("4.5", 3, "Energy & Chemical Change", "Explanation",
     "Does the graph represent exothermic or endothermic? Explain.",
     True, [], "exothermic — more thermal energy released than absorbed (heat of reaction negative; Ep > Er)",
     ["exothermic (1)", "more energy released than absorbed (1)", "products lower / dH<0 (1)"], "Three marks.", True, False),
    ("4.6.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Define a catalyst.",
     False, [], "increases the rate of reaction but is unchanged at the end",
     ["increases rate (1)", "unchanged at end (1)"], "Two marks.", False, False),
    ("4.6.2", 2, "Energy & Chemical Change", "Short Answer",
     "With a catalyst, how would the energy at point B change? (INCREASES/DECREASES/REMAINS THE SAME)",
     True, [], "DECREASES", ["DECREASES (2)"], "Two marks.", True, False),
    ("4.6.3", 3, "Energy & Chemical Change", "Explanation",
     "How would a catalyst affect the stability of point B? Explain.",
     True, [], "stability increases — less energy needed to start the reaction, so more stable",
     ["stability increases (1)", "less energy to start (1)", "less energy = more stable (1)"], "Three marks.", True, False),
    ("4.7", 4, "Reaction Rates", "Explanation",
     "HCl concentration increased. Use the Maxwell-Boltzmann curve to explain how this affects rate.",
     True, [], "more particles per volume -> more collisions/s -> more effective collisions/s (shaded area) -> faster rate",
     ["more particles/volume (1)", "more collisions/s (1)", "more effective collisions (1)", "rate increases, relate to graph (1)"],
     "Four marks; must relate to the graph (memo: -2 if no graph reference).", True, False),

    # ---------------- QUESTION 5: STANDARD SOLUTION / IONS (17 marks) ----------------
    ("5.1.1", 2, "Stoichiometry", "Definition/Explain",
     "0,5 mol/dm3 K2SO4 standard solution. Define a standard solution.",
     False, [], "a solution of known concentration", ["known concentration (2)"], "Two marks.", False, False),
    ("5.1.2", 4, "Stoichiometry", "Calculation",
     "Calculate the mass of K2SO4 needed to make 500 cm3 of 0,5 mol/dm3 solution. (M=174)",
     False, ["c=m/(MV)"], "43,5 g",
     ["c = m/(M V) (1)", "0,5 = m/(174 x 0,5) (1)", "m = 0,5x174x0,5 (1)", "= 43,5 g (1)"], "Four marks.", False, False),
    ("5.1.3", 2, "Stoichiometry", "Explanation",
     "Should solid K2SO4 be added before or after distilled water? Explain.",
     False, [], "before — to ensure final volume is exactly 500 cm3, not more",
     ["before (1)", "final volume exactly 500 cm3 (1)"], "Two marks.", False, False),
    ("5.2.1", 4, "Bonding", "Short Answer",
     "0,8 M K2SO4 (600 ml) and 0,3 M KCl (250 ml). Write balanced dissociation equations (no phases).",
     False, [], "K2SO4 -> 2K+ + SO4 2- ; KCl -> K+ + Cl-",
     ["K2SO4 -> 2K+ + SO4 2- (2)", "KCl -> K+ + Cl- (2)"], "Four marks.", False, False),
    ("5.2.2", 5, "Stoichiometry", "Calculation",
     "The two solutions are mixed. What is [K+] in the mixture?",
     False, ["n=cV", "c=n/V"], "1,22 mol.dm-3",
     ["n(K2SO4)=0,8x0,6=0,48 mol (1)", "n(KCl)=0,3x0,25=0,075 mol (1)", "[K+]=2x0,48=0,96 (1)", "C=(0,96+0,075)/(0,6+0,25) (1)", "=1,22 (1)"],
     "Five marks.", False, False),

    # ---------------- QUESTION 6: STOICHIOMETRY / WATER OF CRYSTALLISATION (18 marks) ----------------
    ("6.1", 4, "Stoichiometry", "Explanation",
     "672 dm3 NH3 and 1101,2 dm3 CO2 at STP. Aidan says same amount of substance; Ryan says not. Who is correct, "
     "without calculation?",
     False, [], "Ryan — 1 mol of any gas at STP = 22,4 dm3, so different volumes mean different n",
     ["Ryan (1)", "1 mol gas = 22,4 dm3 at STP (1)", "different volume -> different n (1)", "CO2 has more n (1)"], "Four marks.", False, False),
    ("6.2.1", 4, "Stoichiometry", "Calculation",
     "BaCl2 + 2AgNO3 -> 2AgCl + Ba(NO3)2. 1,39 g BaCl2, 2,69 g AgNO3. Prove BaCl2 is limiting.",
     False, ["n=m/M"], "BaCl2 limiting",
     ["n(BaCl2)=1,39/208,3=0,0067 (1)", "n(AgNO3)=2,69/170=0,0158 (1)", "ratio 1:2 -> need 0,0134 AgNO3 (1)", "AgNO3 in excess -> BaCl2 limiting (1)"],
     "Four marks.", False, False),
    ("6.2.2", 2, "Stoichiometry", "Calculation",
     "What mass of AgCl will be produced?",
     False, ["m=nM"], "1,92 g",
     ["n(AgCl)=0,0134 (1)", "m=0,0134x143,5=1,92 g (1)"], "Two marks.", False, False),
    ("6.2.3", 4, "Stoichiometry", "Calculation",
     "1,80 g AgCl collected. Calculate % yield to nearest whole number.",
     False, ["% yield = actual/theoretical x 100"], "94%",
     ["1,80/1,92 (1)", "x100 (1)", "=93,99% (1)", "=94% (1)"], "Four marks.", False, False),
    ("6.3", 4, "Stoichiometry", "Calculation",
     "Find x in MgSO4.xH2O (Epsom salts): masses give 2,463 g hydrated, 1,203 g anhydrous, 1,260 g water. "
     "Complete: moles MgSO4, moles H2O, ratio, formula.",
     False, ["n=m/M"], "MgSO4.7H2O",
     ["n(MgSO4)=0,01 (1)", "n(H2O)=0,07 (1)", "ratio 1:7 (1)", "MgSO4.7H2O (1)"], "Four marks.", False, False),

    # ---------------- QUESTION 7: REACTION RATE (29 marks) ----------------
    ("7.1", 2, "Reaction Rates", "Explanation",
     "CuCO3 + 2HCl -> CuCl2 + H2O + CO2 (CO2 partially soluble). Why a cotton wool plug at the flask mouth?",
     True, [], "to ensure only CO2 escapes, so rate is measured by the decrease in CO2 concentration",
     ["only CO2 escapes (1)", "rate from CO2 decrease (1)"], "Two marks; apparatus is an image.", True, False),
    ("7.2", 2, "Reaction Rates", "Definition/Explain",
     "Define the rate of the reaction.",
     False, [], "change in concentration per unit time of a reactant or product",
     ["change in concentration (1)", "per unit time (1)"], "Two marks.", False, False),
    ("7.3", 2, "Reaction Rates", "Explanation",
     "Has the reaction gone to completion? Explain.",
     True, [], "No — the graph has not yet levelled off", ["No (1)", "graph not yet levelled (1)"], "Two marks; from the graph.", True, False),
    ("7.4", 2, "Reaction Rates", "Explanation",
     "This is not the most ideal monitoring method. Suggest another and explain how to measure rate.",
     True, [], "use a syringe to collect gas volume per unit time; or measure colour change over time",
     ["syringe collects gas volume/time (1)", "or measure colour change (1)"], "Two marks.", True, False),
    ("7.5", 4, "Reaction Rates", "Calculation",
     "Calculate average rate in mol.s-1 between t=10 s and t=30 s (mass drops 164,73->164,25 g).",
     True, [], "1,36 x 10^-4 mol.s-1",
     ["rate = (164,73-164,25)/(30-10) = 0,006 g.s-1 (1)", "rate = 0,006/44 (1)", "=1,36e-4 mol.s-1 (1)"],
     "Four marks; from the graph/mass.", True, False),
    ("7.6a", 2, "Reaction Rates", "Diagram-based",
     "On the graph, sketch if powdered CuCO3 is used instead of lumps. Label 'a)'.",
     True, [], "steeper, ends sooner (more surface area)", ["steeper (1)", "ends sooner (1)"], "Two marks; on the graph.", True, False),
    ("7.6b", 2, "Reaction Rates", "Diagram-based",
     "On the graph, sketch if acid concentration is decreased. Label 'b)'.",
     True, [], "less steep, lower final volume (slower)", ["less steep (1)", "lower final (1)"], "Two marks; on the graph.", True, False),
    ("7.7.1", 6, "Stoichiometry", "Calculation",
     "1,5 g impure CuCO3 + 75 ml 0,25 M HCl -> 180 cm3 CO2 at STP. Calculate % purity of CuCO3. (M=123,5)",
     False, ["n=V/Vm", "n=m/M", "% purity = pure/impure x 100"], "66%",
     ["n(CO2)=0,18/22,4=0,008 mol (1)", "n(CuCO3)=0,008 (1)", "m=0,008x123,5=0,99 g (1)",
      "% = 0,99/1,5 (1)", "=66% (2)"], "Six marks.", False, False),
    ("7.7.2", 2, "Stoichiometry", "Definition/Explain",
     "Define concentration.",
     False, [], "amount of solute per unit volume of solution", ["amount of solute (1)", "per unit volume (1)"], "Two marks.", False, False),
    ("7.7.3", 5, "Stoichiometry", "Calculation",
     "Determine the new [HCl] after the reaction completes.",
     False, ["n=cV", "c=n/V"], "0,037 mol.dm-3",
     ["n(HCl) initial = 0,075x0,25=0,01875 (1)", "left = 0,01875 - 0,008x2 = 0,00275 (1)", "C=0,00275/0,075 (1)", "=0,037 (1)"],
     "Five marks.", False, False),

    # ---------------- QUESTION 8: ORGANIC CHEMISTRY (24 marks) ----------------
    ("8.1", 4, "Organic Chemistry", "Short Answer",
     "Compounds: B CH2=C(CH3)CH2CH3, E HOCH2CH2CH2OH. Give IUPAC names for B and E.",
     True, [], "B: 3-methylpenta-1,2-diene (memo: penta-1,2-diene); E: propane-1,3-diol",
     ["B name (2)", "E name (2)"], "Four marks; structures are images.", True, False),
    ("8.2.1", 2, "Organic Chemistry", "Definition/Explain",
     "Compounds C and F. Define isomer.",
     False, [], "compounds with the same molecular formula but a different structural formula",
     ["same molecular formula (1)", "different structural formula (1)"], "Two marks.", False, False),
    ("8.2.2", 1, "Organic Chemistry", "Short Answer",
     "Which has the higher boiling point (C or F)?",
     False, [], "C", ["C (1)"], "One mark.", False, False),
    ("8.2.3", 2, "Organic Chemistry", "Explanation",
     "Give a reason for 8.2.2.",
     False, [], "C has a larger surface area and stronger London forces", ["larger surface area (1)", "stronger London forces (1)"], "Two marks.", False, False),
    ("8.3.1", 2, "Organic Chemistry", "Definition/Explain",
     "Bromine water added to B and C. Define unsaturated compound.",
     False, [], "a compound containing at least one C=C double bond (or C-C multiple bond)",
     ["contains double bond (1)", "multiple bond (1)"], "Two marks.", False, False),
    ("8.3.2", 2, "Organic Chemistry", "Short Answer",
     "Which (B or C) would rapidly decolourise bromine water?",
     True, [], "B (B is unsaturated; C is alkane)", ["B (1)"], "Two marks; B is the alkene.", True, False),
    ("8.4.1", 5, "Organic Chemistry", "Diagram-based",
     "A (CH3OH) and D (CH3CH2COOH) undergo condensation. Write the equation with conditions (structural formulae).",
     False, [], "CH3OH + CH3CH2COOH -> CH3CH2COOCH3 + H2O (esterification, conc H2SO4, heat)",
     ["reactants (1)", "products (1)", "balanced (1)", "conditions H2SO4/heat (1)"], "Five marks; esterification.", False, False),
    ("8.4.2", 2, "Organic Chemistry", "Short Answer",
     "Give the name AND molecular formula of the functional isomer of the ester product.",
     False, [], "butanoic acid, C4H8O2", ["butanoic acid (1)", "C4H8O2 (1)"], "Two marks.", False, False),
    ("8.5", 2, "Organic Chemistry", "Definition/Explain",
     "Define homologous series.",
     False, [], "series of similar compounds with the same functional group and general formula, differing by CH2",
     ["same functional group + general formula (1)", "differ by CH2 (1)"], "Two marks.", False, False),
    ("8.6", 1, "Organic Chemistry", "Short Answer",
     "Name the homologous series for compound D (CH3CH2COOH).",
     False, [], "carboxylic acids", ["carboxylic acids (1)"], "One mark.", False, False),
    ("8.7", 1, "Organic Chemistry", "Short Answer",
     "Write the general formula for compound C (an alkane).",
     False, [], "CnH2n+2", ["CnH2n+2 (1)"], "One mark.", False, False),

    # ---------------- QUESTION 9: ORGANIC CHEMISTRY / REACTIONS (32 marks) ----------------
    ("9.1.1", 1, "Organic Chemistry", "Short Answer",
     "9-carbon hydrocarbon -> hexane + compound L (Reaction 1). Identify the GENERAL reaction type.",
     True, [], "elimination", ["elimination (1)"], "One mark.", True, False),
    ("9.1.2", 1, "Organic Chemistry", "Short Answer",
     "Identify the SPECIFIC type of Reaction 1.",
     True, [], "thermal cracking", ["thermal cracking (1)"], "One mark.", True, False),
    ("9.2", 3, "Organic Chemistry", "Calculation",
     "Write the balanced combustion reaction for hexane, identifying substances (i)-(iii) (molecular formulae).",
     False, [], "2C6H14 + 19O2 -> 12CO2 + 14H2O (or C6H14 + 9,5O2 -> 6CO2 + 7H2O)",
     ["reactants (1)", "balanced (1)", "products (1)"], "Three marks.", False, False),
    ("9.3.1", 3, "Organic Chemistry", "Short Answer",
     "Compound K is a structural isomer of hexane. Give an IUPAC name for a possible isomer.",
     False, [], "2-methylpentane (or 2,3-dimethylbutane)", ["2-methyl (1)", "pentane / dimethylbutane (1)", "valid name (1)"], "Three marks.", False, False),
    ("9.3.2", 2, "Organic Chemistry", "Short Answer",
     "Write a condensed structural formula for compound K.",
     False, [], "CH3CH2(CH3)CH2CH2CH3", ["CH3CH2(CH3)CH2CH2CH3 (2)"], "Two marks.", False, False),
    ("9.4", 2, "Organic Chemistry", "Short Answer",
     "Give the IUPAC name for compound L (propene).",
     True, [], "propene", ["propene (2)"], "Two marks.", True, False),
    ("9.5.1", 2, "Organic Chemistry", "Short Answer",
     "Reaction 2 (hexane -> compound L). Identify the SPECIFIC type of reaction.",
     True, [], "hydrohalogenation", ["hydrohalogenation (2)"], "Two marks.", True, False),
    ("9.5.2", 2, "Organic Chemistry", "Short Answer",
     "What specific condition must be met for Reaction 2?",
     False, [], "no water (presence of HX, anhydrous)", ["no water (2)"], "Two marks.", False, False),
    ("9.6.1", 2, "Organic Chemistry", "Short Answer",
     "Reaction 3 produces an alcohol and a solid. Identify the GENERAL reaction type.",
     True, [], "substitution", ["substitution (2)"], "Two marks.", True, False),
    ("9.6.2", 3, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula for alcohol N; circle and name the functional group.",
     True, [], "propan-1-ol (CH3CH2CH2OH); functional group = hydroxyl (-OH)",
     ["structure (1)", "circle OH (1)", "hydroxyl (1)"], "Three marks; structure is an image.", True, False),
    ("9.6.3", 2, "Organic Chemistry", "Short Answer",
     "Identify substance (iv) and solid (v) in Reaction 3 (halogenation of alcohol).",
     False, [], "iv = NaOH or KOH; v = NaCl or KCl", ["iv NaOH/KOH (1)", "v NaCl/KCl (1)"], "Two marks.", False, False),
    ("9.6.4", 2, "Organic Chemistry", "Short Answer",
     "State the conditions required for Reaction 3.",
     False, [], "heat under reflux, dilute alkali", ["heat under reflux (1)", "dilute alkali (1)"], "Two marks.", False, False),
    ("9.7.1", 3, "Organic Chemistry", "Short Answer",
     "Compounds L, M, N. Identify the IMF in each.",
     True, [], "L: London forces; M: dipole-dipole; N: hydrogen bond force",
     ["L London (1)", "M dipole-dipole (1)", "N H-bond (1)"], "Three marks.", True, False),
    ("9.7.2", 2, "Organic Chemistry", "Data/Graph Interpretation",
     "Rank L, M, N in increasing order of boiling points.",
     True, [], "L, M, N", ["L, M, N (2)"], "Two marks.", True, False),
    ("9.7.3", 2, "Organic Chemistry", "Explanation",
     "Explain the highest-boiling compound via IMF strengths.",
     True, [], "N has the strongest force (H-bonding) so most energy needed to overcome for boiling",
     ["N strongest force (1)", "more energy to overcome (1)"], "Two marks.", True, False),
]
