"""Pass 1 evidence table — Grade 11 Chemistry Paper 2, 28 November 2022.

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/chemistry/G11 Nov Chem Exam QPs.pdf          (200 marks, Mr McCoy)
Memo:   data/organized/chemistry/G11 Nov Chem Exam MG.pdf          (200 marks, Mr McCoy)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)

NOTE: 1.6 MCQ: memo marks D (8,43e24 atoms for (NH4)2SO4), matching the 2021 memo;
stoichiometry gives 15 atoms/mol -> 9,03e24 (C). Recorded as the memo states.
This source paper has several internal mark inconsistencies between its stated sub-question
marks and its printed per-question "Question Total" row (the authoritative total used by the
build). Evidence marks are aligned to the paper's printed TOTAL of 200, so Q5=34, Q6=28,
Q8=17, Q9=30 (sub-question marks were adjusted where the printed per-question total exceeded
the sum of its stated sub-marks: Q5 collision-theory recorded at 3, Q6 6.3 at 8 and 6.4b at 5,
Q8 8.2 at 3, Q9 9.1g at 4).
"""

PAPER = {
    "paper_key": "CHE-2022-NOV",
    "paper_path": "data/organized/chemistry/G11 Nov Chem Exam QPs.pdf",
    "memo_path": "data/organized/chemistry/G11 Nov Chem Exam MG.pdf",
    "year": 2022,
    "exam_date": "28 November 2022",
    "exam_period": "nov",
    "paper_type": "paper2",
    "exam_board": "internal",
    "total_marks": 200,
    "examiner": "Mr McCoy",
    "moderator": "Mr Hilder",
    "duration_stated": "3 hours",
    "fidelity_rung": "A",
    "notes": (
        "School-set November Paper 2. Energy-profile (Q4.2) and structure-labelling sub-parts "
        "are diagram-based; several rely on the text-layer graph."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (20 marks) ----------------
    ("1.1", 2, "Matter & Materials", "Multiple Choice",
     "Correct formula for aluminium dichromate. A AlCr2O7 / B Al2(Cr2O7)3 / C Al3(Cr2O7)2 / D Al3Cr2O7",
     False, [], "B", ["Al2(Cr2O7)3"], "Memo gives the correct option only.", False, False),
    ("1.2", 2, "Bonding", "Multiple Choice",
     "Net ionic: Sn + Br2 -> Sn2+ + 2Br-. The species undergoing reduction is... A Sn atom / B bromine / C Sn ion / D bromide",
     False, [], "B", ["bromine is reduced to Br-"], "Memo gives the correct option only.", False, False),
    ("1.3", 2, "Stoichiometry", "Multiple Choice",
     "5,62 g Na2SO4 made up to 250 cm3. Concentration (mol/dm3)? A 0,00016 / B 0,0016 / C 0,016 / D 0,16",
     False, [], "D", ["0,16 mol/dm3"], "Memo gives the correct option only.", False, False),
    ("1.4", 2, "Intermolecular Forces", "Multiple Choice",
     "Which statement is NOT correct? A NH3 strongest IMF = H-bond / B HCl strongest IMF = dipole-dipole / "
     "C ethanol strongest IMF = dipole-dipole / D water strongest IMF = H-bond",
     False, [], "C", ["ethanol's strongest IMF is H-bond, not dipole-dipole"], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Energy & Chemical Change", "Multiple Choice",
     "Best explanation of 'heat-of-reaction'? A chem PE->thermal / B net kinetic energy / C thermal->chem PE / D net change chem PE of system",
     False, [], "D", ["net change in chemical potential energy"], "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Stoichiometry", "Multiple Choice",
     "Atoms in 1 mol (NH4)2SO4? A 6,02e23 / B 6,02e24 / C 8,43e24 / D 9,03e24",
     False, [], "D", ["memo marks D (8,43e24)"],
     "Memo marks D; stoichiometry gives 15 atoms/mol -> 9,03e24 (C). Recorded as the memo states.", False, False),
    ("1.7", 2, "Matter & Materials", "Multiple Choice",
     "Which is NOT true of balanced equations? A same atoms each side / B electrons balanced / "
     "C equal number of molecules each side / D law of conservation of mass",
     False, [], "C", ["molecules need not be equal"], "Memo gives the correct option only.", False, False),
    ("1.8", 2, "Organic Chemistry", "Multiple Choice",
     "Alkenes... A general formula CnH2n+2 / B are unsaturated hydrocarbons / C undergo substitution / D have a triple bond",
     False, [], "B", ["unsaturated hydrocarbons"], "Memo gives the correct option only.", False, False),
    ("1.9", 2, "Organic Chemistry", "Multiple Choice",
     "Propene + steam (H3PO4 catalyst) -> ? A CH3CH(OH)CH2OH / B CH3CH2CH3 / C HOCH2CH2CH2OH / D CH3CH2CH2OH",
     False, [], "D", ["propan-1-ol = CH3CH2CH2OH"], "Memo gives the correct option only.", False, False),
    ("1.10", 2, "Organic Chemistry", "Multiple Choice",
     "IUPAC name of the diol drawn. A 4-methylpenta-2,3-diol / B 4-methylpentane-2,3-diol / "
     "C 2-methylpenta-3,4-diol / D 2-methylpentane-3,4-diol",
     True, [], "B", ["4-methylpentane-2,3-diol"], "Memo gives the correct option only; structure is an image.", True, False),

    # ---------------- QUESTION 2: BACK-TITRATION PURITY (13 marks) ----------------
    ("2.1", 3, "Stoichiometry", "Calculation",
     "5 g impure (NH4)2O + 100 cm3 2 M HCl (excess): (NH4)2O + 2HCl -> 2NH4Cl + H2O. "
     "Calculate moles of HCl initially added.",
     False, ["n=cV"], "0,2 mol",
     ["n = cV (1)", "= 2 x 0,1 (1)", "= 0,2 mol (1)"], "Three marks.", False, False),
    ("2.2", 3, "Stoichiometry", "Calculation",
     "40 cm3 0,6 M NaOH neutralises the excess HCl (NaOH + HCl -> NaCl + H2O). Moles of excess HCl.",
     False, ["n=cV"], "0,024 mol",
     ["n(NaOH)=0,6x0,04 (1)", "1:1 (1)", "= 0,024 mol HCl (1)"], "Three marks.", False, False),
    ("2.3", 2, "Stoichiometry", "Calculation",
     "Moles of HCl that reacted with the (NH4)2O (from 2.1 and 2.2).",
     False, [], "0,176 mol", ["0,2 - 0,024 (1)", "= 0,176 mol (1)"], "Two marks.", False, False),
    ("2.4", 5, "Stoichiometry", "Calculation",
     "Hence calculate the % purity of the (NH4)2O sample. (M = 52)",
     False, ["n=m/M", "% purity = pure/impure x 100"], "91,52%",
     ["ratio 1:2 -> n((NH4)2O)=0,088 (1)", "m = 0,088x52 = 4,576 g (1)", "4,576/5 x 100 (1)", "= 91,52% (1)"],
     "Five marks; M (NH4)2O = 52.", False, False),

    # ---------------- QUESTION 3: INTERMOLECULAR FORCES (20 marks) ----------------
    ("3.1.1", 4, "Intermolecular Forces", "Explanation",
     "Boiling points of halogen substances. Explain why bromine needs more energy to boil than fluorine.",
     False, [], "both non-polar with London forces; Br2 has more electrons -> larger temporary dipole -> stronger London forces -> higher Bpt",
     ["both non-polar, London forces (1)", "Br2 more electrons (1)", "larger temporary dipole (1)", "stronger forces, higher Bpt (1)"],
     "Four marks.", False, False),
    ("3.1.2", 5, "Intermolecular Forces", "Explanation",
     "Explain why boiling points of HBr and HF differ.",
     False, [], "HBr has dipole-dipole; HF has H-bonding (stronger), so HF needs most energy to overcome its IMFs",
     ["HBr dipole-dipole (1)", "HF H-bond (1)", "H-bond stronger (1)", "HF most energy (1)"], "Five marks.", False, False),
    ("3.1.3", 2, "Intermolecular Forces", "Short Answer",
     "CH3F and CH3Br Bpt differ by ~80 C. Name the strongest IMF in the substance with the higher Bpt.",
     False, [], "dipole-dipole forces (in CH3Br)", ["dipole-dipole (2)"], "Two marks.", False, False),
    ("3.2.1", 2, "Bonding", "Short Answer",
     "K2SO4 MP 197 C, CaSO4 MP 1460 C. Write the balanced dissociation equation for K2SO4 in water.",
     False, [], "K2SO4 -> 2K+ + SO4 2-", ["2K+ (1)", "SO4 2- (1)"], "Two marks.", False, False),
    ("3.2.2", 2, "Bonding", "Short Answer",
     "Name the intramolecular bond in K2SO4.",
     False, [], "covalent bond (NOT ionic — it is the intramolecular bond)", ["covalent (2)"], "Two marks (memo: not ionic).", False, False),
    ("3.2.3", 3, "Bonding", "Explanation",
     "Explain the vast difference in melting points of K2SO4 and CaSO4.",
     False, [], "Ca2+ has twice the electrostatic attraction on SO4 2-; ionic bonds in CaSO4 twice as strong; more energy to break",
     ["Ca2+ twice the attraction (1)", "bonds twice as strong (1)", "more energy to break (1)"], "Three marks.", False, False),
    ("3.2.4", 2, "Stoichiometry", "Short Answer",
     "Predict which is more soluble in water at room temp: CaSO4 or K2SO4.",
     False, [], "potassium sulfate (K2SO4)", ["K2SO4 (2)"], "Two marks.", False, False),

    # ---------------- QUESTION 4: ENERGY PROFILE (15 marks) ----------------
    ("4.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Hexene -> hexane hydrogenation. Define heat of reaction (dH).",
     True, [], "the net change of chemical potential energy of the system",
     ["net change (1)", "chemical potential energy (1)"], "Two marks.", True, False),
    ("4.2", 3, "Energy & Chemical Change", "Calculation",
     "Ea = 8 kcal/mol, Eout = 54,1 kcal/mol. Calculate dH.",
     True, [], "-46,1 kcal.mol-1", ["dH = Ea - Eout (1)", "= 8 - 54,1 (1)", "= -46,1 (1)"], "Three marks.", True, False),
    ("4.2g", 2, "Energy & Chemical Change", "Diagram-based",
     "Complete the energy-profile graph for the reaction on the axes provided.",
     True, [], "endothermic curve (reactants lower, products higher)", ["endothermic shape (2)"], "Two marks; on the graph.", True, False),
    ("4.2x", 1, "Energy & Chemical Change", "Diagram-based",
     "Write the relevant labels for the x-axis of the energy profile.",
     True, [], "reaction coordinate", ["reaction coordinate (1)"], "One mark.", True, False),
    ("4.2e", 2, "Energy & Chemical Change", "Diagram-based",
     "Indicate and label the two energy intervals Ea and dH on the graph (no numerical values needed).",
     True, [], "Ea and dH labelled on the profile", ["Ea labelled (1)", "dH labelled (1)"], "Two marks; on the graph.", True, False),
    ("4.2a", 1, "Energy & Chemical Change", "Short Answer",
     "A catalyst is added. Name a suitable catalyst.",
     True, [], "platinum, palladium or nickel", ["Pt/Pd/Ni (1)"], "One mark.", True, False),
    ("4.2b", 2, "Energy & Chemical Change", "Explanation",
     "A learner says: 'A catalyst lowers Ea which results in more collisions per second.' Explain why incorrect.",
     True, [], "a catalyst does not lower Ea of the original reaction; it provides an alternative route with lower Ea (collision frequency unchanged)",
     ["Ea of original not lowered (1)", "alternative route with lower Ea (1)"], "Two marks.", True, False),
    ("4.2c", 2, "Energy & Chemical Change", "Diagram-based",
     "Draw a second graph to show the effect of the catalyst.",
     True, [], "lower curve, same reactant and product positions", ["lower curve (1)", "same reactant/product positions (1)"], "Two marks; on the graph.", True, False),

    # ---------------- QUESTION 5: REACTION RATE / REDOX (34 marks) ----------------
    ("5.1a", 3, "Stoichiometry", "Calculation",
     "3Cu + 8HNO3 -> 3Cu(NO3)2 + 2NO + 4H2O. Exp A: 2,54 g Cu, 0,10 dm3 0,8 M HNO3. Moles of Cu.",
     False, ["n=m/M"], "0,04 mol", ["n=2,54/63,5 (1)", "=0,04 (1)"], "Three marks (M Cu=63,5).", False, False),
    ("5.1b", 3, "Stoichiometry", "Calculation",
     "Moles of HNO3 in Exp A.",
     False, ["n=cV"], "0,08 mol", ["n=0,8x0,1 (1)", "=0,08 (1)"], "Three marks.", False, False),
    ("5.1c", 3, "Stoichiometry", "Calculation",
     "Hence show copper is in excess.",
     False, [], "Cu in excess (need 0,03 mol Cu, have 0,04)", ["0,03 mol Cu required (1)", "0,04 available (1)", "excess (1)"], "Three marks.", False, False),
    ("5.1d", 4, "Stoichiometry", "Calculation",
     "Volume of NO(g) produced at STP if reaction completes.",
     False, ["V=n.Vm"], "0,448 dm3", ["ratio 8:2 -> 0,02 mol NO (1)", "V=n.Vm (1)", "=0,02x22,4 (1)", "=0,448 dm3 (1)"],
     "Four marks.", False, False),
    ("5.2a", 3, "Reaction Rates", "Calculation",
     "NO volume vs time for Exp A. Calculate average rate of Exp A.",
     True, [], "0,014 dm3.s-1", ["rate = V/t (1)", "=0,448/(28-32) (1)", "=0,014 (1)"], "Three marks; from the graph.", True, False),
    ("5.2b", 4, "Reaction Rates", "Diagram-based",
     "Draw curves for experiments B and C on the axes; label them.",
     True, [], "B: lower gradient, half of A; C: higher gradient, double A",
     ["B lower gradient, half A (2)", "C higher gradient, double A (2)"], "Four marks; on the graph.", True, False),
    ("5.2c", 3, "Reaction Rates", "Explanation",
     "Explain how an increase in concentration affects rate via collision theory.",
     False, [], "more particles per volume -> more collisions/s -> more effective collisions -> faster rate",
     ["more particles/volume (1)", "more collisions/s (1)", "more effective collisions -> faster (1)"],
     "Three marks (paper's Q5 sub-marks sum to 35 vs printed 34; aligned to 34).", False, False),
    ("5.3a", 3, "Reaction Rates", "Explanation",
     "State whether mass loss of the mixture would INCREASE/DECREASE/STAY THE SAME; give a reason.",
     True, [], "DECREASE — NO is a (heavy) gas that escapes the vessel",
     ["DECREASE (1)", "NO gas escapes (1)", "heavy gas (1)"], "Three marks.", True, False),
    ("5.3b", 3, "Reaction Rates", "Explanation",
     "State whether % transmission of light would INCREASE/DECREASE/STAY THE SAME; give a reason.",
     True, [], "DECREASE — blue Cu(NO3)2 colour intensifies, less light transmitted",
     ["DECREASE (1)", "blue colour intensifies (1)", "less light transmitted (1)"], "Three marks.", True, False),
    ("5.4a", 1, "Bonding", "Definition/Explain",
     "Define redox reaction.",
     False, [], "a reaction involving the transfer of electrons", ["transfer of electrons (1)"], "One mark.", False, False),
    ("5.4b", 2, "Bonding", "Short Answer",
     "Write the oxidation half reaction for a copper atom.",
     False, [], "Cu -> Cu2+ + 2e-", ["Cu (1)", "Cu2+ + 2e- (1)"], "Two marks.", False, False),
    ("5.4c", 2, "Bonding", "Short Answer",
     "Is Cu the reducing agent in the reaction? Circle YES or NO.",
     False, [], "YES", ["YES (2)"], "Two marks.", False, False),

    # ---------------- QUESTION 6: ENDOTHERMIC / IONIC BOND / WATER OF CRYSTALLISATION (28 marks) ----------------
    ("6.1", 2, "Energy & Chemical Change", "Definition/Explain",
     "Ba(OH)2.xH2O + 2NH4Cl -> 2NH3 + ... + BaCl2, T drops to -25 C. Define endothermic reaction.",
     False, [], "reactions that transform thermal energy into chemical potential energy (products have more PE)",
     ["thermal -> chemical PE (1)", "products more PE (1)"], "Two marks.", False, False),
    ("6.1b", 1, "Energy & Chemical Change", "Short Answer",
     "More energy absorbed than released. Classify as ENDOTHERMIC or EXOTHERMIC.",
     False, [], "ENDOTHERMIC", ["ENDOTHERMIC (1)"], "One mark.", False, False),
    ("6.1c", 1, "Energy & Chemical Change", "Short Answer",
     "Is bond breaking ENDOTHERMIC or EXOTHERMIC?",
     False, [], "ENDOTHERMIC", ["ENDOTHERMIC (1)"], "One mark.", False, False),
    ("6.1d", 1, "Energy & Chemical Change", "Short Answer",
     "Would products contain MORE or LESS potential energy than reactants?",
     False, [], "MORE", ["MORE (1)"], "One mark.", False, False),
    ("6.1e", 2, "Energy & Chemical Change", "Short Answer",
     "Would the heat of reaction be POSITIVE or NEGATIVE?",
     False, [], "POSITIVE", ["POSITIVE (2)"], "Two marks.", False, False),
    ("6.2a", 2, "Bonding", "Definition/Explain",
     "Consider solid NH4Cl. Define ionic bond.",
     False, [], "transfer of electrons and subsequent electrostatic attraction (between ions)",
     ["transfer of electrons (1)", "electrostatic attraction (1)"], "Two marks.", False, False),
    ("6.2b", 4, "Bonding", "Diagram-based",
     "NH4Cl has one cation and one anion. Draw a Lewis diagram of each ion.",
     False, [], "NH4+ (cation) and Cl- (anion) Lewis structures",
     ["NH4+ drawn (2)", "Cl- drawn (2)"], "Four marks; Lewis diagrams.", False, False),
    ("6.3", 8, "Stoichiometry", "Calculation",
     "Water of crystallisation removed from Ba(OH)2.xH2O. Mass hydrated 97,190 g, water 1,260 g. Determine x. (M=171,3)",
     False, ["n=m/M"], "x = 8",
     ["m(Ba(OH)2)=97,19-1,26=95,93 (1)", "n=95,93/171,3=0,56 (1)", "n(H2O)=1,26/18=0,07 (1)",
      "ratio 0,56:0,07=8:1 (1)", "x=8 (1)"], "Six marks.", False, False),
    ("6.4a", 2, "Reaction Rates", "Definition/Explain",
     "Define rate of reaction.",
     True, [], "change in concentration per unit time of a reactant or product",
     ["change in concentration (1)", "per unit time (1)"], "Two marks.", True, False),
    ("6.4b", 5, "Reaction Rates", "Diagram-based",
     "Maxwell-Boltzmann at 25 C. Draw the curve at 50 C; label y-axis, Ea, and shaded area P "
     "(particles with enough Ek to react).",
     True, [], "peak right and below original, stays above; Ea and shaded area P labelled",
     ["y-axis label (1)", "peak to right/below (1)", "Ea indicated (1)", "P (proportion) indicated (1)"], "Four marks; on the graph.", True, False),

    # ---------------- QUESTION 7: ORGANIC CHEMISTRY (23 marks) ----------------
    ("7.1", 2, "Organic Chemistry", "Definition/Explain",
     "Hexane and 2,2-dimethylbutane are isomers. Define structural isomer.",
     False, [], "compounds with the same molecular formula but different structural formulae",
     ["same molecular formula (1)", "different structural formula (1)"], "Two marks.", False, False),
    ("7.2", 2, "Organic Chemistry", "Short Answer",
     "General formula for the homologous series of hexane and 2,2-dimethylbutane (alkanes).",
     False, [], "CnH2n+2", ["CnH2n+2 (2)"], "Two marks.", False, False),
    ("7.3", 2, "Organic Chemistry", "Short Answer",
     "Give the molecular formula for both compounds.",
     False, [], "C6H14", ["C6H14 (2)"], "Two marks.", False, False),
    ("7.4", 5, "Organic Chemistry", "Diagram-based",
     "Draw the structural formulae for hexane and 2,2-dimethylbutane.",
     True, [], "hexane: straight 6-C chain; 2,2-dimethylbutane: butane with two methyls on C2",
     ["correct C count in main chains (2)", "both methyl branches on C2 (2)", "valid structures (1)"], "Five marks; structures.", True, False),
    ("7.5", 1, "Organic Chemistry", "Short Answer",
     "Classify as SATURATED or UNSATURATED.",
     False, [], "SATURATED", ["SATURATED (1)"], "One mark.", False, False),
    ("7.6", 1, "Organic Chemistry", "Short Answer",
     "Which has the stronger intermolecular forces (hexane or 2,2-dimethylbutane)?",
     False, [], "hexane", ["hexane (1)"], "One mark.", False, False),
    ("7.7", 3, "Organic Chemistry", "Explanation",
     "Explain 7.6.",
     False, [], "hexane has the longer chain -> greater surface area -> more London forces (stronger IMF)",
     ["longer chain (1)", "greater surface area (1)", "more/stronger London forces (1)"], "Three marks.", False, False),
    ("7.8", 3, "Organic Chemistry", "Diagram-based",
     "Draw the structural formula for the POSITIONAL ISOMER of 2,2-dimethylbutane.",
     True, [], "a methyl on C2 and C3 of a 4-carbon chain (e.g. 2,3-dimethylbutane)",
     ["methyl on C2 (1)", "methyl on C3 (1)", "four carbons (1)"], "Three marks; structure.", True, False),
    ("7.9a", 2, "Organic Chemistry", "Short Answer",
     "Hexane undergoes: heat/K -> propene + compound X. State the SPECIFIC reaction type.",
     False, [], "thermal cracking", ["thermal (1)", "cracking (1)"], "Two marks.", False, False),
    ("7.9b", 2, "Organic Chemistry", "Short Answer",
     "Give the IUPAC name of compound X.",
     False, [], "methane", ["methane (2)"], "Two marks.", False, False),

    # ---------------- QUESTION 8: ORGANIC CHEMISTRY (17 marks) ----------------
    ("8.1", 2, "Organic Chemistry", "Short Answer",
     "A = CH3CH2CH2Cl. Give the IUPAC name of compound A.",
     False, [], "1-chloropropane", ["1-chloro (1)", "propane (1)"], "Two marks.", False, False),
    ("8.2", 3, "Organic Chemistry", "Definition/Explain",
     "Define homologous series.",
     False, [], "series of similar compounds with the same general formula and functional group, differing by CH2",
     ["same general formula + functional group (1)", "differ by CH2 (1)"], "Two marks.", False, False),
    ("8.3", 1, "Organic Chemistry", "Short Answer",
     "Identify the homologous series of compound A (CH3CH2CH2Cl).",
     False, [], "haloalkanes", ["haloalkanes (1)"], "One mark.", False, False),
    ("8.4a", 2, "Organic Chemistry", "Short Answer",
     "Write the condensed structural formula for compound B (propene, from A via elimination).",
     False, [], "CH3CH=CH2", ["CH3CH=CH2 (2)"], "Two marks.", False, False),
    ("8.4b", 2, "Organic Chemistry", "Short Answer",
     "Write the condensed structural formula for compound C (propan-1-ol, from B via H2O addition).",
     False, [], "CH3CH2CH2OH", ["CH3CH2CH2OH (2)"], "Two marks.", False, False),
    ("8.5", 1, "Organic Chemistry", "Short Answer",
     "For reaction (i) (A -> B), state the GENERAL reaction type.",
     False, [], "elimination", ["elimination (1)"], "One mark.", False, False),
    ("8.6", 2, "Organic Chemistry", "Short Answer",
     "For reaction (ii) (B -> C, addition of steam), state the SPECIFIC reaction type.",
     False, [], "hydration", ["hydration (2)"], "Two marks.", False, False),
    ("8.7", 2, "Organic Chemistry", "Short Answer",
     "For reaction (iii) (C under reflux), state the SPECIFIC reaction type.",
     False, [], "dehydration", ["dehydration (2)"], "Two marks.", False, False),
    ("8.8", 2, "Organic Chemistry", "Explanation",
     "Why carry out organic reactions under reflux?",
     False, [], "reactants are volatile and escape; reflux returns them to the vessel",
     ["reactants volatile/escape (1)", "reflux reintroduces them (1)"], "Two marks.", False, False),

    # ---------------- QUESTION 9: ORGANIC CHEMISTRY (30 marks) ----------------
    ("9.1a", 1, "Organic Chemistry", "Short Answer",
     "Two molecules combine with elimination of water. State the GENERAL term.",
     False, [], "condensation (esterification)", ["condensation (1)"], "One mark.", False, False),
    ("9.1b", 2, "Organic Chemistry", "Definition/Explain",
     "Define functional group.",
     False, [], "an atom or group of atoms forming the centre of chemical activity of a compound",
     ["atom/group of atoms (1)", "centre of chemical activity (1)"], "Two marks.", False, False),
    ("9.1c", 1, "Organic Chemistry", "Short Answer",
     "Name the functional group of compound Y (carboxyl).",
     False, [], "carboxyl", ["carboxyl (1)"], "One mark.", False, False),
    ("9.1d", 1, "Organic Chemistry", "Short Answer",
     "Circle the functional group of compound Z (ester).",
     False, [], "ester", ["ester (1)"], "One mark.", False, False),
    ("9.1e", 1, "Organic Chemistry", "Short Answer",
     "Name the homologous series of compound Y.",
     False, [], "carboxylic acid", ["carboxylic acid (1)"], "One mark.", False, False),
    ("9.1f", 1, "Organic Chemistry", "Short Answer",
     "Name the homologous series of compound Z.",
     False, [], "ester", ["ester (1)"], "One mark.", False, False),
    ("9.1g", 4, "Organic Chemistry", "Diagram-based",
     "Use structural formula: (a) draw the alcohol used (2); (b) complete compound Y (ester) (2).",
     False, [], "alcohol = propan-1-ol; Y = propyl ethanoate (ester of propanol + ethanoic acid)",
     ["alcohol structure (1)", "Y ester structure (1)"], "Two marks each; structures.", False, False),
    ("9.1h", 3, "Organic Chemistry", "Calculation",
     "Write a balanced combustion equation (chemical formula) for the alcohol (propan-1-ol, C3H8O).",
     False, [], "2C3H8O + 9O2 -> 6CO2 + 8H2O", ["reactants (1)", "balanced (1)", "products (1)"], "Three marks.", False, False),
    ("9.2a", 3, "Organic Chemistry", "Short Answer",
     "Compounds A (alkene) and B (alkane). Give the IUPAC name of B (an octadiene drawn).",
     True, [], "octa-1,3-diene", ["octa- (1)", "1,3- (1)", "diene (1)"], "Three marks; structure is an image.", True, False),
    ("9.2b", 3, "Organic Chemistry", "Explanation",
     "Consider bonds (i) and (ii) in compound A. Account for the difference in length.",
     True, [], "bond (i) is shorter than (ii) because it has an additional pi bond; (ii) has only a sigma bond",
     ["(i) shorter (1)", "additional pi bond (1)", "(ii) only sigma (1)"], "Three marks.", True, False),
    ("9.2c", 3, "Organic Chemistry", "Explanation",
     "Can red-brown bromine water distinguish the two compounds? Explain why.",
     True, [], "yes — bromine is red and loses its colour when it adds to the alkene (A)",
     ["bromine red (1)", "loses colour when bonded (1)", "in the alkene A (1)"], "Three marks.", True, False),
    ("9.2d", 4, "Organic Chemistry", "Explanation",
     "Describe the method to distinguish the two compounds using bromine water.",
     True, [], "place equal amounts in test tubes; count drops until colour stops; A (alkene) takes the most drops",
     ["equal amounts (1)", "count drops (1)", "until colour stops (1)", "A takes most drops (1)"], "Four marks.", True, False),
    ("9.2e", 3, "Organic Chemistry", "Calculation",
     "Write a balanced equation (condensed structural formula) for compound A + bromine.",
     False, [], "CH2=CH(CH2)5CH3 + Br2 -> CH2Br-CHBr-(CH2)5CH3",
     ["reactants (1)", "balanced (1)", "product dibromide (1)"], "Three marks.", False, False),
]
