"""Pass 1 evidence table — Grade 11 Physical Science Paper 1, 22 July 2019 (mid-year).

Authored by reading the extracted text of the paper and its marking guidelines.
Paper:  data/organized/physics/Grade 11 Paper 1 QP 2019.pdf  (165 marks, Mr McCoy)
Memo:   data/organized/physics/Grade 11 Paper 1 MG 2019.pdf  (165 marks, Mr McCoy)

Record tuple layout (see SCHEMA below):
(qn, marks, topic, qtype, text, has_diagram, formulae, memo_answer,
 memo_steps, memo_notes, needs_visual, ocr_uncertain)
"""

PAPER = {
    "paper_key": "PHY-2019-MY",
    "paper_path": "data/organized/physics/Grade 11 Paper 1 QP 2019.pdf",
    "memo_path": "data/organized/physics/Grade 11 Paper 1 MG 2019.pdf",
    "year": 2019,
    "exam_date": "22 July 2019",
    "exam_period": "june",
    "paper_type": "paper1",
    "exam_board": "internal",
    "total_marks": 165,
    "examiner": "Mr McCoy",
    "moderator": "Mr Ntombela",
    "duration_stated": {"paper": "150 minutes", "memo": "180 minutes"},
    "fidelity_rung": "A",
    "notes": (
        "School-set paper using the IEB NSC Physical Sciences data sheet "
        "(IEB Copyright 2014-2018 handbook printed on the paper's data sheet)."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (16 marks) ----------------
    ("1.1", 2, "Mechanics-Vectors", "Multiple Choice",
     "Which of the following pairs of physical quantities contains ONLY vector quantities? "
     "A velocity, energy / B acceleration, distance / C work, speed / D displacement, velocity",
     False, [], "D", [], "Memo gives the correct option only; no method or distractor analysis shown.", False, False),
    ("1.2", 2, "Mechanics-Motion graphs", "Multiple Choice",
     "A driver stops his car in time t by gradually increasing the total braking force. The graph shows "
     "the resultant force on the car. Which graph shows how the speed of the car will vary during this time?",
     True, [], "D", [], "Memo gives the correct option only; force-time and speed-time graphs are images.", True, False),
    ("1.3", 2, "Mechanics-Forces", "Multiple Choice",
     "Peter pushes two books on a frictionless surface with a force F. The force Book 1 exerts on Book 2 is X; "
     "the force Book 2 exerts on Book 1 is Y. The magnitude of X compared to Y is: A X = Y / B X > Y / "
     "C X < Y / D Depends on the acceleration of the system",
     True, [], "A", [], "Memo gives the correct option only.", True, False),
    ("1.4", 2, "Mechanics-Vectors", "Multiple Choice",
     "Two forces, 4 N and 11 N, simultaneously act on a point. Which of the following cannot be the magnitude "
     "of their resultant? A 5 N / B 7 N / C 9 N / D 15 N",
     False, [], "A", [], "Memo gives the correct option only.", False, False),
    ("1.5", 2, "Mechanics-Gravitation", "Multiple Choice",
     "An object has a weight of 88,20 N on Earth. Gravitational field strength on the Moon is 1,64 m.s-2. "
     "What are the weight and mass of the object on the Moon? (options give Weight (N) / Mass (kg) pairs: "
     "A 14,76 / 1,5 ; B 14,76 / 9,0 ; C 88,20 / 1,5 ; D 88,20 / 9,0)",
     False, [], "B", [], "Memo gives the correct option only.", False, False),
    ("1.6", 2, "Electric Circuits", "Multiple Choice",
     "A portable generator is connected by cables to floodlights; generator produces 10 A at 240 V; total "
     "cable resistance 2 ohm. What is the p.d. V across and power P delivered to the floodlights? "
     "(A 220/2400; B 220/2200; C 230/2400; D 230/2300)",
     True, [], "B", [], "Memo gives the correct option only; circuit diagram is an image.", True, False),
    ("1.7", 2, "Electric Circuits", "Multiple Choice",
     "Circuit of two identical cells, a resistor, an ammeter and a voltmeter; each cell emf 3,0 V, resistor "
     "12 ohm, negligible internal resistance. Which row shows the voltmeter and ammeter readings? "
     "(A 3,0/0,25; B 3,0/0,50; C 6,0/0,25; D 6,0/0,50)",
     True, [], "A", [], "Memo gives the correct option only; circuit diagram is an image.", True, False),
    ("1.8", 2, "Electric Circuits", "Multiple Choice",
     "Cell with negligible internal resistance connected to three resistors, an ammeter and a voltmeter. "
     "Which row shows the ammeter and voltmeter readings? (A 0,075/0,75; B 0,075/1,50; C 0,150/0,75; D 0,150/1,50)",
     True, [], "D", [], "Memo gives the correct option only; circuit diagram is an image.", True, False),

    # ---------------- QUESTION 2: HORIZONTAL MOTION (34 marks) ----------------
    ("2.1.1", 2, "Mechanics-Motion", "Definition/Explain",
     "Define velocity. (v-t graphs of cars P and Q; cars travel in the same direction; P passes Q at t = 0)",
     True, [],
     "the rate of change of position or the rate of displacement or the rate of change of displacement and "
     "know that velocity is a vector quantity",
     ["rate of change of position / rate of displacement (1)", "vector quantity stated (1)"],
     "Two marks allocated to the definition; memo wording accepts three alternative phrasings.", True, False),
    ("2.1.2", 3, "Mechanics-Motion", "Data/Graph Interpretation",
     "The speed limit is 100 km.h-1. State and explain whether car Q exceeds the speed limit.",
     True, [], "108 km.h-1; therefore the speed limit was broken",
     ["30 m.s-1 x 3,6 (1)", "= 108 km.h-1 (1)", "conclusion: speed limit broken (1)"],
     "Mark awarded for the conversion factor AND the explicit conclusion.", True, False),
    ("2.1.3", 3, "Mechanics-Motion", "Calculation",
     "Calculate the magnitude of the acceleration of car P.",
     True, ["v = u + at"], "a = 0,33 m.s-2",
     ["v = u + at (accept gradient calculation)", "24 = 20 + a(12)", "a = 0,33 m.s-2"],
     "Memo explicitly accepts a gradient calculation as an alternative method.", True, False),
    ("2.1.4", 4, "Mechanics-Motion", "Data/Graph Interpretation",
     "Determine the distance between the two cars at time t = 12 s.",
     True, ["area under v-t graph"], "84 m",
     ["Car Q = 1/2 b.h (formula mark)", "= 0,5 x 12 x 30 = 180 m",
      "Car P = 1/2 b.h + l x b = 24 + 240 = 264 m", "264 - 180 = 84 m"],
     "Separate formula mark awarded before substitution; answer obtained as a difference of two areas.", True, False),
    ("2.1.5", 4, "Mechanics-Motion", "Calculation",
     "From t = 12 s the velocity of each car remains constant. Determine the time t at which car Q passes car P.",
     True, ["v = s/t"], "t = 26 s",
     ["180 + 30t = 264 + 24t", "30t - 24t = 264 - 180", "t = 14 s", "Time = 14 + 12 = 26 s"],
     "Final mark requires adding the 12 s already elapsed; equation set-up carries 2 marks.", True, False),
    ("2.2.1", 1, "Mechanics-Motion", "Short Answer",
     "Truck at constant 20 m.s-1; driver sees a stationary car at X and hits the brakes 0,35 s later at Y. "
     "What is the reaction time of the driver?",
     True, [], "0,35 s", ["0,35 s"], "Single mark, read directly from the given data.", True, False),
    ("2.2.2", 2, "Mechanics-Motion", "Calculation",
     "Calculate how far the truck travels before the brakes are applied.",
     True, ["s = v x t"], "7 m", ["s = v x t", "= 20 x 0,35", "= 7 m"],
     "Formula + substitution/answer marked.", True, False),
    ("2.2.3", 4, "Mechanics-Motion", "Calculation",
     "Calculate how long it takes before the truck comes to rest from the moment the car is seen.",
     True, ["v = u + at"], "8,35 s",
     ["0 = 20 + (-2,5)t", "t = 8 s", "total time = 8 + 0,35 = 8,35 s"],
     "Memo note: 'Must show that the acceleration is negative.' Final mark requires adding reaction time.", True, False),
    ("2.2.4", 4, "Mechanics-Motion", "Calculation",
     "Calculate how far point X is from the car. (Truck stops 2 m from the car at Z.)",
     True, ["s = ((v+u)/2)t"], "89 m",
     ["s = ((v+u)/2)t", "= ((0+20)/2)(8)", "= 80 m (YZ)", "car from X = 7 + 80 + 2 = 89 m"],
     "Memo marks the sum of three separate distances; missing the 2 m gap loses a mark.", True, False),
    ("2.2.5", 3, "Mechanics-Motion graphs", "Diagram-based",
     "Draw a v/t sketch graph for the motion of the truck from X to Z.",
     True, [], "Graph: horizontal at 20 m.s-1 to t = 0,35 s then straight line down to 0 at t = 8,35 s",
     ["correct shape", "all values", "c.o.e. (consistent with earlier errors)"],
     "Memo awards marks for shape and labelled values; 'c.o.e.' allows credit from an earlier wrong value.", True, False),
    ("2.3", 4, "Mechanics-Motion", "Calculation",
     "A car travels a distance R in a time t accelerating uniformly from rest. What distance, in terms of R, "
     "will the car travel if it accelerates for twice the time? Assume rectilinear motion.",
     False, ["s = ut + 1/2 at2"], "4R",
     ["R = 0 + 1/2 at2 -> 2R = at2", "s = 0 + 1/2 a(2t)2 -> s/2 = at2", "link the two expressions", "s = 4R"],
     "Memo marks the algebraic link between the two cases explicitly ('link').", False, False),

    # ---------------- QUESTION 3: VERTICAL MOTION / GRAPHS (31 marks) ----------------
    ("3.1.1", 2, "Mechanics-Motion", "Definition/Explain",
     "Define acceleration. (velocity-time graph of a ball bouncing vertically on a distant planet, no atmosphere)",
     True, [], "the rate of change of velocity", ["rate of change of velocity (2)"],
     "Two marks for the definition alone.", True, False),
    ("3.1.2", 4, "Mechanics-Motion graphs", "Data/Graph Interpretation",
     "Describe the motion of the ball for 0,5 - 0,9 seconds.",
     True, [], "uniform acceleration down; decreasing velocity up",
     ["uniform acceleration (1)", "down (1)", "decreasing velocity (1)", "up (1)"],
     "Two separate mark pairs: one for the acceleration statement + direction, one for velocity + direction.", True, False),
    ("3.1.3", 3, "Mechanics-Motion", "Calculation",
     "Calculate the height from which the ball was dropped.",
     True, ["s = ((u+v)/2)t", "area = 1/2 b.h"], "0,8 m",
     ["s = (u+v)/2 x t OR A = 1/2 b.h", "= (0+3,2)/2 x 0,5 = 1/2 x 3,2 x 0,5", "= 0,8 m"],
     "Memo accepts either the average-velocity equation or the area under the graph.", True, False),
    ("3.1.4", 2, "Mechanics-Forces", "Diagram-based",
     "Draw a labelled free-body diagram showing the forces acting on the ball at 0,7 s. Ignore air resistance.",
     True, [], "dot and weight ONLY", ["dot (1)", "weight (1)"],
     "Memo says 'dot and weight ONLY' - extra forces are penalised.", True, False),
    ("3.1.5", 2, "Work Energy Power", "Short Answer",
     "Was any energy lost during the bounce? Briefly explain your answer.",
     True, [], "Yes, the velocity before and after the bounce is different",
     ["Yes (1)", "velocity before and after bounce differs (1)"],
     "Mark requires the reasoned comparison, not just 'yes'.", True, False),
    ("3.1.6", 2, "Mechanics-Motion graphs", "Data/Graph Interpretation",
     "State the magnitude of the velocity with which the ball hits the ground at 1,30 s.",
     True, [], "2,56 m.s-1", ["2,56 m.s-1 (2)"], "Read off the graph; both marks for the value.", True, False),
    ("3.1.7", 3, "Mechanics-Motion graphs", "Diagram-based",
     "Sketch an acceleration versus time graph of the ball from 0 s to 0,9 s.",
     True, [], "constant -9,8 m.s-2 (or 9,8 down) from 0 to 0,9 s", ["correct constant value/shape (3)"],
     "Memo shows the expected graph as an image with value 9,8 labelled.", True, False),
    ("3.1.8", 4, "Mechanics-Motion graphs", "Diagram-based",
     "Sketch the corresponding position-time graph for the motion from 0 s to 1,3 s, using the point of "
     "release as position zero and maintaining the direction used in the given graph.",
     True, [], "curve as shown in memo", ["draw as shown"],
     "Memo note: '3/4 if on the negative side' - partial credit for a mirrored but consistent graph.", True, False),
    ("3.2.1", 3, "Mechanics-Motion", "Calculation",
     "Athlete runs anticlockwise around an 800 m track starting at A. It takes 1 min 45 s to run half way "
     "to B. Calculate the average speed of the athlete.",
     True, ["speed = distance/time"], "3,81 m.s-1",
     ["speed = distance/time", "= 400/105", "= 3,81 m.s-1"],
     "Distance must be halved (400 m) and time converted to seconds.", True, False),
    ("3.2.2", 2, "Mechanics-Motion", "Short Answer",
     "Suppose the athlete continues at constant speed; what is the athlete's instantaneous velocity at point C?",
     True, [], "3,81 m.s-1 west", ["3,81 m.s-1 c.o.e. (1)", "west (1)"],
     "Memo awards one mark for magnitude (consistent with earlier answer) and one for direction.", True, False),
    ("3.2.3", 4, "Mechanics-Motion", "Definition/Explain",
     "Use points A - C to explain the difference between distance and displacement.",
     True, [],
     "distance = length of path travelled (A to B to C); displacement = change in position (straight line A to C, north)",
     ["distance as length of path travelled (1)", "reference to A-B-C route (1)",
      "displacement as change in position (1)", "straight line A to C with direction (1)"],
     "Each definition AND its application to the given points is separately marked.", True, False),

    # ---------------- QUESTION 4: FORCES / VECTORS (20 marks) ----------------
    ("4.1.1", 2, "Mechanics-Vectors", "Definition/Explain",
     "Define resultant force. (ship towed by two tug-boats with forces A and B)",
     True, [], "the single force which has the same effect as the original forces acting together",
     ["single force (1)", "same effect as original forces together (1)"], "Two-part definition.", True, False),
    ("4.1.2", 6, "Mechanics-Vectors", "Calculation",
     "Determine the resultant force on the ship. Give your answer in bearing.",
     True, ["Pythagoras", "tan-1"], "8745,21 N on a bearing of 190,5 degrees",
     ["resolve x-components (1854,10 - 3447,2 = -1593,01)", "resolve y-components (5706,34 + 2892,54 = 8598,88)",
      "a2 + b2 = c2 -> c = 8745,21 N", "theta = tan-1(8598,88/1593,01) = 79,50",
      "final answer with bearing 190,5 degrees"],
     "Six marks distributed over component resolution, magnitude, angle and final bearing statement.", True, False),
    ("4.2.1", 2, "Mechanics-Motion", "Definition/Explain",
     "Define speed. (horse pulling a canal boat at constant velocity, rope at 12 degrees, tension 1150 N)",
     True, [], "the rate of change of distance (AON)", ["rate of change of distance (2)"],
     "Memo note 'AON' = any other (correct) wording accepted.", True, False),
    ("4.2.2", 3, "Mechanics-Forces", "Calculation",
     "The canal boat is moving at a steady speed. Calculate the resistive (frictional) force opposing the "
     "boat's forward motion.",
     True, ["F = T cos theta"], "1125 N",
     ["component of tension = 1150 x cos 12 (1)", "= 1125 N (1)", "resistive force = 1125 N (1)"],
     "Requires the equilibrium argument: constant velocity implies forces balance.", True, False),
    ("4.2.3", 2, "Mechanics-Forces", "Definition/Explain",
     "Why is it necessary to have someone steer the boat in order to keep it in the direction of motion?",
     True, [],
     "the tension has a component pulling the boat off course, so it must be steered in the opposite direction",
     ["tension has a lateral component (1)", "steering in opposite direction keeps course (1)"],
     "Both the cause and the corrective action are marked.", True, False),
    ("4.2.4", 3, "Mechanics-Vectors", "Diagram-based",
     "Draw a vector addition diagram of all the forces acting on the boat in the same plane at the "
     "tensional force.",
     True, [], "tension 1150 N, resistive force and steering force drawn as a closed vector triangle",
     ["tension = 1150 N (1)", "resistive force (1)", "'steering' force (1)"],
     "Memo note: '12 degrees minus 1, if angles not [shown]' - tolerance on the stated angle.", True, False),
    ("4.2.5", 2, "Mechanics-Forces", "Definition/Explain",
     "Explain why using a longer rope could allow the horse to move the boat at the same velocity but with "
     "a lower tension in the rope.",
     True, [], "longer rope means a smaller angle, so the same component is achieved with lower tension",
     ["longer rope -> smaller angle (1)", "same component with lower tension (1)"],
     "Two linked reasoning steps; order implied by the memo's two marks.", True, False),

    # ---------------- QUESTION 5: NEWTON'S LAWS / FRICTION (24 marks) ----------------
    ("5.1", 2, "Mechanics-Forces", "Definition/Explain",
     "State Newton's first law. (box of mass 200 kg on the back of a truck, not tied down)",
     True, [],
     "An object continues in a state of rest or uniform (constant) velocity unless acted upon by a net or "
     "resultant force",
     ["state of rest or uniform velocity (1)", "unless acted on by a net/resultant force (1)"],
     "Both clauses of the law are separately marked.", True, False),
    ("5.2", 2, "Mechanics-Forces", "Definition/Explain",
     "Define friction.",
     False, [], "the force that opposes the motion of an object and acts parallel to the surface in contact",
     ["opposes motion (1)", "parallel to the contact surface (1)"], "Two-part definition.", False, False),
    ("5.3.1", 4, "Mechanics-Forces", "Definition/Explain",
     "The maximum frictional force between truck and box is 570 N. Refer to Newton's first law to explain "
     "why this limits the maximum acceleration the truck can have without the box falling off.",
     True, [],
     "external force acts on the truck; the inertia of the box resists the change in motion; friction is not "
     "great enough to accelerate the box with the truck, hence it slides off",
     ["external force applied to the truck (1)", "inertia of the box resists change in motion (1)",
      "friction not great enough to accelerate box with truck (1)", "hence it slides off (1)"],
     "Four-mark structured explanation; memo allocates one mark per reasoning link.", True, False),
    ("5.3.2", 3, "Mechanics-Forces", "Short Answer",
     "Will the kinetic friction between the truck and the box be GREATER THAN, LESS THAN or EQUAL TO 570 N? "
     "Explain your answer.",
     True, [], "Less than, and once the box is in motion the surfaces interact less",
     ["less than (1)", "explanation: surfaces interact less once in motion"],
     "Choice plus justification; memo shows a 3-mark allocation for the combined response.", True, False),
    ("5.4", 4, "Mechanics-Forces", "Diagram-based",
     "The back of the truck is tilted at an angle theta. Draw a labelled free-body diagram of all the forces "
     "acting on the box.",
     True, [], "theta, normal force, weight, frictional force",
     ["theta (1)", "force normal (1)", "weight (1)", "frictional force (1)"],
     "One mark per correctly drawn and labelled force/angle.", True, False),
    ("5.5", 2, "Mechanics-Forces", "Short Answer",
     "Give the reaction force, with direction, of the weight of the box.",
     True, [], "the box pulling up on the Earth", ["box (1)", "pulling up on the Earth (1)"],
     "Newton's third law pair must be named with both body and direction.", True, False),
    ("5.6", 2, "Mechanics-Forces", "Calculation",
     "Write an equation to express the normal force in terms of Fg.",
     True, ["FN = Fg cos theta"], "FN = -Fg(mg) cos theta", ["FN = (1)", "Fg cos theta (1)"],
     "Equation form only; sign convention accepted as written in the memo.", True, False),
    ("5.7", 5, "Mechanics-Forces", "Calculation",
     "The angle theta is increased until the box is just about to slide. Calculate the angle that will cause "
     "the box to start sliding if the coefficient of static friction is 0,32. Show all your calculations.",
     True, ["Ff = mu FN"], "17,74 degrees",
     ["Ff(max) = mu FN", "mu = mg sin theta / mg cos theta = tan theta", "0,32 = tan theta", "theta = 17,74"],
     "Memo note: 'MUST show how you got tan' - the derivation of mu = tan theta is separately marked.", True, False),

    # ---------------- QUESTION 6: INVESTIGATION (14 marks) ----------------
    ("6.1", 3, "Experimental Investigation", "Experiment/Investigation",
     "A student wonders if there is a relationship between the speed of a truck entering an escape ramp and "
     "the length of ramp needed to stop. Write a hypothesis for the investigation.",
     True, [], "As the initial speed of the truck increases so the length of the ramp will have to increase",
     ["initial speed increases (1)", "length of ramp (1)", "will have to increase (1)"],
     "Memo note: 'order matters' - the hypothesis must state the variables in the correct dependent/independent order.", True, False),
    ("6.2", 2, "Experimental Investigation", "Experiment/Investigation",
     "The investigation is recreated with a Smart Cart and Chromebook. How could the student vary the initial "
     "velocity of the cart?",
     True, [], "By pushing it with different forces", ["pushing with different forces (2)"],
     "Practical method question; both marks for the method.", True, False),
    ("6.3", 1, "Experimental Investigation", "Calculation",
     "Data table of cart velocity, average displacement and velocity squared (0,5/0,07/0,25; 1,0/0,29/1,00; "
     "1,2/0,42/1,44; 1,6/0,75/2,56; 1,8/0,95/?). Calculate the missing value in the table.",
     False, [], "3,24", ["3,24 (1)"], "Single mark; squaring the last velocity value.", False, False),
    ("6.4", 6, "Experimental Investigation", "Data/Graph Interpretation",
     "Plot a graph of velocity squared (y-axis) vs average displacement (x-axis) on the graph paper provided.",
     True, [], "straight line through origin, y = 3,4035x",
     ["heading (1)", "labels and correct unit (1)", "scale (1)", "plotting (2)", "LOBF / line of best fit (1)"],
     "Memo breaks the 6 marks into heading, labels/units, scale, plotting and line of best fit.", True, False),
    ("6.5", 2, "Experimental Investigation", "Data/Graph Interpretation",
     "Draw a second line on the graph to show the effect of decreasing the angle theta. Label this line 6.5.",
     True, [], "second line with a smaller gradient than the first", ["correct second line (2)"],
     "Requires reasoning about gradient, not just drawing.", True, False),

    # ---------------- QUESTION 7: ELECTRIC CIRCUITS (26 marks) ----------------
    ("7.1", 2, "Electric Circuits", "Definition/Explain",
     "Define emf. (battery emf 14 V connected to a resistor network; R1 = 6,0 ohm, R2 = 12 ohm, R3 rheostat)",
     True, [], "the total energy supplied per coulomb of charge by the cell",
     ["total energy supplied per coulomb (1)", "by the cell (1)"], "Two-part definition.", True, False),
    ("7.2", 2, "Electric Circuits", "Calculation",
     "Calculate the resistance of the circuit when the switch is open.",
     True, ["R = R1 + R2"], "18 ohm", ["Rs = 6 + 12", "= 18 ohm"],
     "Series combination only; two marks.", True, False),
    ("7.3", 1, "Electric Circuits", "Definition/Explain",
     "What is a short circuit?",
     False, [], "a low resistance connection (established by accident or intention)",
     ["low resistance connection (1)"], "Single mark definition.", False, False),
    ("7.4.1", 4, "Electric Circuits", "Calculation",
     "Switch S is closed. Calculate the current in the battery when the resistance of R3 is set at zero.",
     True, ["I = V/R"], "2,33 A",
     ["I = V/R", "= 14/6", "= 2,33 A"],
     "Memo note: 'if the rheostat is at zero, no current will flow through R2' - recognising the shorted branch is required.", True, False),
    ("7.4.2", 4, "Electric Circuits", "Calculation",
     "Calculate the current in the battery when the resistance of R3 is set at 24 ohm.",
     True, ["1/Rp = 1/R1 + 1/R2", "I = V/R"], "1 A",
     ["total resistance of parallel resistors = 8,0 ohm (2)", "current = 14/(6,0 + 8,0)", "= 1 A (2)"],
     "Parallel combination carries 2 marks; final current carries 2.", True, False),
    ("7.5.1", 2, "Electric Circuits", "Calculation",
     "R3 is set to 24 ohm. Calculate the total power produced by the battery.",
     True, ["P = VI", "P = V2/R", "P = I2R"], "14 W",
     ["P = EI (allow P = VI, P = V2/R, P = I2R)", "power = 14 x 1", "= 14 W"],
     "Memo allows any of three power formulae; 'c.o.e.' applied to the substituted current.", True, False),
    ("7.5.2", 3, "Electric Circuits", "Calculation",
     "Calculate the voltage drop across R1.",
     True, ["V = IR"], "6 V", ["V = I x R", "= 1 x 6", "6 V"], "Three marks: formula, substitution, answer.", True, False),
    ("7.6", 3, "Electric Circuits", "Data/Graph Interpretation",
     "Sketch a graph of voltage across R1 versus resistance of R3 as R3 changes from 0 to 24 ohm.",
     True, [], "rising curve from 0 V toward 6 V as R3 increases",
     ["correct shape and trend (3)"], "Memo shows the expected curve as an image.", True, False),
    ("7.7.1", 1, "Electric Circuits", "Short Answer",
     "The rheostat is now removed. Will the power dissipated in R1 increase, decrease or remain the same?",
     True, [], "decrease", ["decrease (1)"], "Single mark for the qualitative prediction.", True, False),
    ("7.7.2", 4, "Electric Circuits", "Definition/Explain",
     "Justify your answer in 7.7.1 making reference to two relevant formulae.",
     True, ["I = V/R", "P = I2R"],
     "As circuit R increases I decreases; as I decreases P decreases since P = I2R and R is constant",
     ["as circuit R increases, I decreases (1)", "I = V/R quoted (1)",
      "as I decreases P decreases (1)", "P = I2R with R constant (1)"],
     "Four marks require TWO named formulae plus the causal chain; the memo numbers this answer '7.5.2' in error.", True, True),
]
