"""Pass 1 evidence table — Grade 11 Physical Science Paper 1, 15 November 2021 (final).

Paper:  data/organized/physics/PS11 Physics November Exam 2021 QP.pdf (200 marks, Mr D. du Toit)
Memo:   data/organized/physics/PS11 Physics November Exam 2021 MG.pdf (200 marks)
"""

PAPER = {
    "paper_key": "PHY-2021-NOV",
    "paper_path": "data/organized/physics/PS11 Physics November Exam 2021 QP.pdf",
    "memo_path": "data/organized/physics/PS11 Physics November Exam 2021 MG.pdf",
    "year": 2021,
    "exam_date": "15 November 2021",
    "exam_period": "nov",
    "paper_type": "paper1",
    "exam_board": "internal",
    "total_marks": 200,
    "examiner": "Mr D. du Toit",
    "moderator": "Mrs S. Govender / Mr F. McCoy",
    "duration_stated": {"paper": "3 hours", "memo": "3 hours"},
    "fidelity_rung": "A",
    "notes": (
        "Memo uses 'coe' (consequential/consistent-with-earlier-error) markers extensively and names a "
        "different marker per question (Mr Ntombela, Mr du Toit, Mrs Govender, Mr McCoy)."
    ),
}

SCHEMA = (
    "qn", "marks", "topic", "qtype", "text", "has_diagram", "formulae",
    "memo_answer", "memo_steps", "memo_notes", "needs_visual", "ocr_uncertain",
)

RECORDS = [
    # ---------------- QUESTION 1: MULTIPLE CHOICE (20 marks) ----------------
    ("1.1", 2, "Mechanics-Vectors", "Multiple Choice",
     "Two displacement vectors of magnitudes 20 cm and 80 cm are added. Which is the ONLY possible choice for "
     "the magnitude of the resultant? A 0 cm / B 28 cm / C 82 cm / D 114 cm",
     False, [], "C", [], "Memo gives option only (C, 2 ticks).", False, False),
    ("1.2", 2, "Mechanics-Motion", "Multiple Choice",
     "Object moves in +x with positive velocity and positive constant acceleration; after 3 s acceleration "
     "becomes constant negative. Which row is correct for velocity and displacement immediately after 3 s? "
     "(A decreases and remains positive / increases; B decreases and becomes negative / increases; "
     "C increases and remains positive / decreases; D increases and becomes negative / decreases)",
     False, [], "A", [], "Memo gives option only.", False, False),
    ("1.3", 2, "Mechanics-Motion", "Multiple Choice",
     "Athlete runs at constant speed anticlockwise around a track. Which statement is true of the instantaneous "
     "velocity from X to Z via Y? A constant X-Y only / B constant Y-Z only / C constant at all points X-Z / "
     "D never constant anywhere between X and Z",
     True, [], "B", [], "Memo gives option only; track diagram is an image.", True, False),
    ("1.4", 2, "Mechanics-Motion", "Multiple Choice",
     "An object thrown vertically upward accelerates at 9,8 m.s-2 downwards (no air resistance). Which statement "
     "is true? A travels 9,8 m in the first second / B travels an extra 9,8 m each second / C speeds up at "
     "9,8 m.s-1 each second / D speed changes at a rate of 9,8 m.s-1 each second",
     False, [], "D", [], "Memo gives option only.", False, False),
    ("1.5", 2, "Mechanics-Forces", "Multiple Choice",
     "Force F acts on a box of mass m which remains stationary. Which is the correct expression for the normal "
     "force? (options given as mg +/- F sin theta and mg +/- F cos theta)",
     True, [], "B", [], "Memo gives option only; options contain garbled sub/superscripts in extraction.", True, True),
    ("1.6", 2, "Mechanics-Forces", "Multiple Choice",
     "A person stands on a scale in an elevator and the reading is lower than his usual weight. Which could "
     "describe the motion? A down at constant speed / B down and slowing / C up and slowing / D up and speeding up",
     False, [], "C", [], "Memo gives option only.", False, False),
    ("1.7", 2, "Mechanics-Forces", "Multiple Choice",
     "A laptop rests on a table. According to Newton's third law, what is the reaction force to the weight of "
     "the laptop? A upward force of table on laptop / B upward force of laptop on the Earth / C downward force "
     "of Earth on laptop / D the normal force on the laptop",
     False, [], "B", [], "Memo gives option only.", False, False),
    ("1.8", 2, "Work Energy Power", "Multiple Choice",
     "A steam turbine drives a generator; input power PI, output power PO, power loss PL. What is the "
     "efficiency of the turbine? (options: (PI-PL)/PI, PO/(PI-PL), (PI-PL)/PO, PO/(PI-PL) forms)",
     True, [], "A", [], "Memo gives option only; options are garbled fractions in extraction.", True, True),
    ("1.9", 2, "Electric Circuits", "Multiple Choice",
     "The current in a cell is 10 A as shown. What is the current in the 2 ohm resistor? "
     "A 0,35 A / B 2,86 A / C 3,50 A / D 7,14 A",
     True, [], "B", [], "Memo gives option only; circuit diagram is an image.", True, False),
    ("1.10", 2, "Waves Sound Light", "Multiple Choice",
     "Given the energy level diagram for an atom, which electron transition corresponds to the light released "
     "with the longest wavelength?",
     True, [], "D", [], "Memo gives option only; energy-level diagram is an image.", True, False),

    # ---------------- QUESTION 2: HORIZONTAL MOTION / VECTORS (25 marks) ----------------
    ("2.1.1", 4, "Mechanics-Motion", "Definition/Explain",
     "Soccer player runs 20 m due East in 10 s from A to B, then to C (20 m East and 30 m North of B) in a "
     "further 10 s. What is the difference between distance and displacement? Illustrate with an example of "
     "each, referring to positions A, B and C.",
     True, [],
     "Distance = length of path travelled (A to B 20 + B to C 36 = 56 m); displacement = change in position "
     "(straight line / shortest distance from A to C)",
     ["distance: length of path travelled (1)", "worked example 20 + 36 = 56 m (1)",
      "displacement: change in position (1)", "straight line A to C (1)"],
     "Both the definition AND the numerical illustration are marked for each term.", True, False),
    ("2.1.2", 2, "Mechanics-Motion", "Definition/Explain",
     "Define speed.",
     False, [], "rate of change of distance", ["rate of change of distance (2)"],
     "Memo note 'AON' (any other correct wording accepted).", False, False),
    ("2.1.3", 3, "Mechanics-Motion", "Calculation",
     "Calculate the player's average speed from A to C.",
     True, ["speed = distance/time"], "2,8 m.s-1",
     ["speed = distance/time", "= 56/20", "= 2,8 m.s-1"],
     "Requires the total path length (56 m) and total time (20 s).", True, False),
    ("2.1.4", 4, "Mechanics-Vectors", "Diagram-based",
     "Draw a fully labelled 90-degree vector-addition triangle showing the player's resultant change in "
     "position from A to C. Include known values.",
     True, [], "right-angle triangle with 20 m and 30 m sides and resultant from tail of first to head of last",
     ["resultant with arrow from tail of first vector to head of last (1)", "90 degrees and theta (1)",
      "20 m with arrow (1)", "30 m with arrow (1)"],
     "One mark per required diagram feature.", True, False),
    ("2.1.5", 5, "Mechanics-Motion", "Calculation",
     "Calculate the magnitude of the player's average velocity from A to C.",
     True, ["Pythagoras", "tan-1", "v = d/t"], "2,5 m.s-1 at 36,87 degrees N of E (bearing 53,13 degrees)",
     ["R = sqrt(40^2 + 30^2) (Pythagoras)", "= 50 m", "tan-1(30/40) = 36,87 degrees or tan-1(40/30) = 53,13 degrees",
      "v = d/t = 50/20 = 2,5 m.s-1", "direction stated"],
     "Memo note: 'Mark question based on 2.1.4 diagram' - the answer is marked consistently with the candidate's "
     "own diagram (ecf).", True, False),
    ("2.2.1", 5, "Mechanics-Motion", "Calculation",
     "Paul rides past at constant 6 m.s-1; John gives him a 3 s head start then accelerates from rest at "
     "1,2 m.s-2. Calculate the time taken from when John sets off to when he catches up with Paul.",
     False, ["v = s/t", "s = ut + 1/2 at2"], "12,42 s",
     ["Paul: 6 = s/(x+3) -> s = 6x + 18", "John: s = 0 + 1/2(1,2)(x^2) = 0,6x^2",
      "equate: 6x + 18 = 0,6x^2", "x = 12,42 s"],
     "Requires setting up two equations of motion and solving the resulting quadratic.", False, False),
    ("2.2.2", 2, "Mechanics-Motion", "Calculation",
     "Calculate the distance from John's driveway to the position where he catches up with Paul.",
     False, [], "92,50 m", ["s = 6(12,42) + 18 (coe 2.2.1)", "s = 92,50 m (coe 2.2.1)",
     "OR s = 0,6(12,42^2) = 92,50 m"],
     "Memo marks both marks 'coe 2.2.1' - credit follows from the candidate's own 2.2.1 value.", False, False),

    # ---------------- QUESTION 3: VERTICAL MOTION / GRAPHS (28 marks) ----------------
    ("3.1", 2, "Mechanics-Motion", "Definition/Explain",
     "Define velocity. (object projected vertically upwards from a cliff, bounces; v-t graph given with points "
     "A-F)",
     True, [], "rate of change of position", ["rate of change of position (2)"], "Two marks for the definition.", True, False),
    ("3.2", 2, "Mechanics-Motion graphs", "Data/Graph Interpretation",
     "What is the magnitude and direction of the initial velocity of the object?",
     True, [], "8 m.s-1 up", ["8 m.s-1 (1)", "up (1)"], "Magnitude and direction separately marked.", True, False),
    ("3.3", 2, "Mechanics-Motion graphs", "Data/Graph Interpretation",
     "Describe the motion of the object from A to B.",
     True, [], "decreasing velocity up OR uniform acceleration down",
     ["decreasing velocity (1)", "up (1)", "OR uniform acceleration (1)", "down (1)"],
     "Memo accepts either of two equivalent descriptions.", True, False),
    ("3.4", 3, "Mechanics-Motion", "Calculation",
     "Calculate the time taken for the object to reach point B.",
     True, ["v = u + gt"], "0,82 s", ["0 = -8 + 9,8t", "t = 0,82 s"],
     "Sign convention for the initial (upward) velocity is explicitly marked.", True, False),
    ("3.5", 3, "Mechanics-Motion", "Calculation",
     "Use the graph to calculate the distance the ball travelled from its maximum height to the ground.",
     True, ["area = 1/2 b.h", "s = ut + 1/2 gt2"], "187,37 m",
     ["area = 1/2 (7 - 0,82 coe 3.4)(60,6) = 187,37 m",
      "OR s = (0)(7 - 0,82) + 1/2(9,8)(7 - 0,82)^2 = 187,37 m"],
     "Time interval must be taken from the candidate's own 3.4 value (coe).", True, False),
    ("3.6", 3, "Mechanics-Motion", "Calculation",
     "Use the graph to calculate the height of the cliff.",
     True, ["s = ut + 1/2 gt2"], "184,10 m",
     ["187,37 (coe 3.5) - 1/2(8)(0,82 coe 3.4) = 184,10 m",
      "OR s = (-8)(0,82) + 1/2(9,8)(0,82)^2 = 3,27 m; 187,37 - 3,27 = 184,10 m"],
     "Two alternative routes both accepted; both depend on earlier answers (coe).", True, False),
    ("3.7", 2, "Mechanics-Motion graphs", "Data/Graph Interpretation",
     "Relative to the ground, where is the object in its motion at time F?",
     True, [], "maximum height after bounce", ["maximum height (1)", "after bounce (1)"],
     "Both the state and the phase of the motion are marked.", True, False),
    ("3.8", 4, "Mechanics-Motion graphs", "Diagram-based",
     "Draw a position versus time graph for the entire motion, taking the point of release as reference, and "
     "label the time to maximum height, the height of the cliff and points A-F.",
     True, [], "position-time curve as shown in memo",
     ["values: time to max height and height of cliff (1)", "A to B shape (1)",
      "B to C shape (1)", "E to F shape (1)"],
     "Memo note: '-1 if inverted'.", True, False),
    ("3.9", 2, "Mechanics-Forces", "Diagram-based",
     "Draw a free-body diagram showing all the forces acting on the ball at point D (during contact with the "
     "ground).",
     True, [], "weight plus normal/ground force greater than weight",
     ["weight (1)", "Fnormal or Fground on ball greater than weight (1)"],
     "The relative size of the two forces is part of the mark.", True, False),
    ("3.10", 5, "Mechanics-Momentum", "Calculation",
     "If the mass of the ball is 0,6 kg, calculate the magnitude of the force that the ground exerts on the "
     "ball while it is in contact with the ground.",
     True, ["a = gradient = dy/dx", "Fnet = ma", "Fnet = FN + Fg"], "-223,68 N",
     ["a = gradient = (60,6 - (-120))/(7 - 7,2) = -363 m.s-2", "Fnet = ma = (0,6)(-363) = -217,8 N",
      "Fnet = FN + Fg; -217,8 = FN + (0,6)(9,8)", "FN = -223,68 N"],
     "Gradient must be read from the contact portion of the graph; both marks for the weight term.", True, False),

    # ---------------- QUESTION 4: NEWTON'S LAWS / BRAKING (17 marks) ----------------
    ("4.1", 2, "Mechanics-Forces", "Diagram-based",
     "Truck (10 800 kg) at 22 m.s-1 carrying a granite block (160 000 kg) brakes suddenly. Draw a labelled "
     "free-body diagram showing the horizontal force(s) on the granite block while braking, and indicate the "
     "direction of the truck's acceleration.",
     True, [], "friction force and acceleration direction",
     ["Ffriction (1)", "a (1)"], "One mark per required element.", True, False),
    ("4.2", 4, "Mechanics-Forces", "Definition/Explain",
     "With reference to one of Newton's Laws, explain the movement of the granite block.",
     True, [],
     "the external force acts on the truck; the inertia of the block resists a change in motion; the friction "
     "between block and truck is not enough to accelerate it with the truck",
     ["external force acts on the truck (1)", "inertia (1)", "resists a change in motion (1)",
      "friction not enough to accelerate it with the truck (1)"],
     "Four separate reasoning links each carry a mark; the same structure recurs in the 2019 paper (5.3.1).", True, False),
    ("4.3.1", 2, "Mechanics-Motion", "Definition/Explain",
     "Define acceleration.",
     False, [], "rate of change of velocity", ["rate of change of velocity (2)"],
     "Memo note 'AON'.", False, False),
    ("4.3.2", 4, "Mechanics-Motion", "Calculation",
     "The tyre marks were 38,2 m long from braking to stopping. Calculate the acceleration of the truck.",
     True, ["v2 = u2 + 2as"], "-6,34 m.s-2",
     ["v2 = u2 + 2as", "0^2 = 22^2 + 2a(38,2)", "a = 6,34 m.s-2", "negative sign shown"],
     "Memo explicitly marks the negative sign as a separate mark.", True, False),
    ("4.3.3", 2, "Mechanics-Forces", "Calculation",
     "Calculate the magnitude of the braking force exerted on the truck while it was brought to a standstill.",
     True, ["Fnet = ma"], "69769,07 N", ["Fnet = ma", "= (10 800)(-6,34)", "= -69769,07 N"],
     "Uses the candidate's own 4.3.2 acceleration.", True, False),
    ("4.3.4", 3, "Mechanics-Forces", "Definition/Explain",
     "The driver states the company should place a rubber mat under such heavy loads. Using a relevant physics "
     "equation, explain why this is a good idea to prevent such an accident in future.",
     True, ["Ff = mu FN"],
     "using rubber will increase the friction; mu increases; Ff is proportional to mu (for the same FN)",
     ["using rubber will increase the friction (1)", "mu increases (1)",
      "Ff proportional to mu for the same FN, equation quoted (1)"],
     "A named equation linking friction to mu is required for the third mark.", True, False),

    # ---------------- QUESTION 5: NEWTON'S SECOND LAW / CONNECTED BODIES (20 marks) ----------------
    ("5.1", 4, "Mechanics-Forces", "Diagram-based",
     "Block A (3 kg) and block B (2 kg) joined by a cord over a frictionless pulley; horizontal force F = 10 N "
     "on A; B slides up a rough 30-degree plane; A experiences 14,7 N friction. Draw a fully labelled "
     "free-body diagram showing all forces on block B.",
     True, [], "tension, weight, normal force, friction (tension > friction)",
     ["one mark for each force (4)"],
     "Memo note: 'Tension force > Friction force' - relative magnitudes must be drawn correctly.", True, False),
    ("5.2", 2, "Mechanics-Forces", "Definition/Explain",
     "Define friction force.",
     False, [], "a force that opposes motion of an object and acts parallel to the surface in contact",
     ["opposes motion (1)", "parallel to the contact surface (1)"], "Same two-part definition as 2019 Q5.2.", False, False),
    ("5.3", 3, "Mechanics-Forces", "Calculation",
     "Calculate the magnitude of the frictional force acting on block B if the coefficient of kinetic friction "
     "is 0,5.",
     True, ["Ff = mu_k FN"], "8,49 N", ["Ff = mu_k FN", "= (0,5)(2)(9,8)cos30", "= 8,49 N"],
     "Normal force on the incline requires the cos30 component.", True, False),
    ("5.4", 2, "Mechanics-Forces", "Definition/Explain",
     "State Newton's second law of motion.",
     False, [],
     "when a net force acts on an object it accelerates in the direction of the net force; acceleration is "
     "directly proportional to the net force and inversely proportional to the mass",
     ["acceleration in direction of net force (1)", "proportional to net force / inversely to mass (1)"],
     "Two clauses marked separately.", False, False),
    ("5.5", 5, "Mechanics-Forces", "Calculation",
     "Calculate the acceleration of the system.",
     True, ["Fnet = ma"], "4,34 m.s-2",
     ["Block A: Fnet = ma; 40 - T = 3a",
      "Block B: T - (2)(9,8)sin30 - 8,49 (coe 5.3) = 2a",
      "combine to solve for a", "a = 4,34 m.s-2",
      "OR system method: 40 - 2(9,8)sin30 - 8,49 = (5)a"],
     "Memo accepts either the two-body or the whole-system method. NOTE: the memo substitutes 40 N for the "
     "applied force although the question paper states F = 10 N - see unresolved item.", True, False),
    ("5.6", 2, "Mechanics-Forces", "Calculation",
     "Calculate the magnitude of the tension in the cord.",
     True, [], "26,98 N", ["40 - T = 3(4,34) (coe 5.5)", "T = 26,98 N"],
     "Both marks marked 'coe 5.5'.", True, False),
    ("5.7", 2, "Mechanics-Forces", "Short Answer",
     "While block B is accelerating up the slope the cord snaps. How does the acceleration of block A change "
     "after the cord snaps? Write INCREASE, DECREASE or REMAIN THE SAME.",
     True, [], "Increases", ["increases (2)"],
     "Qualitative reasoning question worth 2 marks for the single word.", True, False),

    # ---------------- QUESTION 6: WORK, ENERGY, POWER (24 marks) ----------------
    ("6.1.1", 2, "Work Energy Power", "Definition/Explain",
     "Define work. (smart cart pushed up a slope, free-wheels to rest, returns down)",
     True, [], "the product of the displacement and the component of the force parallel to the displacement",
     ["displacement (1)", "component of force parallel to displacement (1)"], "Two-part definition.", True, False),
    ("6.1.2", 2, "Work Energy Power", "Definition/Explain",
     "Explain what is meant by 'positive' and 'negative' work.",
     False, [], "positive work: object gains energy; negative work: object loses energy",
     ["positive work -> gains energy (1)", "negative work -> loses energy (1)"], "One mark each.", False, False),
    ("6.1.3", 1, "Work Energy Power", "Short Answer",
     "Which force always does negative work when the cart moves up and down the slope?",
     True, [], "frictional force", ["frictional force (1)"], "Single mark.", True, False),
    ("6.1.4", 3, "Mechanics-Forces", "Definition/Explain",
     "How does the acceleration of the cart up the slope compare with the acceleration down the slope? Explain "
     "using a relevant physics equation.",
     True, ["Fnet = ma"], "a_up > a_down; Fnet is proportional to a; Fnet is greater on the way up as friction "
     "and Fg-parallel act in the same direction",
     ["a_up > a_down (1)", "Fnet proportional to a (1)",
      "Fnet greater up the slope because friction and Fg-parallel are in the same direction (1)"],
     "Comparison, equation and physical reason each carry a mark.", True, False),
    ("6.1.5", 3, "Mechanics-Motion graphs", "Diagram-based",
     "Sketch a velocity versus time graph for the cart up and down the track, taking down the ramp as "
     "negative. Label the point where the cart comes to rest as X.",
     True, [], "negative-slope line up to zero at X, then negative-slope line below the axis",
     ["negative gradients (1)", "X marked at zero velocity (1)",
      "gradient steeper on the way up than down (1)"],
     "The relative steepness of the two gradients is separately marked.", True, False),
    ("6.2.1", 3, "Work Energy Power", "Short Answer",
     "A 70 kg crate slides along a rough horizontal surface with applied force 234,63 N and friction 190 N, "
     "passing K at 4 m.s-1 and L 18 m further on. Which forces on the crate do no work? Explain briefly.",
     True, [], "normal force and weight, because they are perpendicular to the displacement",
     ["normal force (1)", "weight (1)", "perpendicular to displacement (1)"],
     "Two forces plus the reason.", True, False),
    ("6.2.2", 3, "Work Energy Power", "Calculation",
     "Calculate the kinetic energy of the crate at point K.",
     True, ["Ek = 1/2 mv2"], "560 J", ["Ek = 1/2 mv2", "= 1/2(70)(4)^2", "= 560 J"],
     "Formula, substitution, answer.", True, False),
    ("6.2.3", 2, "Work Energy Power", "Definition/Explain",
     "State the work-energy theorem.",
     False, [], "the work done by a net force on an object is equal to the change in kinetic energy of the object",
     ["work done by net force (1)", "equals change in kinetic energy (1)"], "Two-part statement.", False, False),
    ("6.2.4", 5, "Work Energy Power", "Calculation",
     "Use the work-energy theorem to calculate the speed of the crate as it passes point L.",
     True, ["Wnet = dEk"], "6,24 m.s-1",
     ["Wnet = dEk", "(234,63 - 190)(18)", "= 1/2(70)v2 - 560 (coe 6.2.2)", "v = 6,24 m.s-1"],
     "Net force must be formed from applied minus friction; the 560 J may follow from 6.2.2.", True, False),

    # ---------------- QUESTION 7: ELECTRIC CIRCUITS (27 marks) ----------------
    ("7.1.1", 2, "Electric Circuits", "Definition/Explain",
     "Define resistance. (battery emf 16 V; ammeter and cell have negligible resistance; no current through "
     "the voltmeter; switch S closed)",
     True, [], "a material's opposition to the flow of electrical current",
     ["opposition to flow of current (2)"], "Memo note 'AON'.", True, False),
    ("7.1.2", 4, "Electric Circuits", "Calculation",
     "Calculate the effective resistance of the circuit.",
     True, ["1/Rp = 1/R1 + 1/R2", "Rs = R1 + R2"], "8 ohm",
     ["1/Rp = 1/4 + 1/12", "= 1/3 -> Rp = 3 ohm", "Rt = 3 + 5 = 8 ohm"],
     "Parallel step and series step separately marked.", True, False),
    ("7.1.3", 4, "Electric Circuits", "Calculation",
     "The 4 ohm resistor has a power rating of 9 W. Calculate the reading on ammeter A.",
     True, ["P = I2R"], "1,5 A", ["P = I2R", "9 = I2(4)", "I = 1,5 A"],
     "Power rating used in reverse to find current.", True, False),
    ("7.1.4", 3, "Electric Circuits", "Calculation",
     "Calculate the reading on voltmeter V1.",
     True, ["V = IR"], "6 V", ["V = IR", "= (1,5)(4)", "= 6 V (coe 7.1.3)"], "Marked 'coe 7.1.3'.", True, False),
    ("7.1.5", 3, "Electric Circuits", "Calculation",
     "Calculate the current through the 5 ohm resistor.",
     True, ["V = IR"], "2 A",
     ["16 - 6 = 10 V (coe 7.1.4)", "10 = I(5)", "I = 2 A",
      "OR 16 = I(8) (coe 7.1.2) -> I = 2 A"],
     "Two alternative routes accepted.", True, False),
    ("7.1.6", 1, "Electric Circuits", "Short Answer",
     "Switch S is now opened. What happens to the reading on the voltmeter connected across the battery? "
     "INCREASES, DECREASES or REMAINS THE SAME.",
     True, [], "Remains the same", ["remains the same (1)"], "Single mark qualitative prediction.", True, False),
    ("7.1.7", 4, "Electric Circuits", "Definition/Explain",
     "What happens to the reading on voltmeter V1? State INCREASES, DECREASES or REMAINS THE SAME and fully "
     "explain using a relevant physics formula.",
     True, ["V = IR"], "Increases; V is proportional to I (R constant); I through the 4 ohm resistor increases",
     ["increases (1)", "V proportional to I with R constant (1)", "formula quoted (1)",
      "I increases through 4 ohm (1)"],
     "Prediction plus a formula-based causal chain.", True, False),
    ("7.2.1", 2, "Work Energy Power", "Definition/Explain",
     "Define power. (same cell connected to two circuits; bulb K has twice the resistance of bulb L)",
     True, [], "the rate at which work is done (or the rate at which energy is transferred)",
     ["rate at which work is done / energy transferred (2)"], "Memo note 'AON'.", True, False),
    ("7.2.2", 4, "Electric Circuits", "Definition/Explain",
     "How does the brightness of bulb K compare with that of bulb L in each of these circuits? Explain.",
     True, ["P = V2/R", "P = I2R"],
     "L is brighter than K in circuit 1 (power inversely proportional to R at constant voltage); K is "
     "brighter than L in circuit 2 (power directly proportional to R at constant current)",
     ["L brighter than K in circuit 1 (1)", "P inversely proportional to R at constant V (1)",
      "K brighter than L in circuit 2 (1)", "P directly proportional to R at constant I (1)"],
     "Requires two different proportionalities for series vs parallel - four separate marks.", True, False),

    # ---------------- QUESTION 8: GRAVITATION INVESTIGATION (26 marks) ----------------
    ("8.1.1", 2, "Mechanics-Gravitation", "Data/Graph Interpretation",
     "Table of gravitational force between two identical spheres at different separations. The diagram shows "
     "the masses 8 m apart. Read off the force experienced and write it in the table on the answer sheet.",
     True, [], "0,518 (x10-8 N)", ["0,518 (2)"], "Read from a simulation diagram (answer sheet).", True, False),
    ("8.1.2", 2, "Mechanics-Gravitation", "Calculation",
     "Calculate the value in the last column (inverse of distance between centres squared) and write it in "
     "the table on the answer sheet.",
     True, [], "0,016 m-2", ["0,016 (2)"], "Single calculation; two marks.", True, False),
    ("8.2", 7, "Mechanics-Gravitation", "Data/Graph Interpretation",
     "Plot a graph of inverse of distance squared vs force on the answer sheet. You must use the scale given.",
     True, [], "straight line through the origin",
     ["heading: inverse of distance between centres squared (x10-2 m-2) (1)",
      "axis label: force experienced (x10-8 N) (1)", "scale (1)", "plotting (2)", "LOBF (1)"],
     "Seven marks allocated across heading, axis labels/units, scale, plotting and line of best fit.", True, False),
    ("8.3", 2, "Mechanics-Gravitation", "Short Answer",
     "Write the relationship between these variables in words.",
     True, [], "the force experienced is inversely proportional to the distance between centres squared",
     ["inversely proportional (1)", "to the distance between centres squared (1)"],
     "Memo note: 'order' - the wording order matters.", True, False),
    ("8.4", 3, "Mechanics-Gravitation", "Data/Graph Interpretation",
     "Use your graph to determine the force the spheres would experience if 4,5 m apart. Show how you "
     "determined this on your graph.",
     True, [], "1,65 x 10-8 N", ["1/4,5^2 = 0,049 = 4,9 x 10-2", "= 1,65 x 10-8 N"],
     "Requires the reciprocal-square conversion before reading the graph.", True, False),
    ("8.5", 4, "Mechanics-Gravitation", "Calculation",
     "Calculate the gradient of the graph. Include a unit.",
     True, ["gradient = dy/dx"], "3 x 10^6 m-2.N-1",
     ["gradient = dy/dx", "= (0,018 - 0)/(0,6 x 10-8 - 0)", "= 3 x 10^6", "unit m-2.N-1"],
     "A unit is explicitly required for one of the four marks.", True, False),
    ("8.6", 3, "Mechanics-Gravitation", "Definition/Explain",
     "What physical quantities are represented by the gradient?",
     True, ["gradient = r-2/F = 1/(G m1 m2)"], "1/(G m1 m2)",
     ["gradient = r-2/F = 1/(F.r2)", "equating with F = Gm1m2/r2 gives 1/(G m1 m2)"],
     "Requires algebraic identification of the gradient's physical meaning.", True, False),
    ("8.7", 3, "Mechanics-Gravitation", "Calculation",
     "Hence, use your answers in 8.5 and 8.6 to determine the mass of each sphere.",
     True, ["3 x 10^6 = 1/(G m^2)"], "70 kg (each)",
     ["3 x 10^6 = 1/(6,7 x 10-11 . x^2)", "x = +- 70 kg"],
     "Chained from two previous answers.", True, False),

    # ---------------- QUESTION 9: PHOTONS / ENERGY LEVELS (13 marks) ----------------
    ("9.1", 1, "Waves Sound Light", "Short Answer",
     "The energy levels for a hydrogen atom are shown; an excited electron is in the 3rd level. How many "
     "unique frequencies will be in the emission spectrum as the electron returns to the ground state?",
     True, [], "3", ["3 (1)"], "Single mark.", True, False),
    ("9.2", 4, "Waves Sound Light", "Calculation",
     "Calculate the frequency of the photon emitted when the electron transition is from the n = 2 level to "
     "the ground state.",
     True, ["E = hf"],
     "unresolved - the memo's worked answer for 9.2 is an image; only the tick allocation (4 marks) is extractable",
     [], "Memo answer not extractable as text; requires visual verification of the marking guidelines image.", True, True),
    ("9.3", 4, "Waves Sound Light", "Calculation",
     "Hydrogen gas in a discharge tube emits light of wavelength 655 nm. Calculate the energy (in eV) that "
     "corresponds to this wavelength.",
     True, ["E = hc/lambda"],
     "unresolved - the memo's worked answer for 9.3 is an image; only the tick allocation (4 marks) is extractable",
     [], "Memo answer not extractable as text; requires visual verification.", True, True),
    ("9.4", 2, "Waves Sound Light", "Short Answer",
     "Which transition will result in a wavelength of 655 nm?",
     True, [],
     "unresolved - the memo's answer for 9.4 is an image; only the tick allocation (2 marks) is extractable",
     [], "Memo answer not extractable as text; requires visual verification.", True, True),
    ("9.5", 2, "Waves Sound Light", "Definition/Explain",
     "Why are the energy levels stated as negative values?",
     True, [],
     "unresolved - the memo's answer for 9.5 is an image; only the tick allocation (2 marks) is extractable",
     [], "Memo answer not extractable as text; requires visual verification.", True, True),
]
