#!/usr/bin/env python3
"""Auditable entry point for english's requested Pass 1 + Pass 2, not later phases."""
from __future__ import annotations
import json
import re
import subprocess
import sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from core.runlog import RunLogger, sha256_file  # noqa: E402
from scripts.build_english_pass1 import docx_text, pdf_text  # noqa: E402
REVIEW_QUEUE = ROOT / 'review_queue/RQ-P4-ENG-PASS2.yaml'


def write_review_queue(run_id, unresolved):
    items = []
    for u in unresolved:
        items.append({'id': u['id'], 'type': u['type'], 'issue': u['summary'], 'detail': u['detail'],
                      'affected_entity': u['affected'], 'evidence': u['evidence'],
                      'possible_resolutions': [u['recommended_review'],
                                               'Retain the unresolved item and exclude unsupported claims from the knowledge bank.'],
                      'recommended_review': u['recommended_review']})
    REVIEW_QUEUE.write_text(yaml.safe_dump({'review_id': 'RQ-P4-ENG-PASS2', 'run_id': run_id,
                                            'subject': 'english', 'phase': '4-11', 'item_count': len(items),
                                            'items': items}, sort_keys=False, allow_unicode=True))


def corpus_audit(batch):
    """Metadata-only audit of all 21 organised English sources, including the ones not admitted."""
    used = {r[k] for r in batch for k in ['source_document', 'memo_document']}
    audit = []
    for path in sorted((ROOT / 'data/organized/english').iterdir()):
        if path.suffix.lower() not in {'.docx', '.pdf'}:
            continue
        rel = str(path.relative_to(ROOT))
        text = docx_text(path) if path.suffix.lower() == '.docx' else pdf_text(path)
        flat = re.sub(r'\s+', ' ', text)[:6000]
        header = re.search(r'\bMARKS\s*:?\s*(\d{1,3})', flat)
        date = re.search(r'DATE\s*:?\s*((?:\d{1,2}\s+)?[A-Za-z]{3,9}\s*,?\s*\d{4})', flat)
        cover = re.search(r'Possible\s*Marks\s+((?:\d{1,3}\s+)+)', flat)
        cover_numbers = [int(n) for n in cover.group(1).split()] if cover else []
        kind = ('orphan_memo_2026' if '2026' in path.name else
                'memorandum' if ('Memo' in path.name or 'memo' in path.name) else 'question_paper')
        if rel in used:
            disposition = 'admitted'
        elif kind == 'orphan_memo_2026':
            disposition = 'rejected_no_matching_paper'
        elif kind == 'memorandum':
            disposition = 'no_matching_local_paper'
        else:
            disposition = 'no_matching_local_memo'
        audit.append({'path': rel, 'sha256': sha256_file(path), 'document_type': kind,
                      'printed_date': date.group(1) if date else None,
                      'printed_marks': int(header.group(1)) if header else None,
                      'printed_cover_row': cover_numbers,
                      'cover_row_sums_to_printed_marks': (
                          bool(cover_numbers) and bool(header) and sum(cover_numbers[:-1]) == int(header.group(1))
                          if cover_numbers else None),
                      'text_layer_characters': len(text), 'disposition': disposition})
    return audit


def write_report(payload, summary, sat, unresolved, audit, run_id):
    families = sorted(summary['families'], key=lambda f: f['family_id'])
    lines = [
        '# English (Grade 11, Papers 1 and 2) — Two-Pass Report', '',
        f'**Run:** `{run_id}` · **Status:** completed_with_review · **Generated by:** `scripts/run_english_pass2.py`', '',
        '## What was processed', '',
        f'* Pass 1 rebuilt at question level from **five verified paper+memo pairs** ({summary["question_records_in_batch"]} question records);',
        '  the inherited document-level stubs were replaced, not extended.',
        '* Pairing was verified from printed evidence only: identical DATE/MARKS/EXAMINER blocks where printed,',
        '  printed section headings, the printed cover row, and per-item bracketed marks checked in both documents.',
        '  The July 2014 Paper 2 memorandum prints no header at all, so it was paired on identical numbered content',
        '  and marks plus its Phase-2 inventory record; that fact is recorded in the record itself.',
        '* Every question record stores the SHA-256 of its paper and memorandum and the ORC source IDs resolved from',
        '  `data/raw/english/SOURCE_INVENTORY.yaml`; the builder fails closed if any of these is missing or ambiguous.',
        '* Source defects (printed totals that disagree with their own items, mis-numbered items, an absent Question 5',
        '  marking section) are declared in the batch and never padded, renamed or silently corrected.', '',
        '## Trust boundary', '',
        'Everything below is derived from the papers and memoranda in `data/organized/english`. No outside knowledge,',
        'no syllabus and no curriculum coverage is asserted. Every Tier 2/Tier 3 claim carries the source IDs it rests on',
        'and every model remains `unvalidated`, `version 0.1.0-draft`.', '',
        '## Families', '',
        '| Family | Paper | Members | Papers | Marks | Confidence |', '| --- | --- | --- | --- | --- | --- |']
    for f in families:
        lines.append(f"| {f['family_id']} — {f['name']} | {f['paper_number']} | {f['members']} | {len(f['papers'])} | "
                     f"{f['marks_range'][0]}–{f['marks_range'][1]} | {f['confidence']} |")
    lines += ['',
              f"Paper 1 (Language) and Paper 2 (Literature/Writing) competences are kept in separate families; no family",
              f"mixes the two papers. The confidence rule is the written one — high requires four or more members across",
              f"three or more papers — and it classifies {summary['confidence_distribution'].get('high', 0)} of {summary['question_families']} families as high and",
              f"{summary['confidence_distribution'].get('medium', 0)} as medium. That is more 'high' than the corpus expectation of mostly medium families: three Paper 1",
              'sittings in this batch share the same section structure, so several operations genuinely recur across three',
              'papers. The label is arithmetic, not a claim about validity, and every model stays unvalidated.', '',
              '## What was deliberately not used', '',
              f"* {sat['additional_diagnostics']['records_image_dependent']} records depend on images (advertisements, cartoons, maps, logos). Their text and memorandum answers are kept in Pass 1, but none may carry a family claim.",
              f"* {sat['additional_diagnostics']['records_without_marking_evidence']} records (three summaries, two essays, four transactional options, and the four November 2016 visual-literacy items) have no marking evidence at all; no marking requirement was invented for them.",
              '* Two records are marked against an IEB rubric that the supplied memoranda do not print; no rubric descriptors were fabricated.',
              f"* {summary['question_records_in_batch'] - summary['records_assigned_to_a_family']} records remain unassigned (a view over the batch, not a partition): the image-dependent, no-evidence and rubric-only sets above, plus five single-exemplar operations listed in the unresolved items.",
              '* The set texts are text-specific (The God of Small Things in one sitting, Othello in another), so no "theme in [text]" family was admitted.', '',
              '## Saturation', '',
              f"* `papers_in_sample`: {sat['papers_in_sample']}",
              f"* `question_families_identified`: {sat['question_families_identified']}",
              f"* `families_first_observed_in_final_third`: {sat['families_first_observed_in_final_third']} ({', '.join(sat['families_new_in_final_third'])})",
              f"* `families_supported_by_single_exemplar`: {sat['families_supported_by_single_exemplar']}",
              f"* `strata_left_unsampled`: {len(sat['strata_left_unsampled'])} strata, including every unpaired Paper 1 sitting, both unpaired Paper 2 sittings, the orphaned 2025/2026 memorandum, and the essay/transactional and visual-literacy competences.",
              '',
              '**NOT saturated.** One family (the dictionary-entry operation) is first observed in the final third of the',
              'batch, five papers sit below the recommended 8–15, and thirteen strata remain unsampled. The saturation',
              'report records this and the review queue carries the acquisition asks.', '',
              '## Review queue', '',
              f"{len(unresolved)} items were logged to `review_queue/RQ-P4-ENG-PASS2.yaml`:",
              f"{len([u for u in unresolved if u['type'] == 'single_exemplar'])} single-exemplar candidates, "
              f"{len([u for u in unresolved if u['type'] == 'contradiction'])} source contradictions, "
              f"{len([u for u in unresolved if u['type'] in {'coverage_gap', 'curriculum_gap'}] )} acquisition gaps and the fidelity/rubric items.", '',
              '## Corpus audit (all 21 organised English files)', '',
              '| File | Printed date | Marks | Cover row matches header | Disposition |', '| --- | --- | --- | --- | --- |']
    for row in audit:
        lines.append(f"| {Path(row['path']).name} | {row['printed_date'] or '—'} | {row['printed_marks'] or '—'} | "
                     f"{row['cover_row_sums_to_printed_marks'] if row['cover_row_sums_to_printed_marks'] is not None else '—'} | {row['disposition']} |")
    lines += ['',
              'The audit is the record of what each file prints. It shows that the subject prompt\'s claim that only four',
              'files print a header date is wrong for this corpus (19 of 21 print one), and that four unpaired papers print',
              'cover rows that disagree with their own header marks.', '',
              '## Method limits', '',
              '* Pass 1 transcription is manual reading of the extracted text layer; the mechanical builder only verifies',
              '  the printed anchors (headers, headings, cover rows, per-item marks), the source hashes and the ORC resolution.',
              '* Image-dependent pages were not visually inspected; their records are flagged rather than interpreted.',
              '* Pass 2 models are paper-and-memorandum derivations. They have not been checked against learner scripts or a teacher.',
              '']
    (ROOT / 'knowledge/english/ENGLISH_REPORT.md').write_text('\n'.join(lines))


def main():
    logger = RunLogger(ROOT / 'runs', phase='4-11', subject='english', agent_version='1.0.0',
                       model='arena-agent', model_provider='arena.ai')
    run_id = logger.start()
    print('run_id:', run_id)
    try:
        logger.log_event('EXTRACTION_STARTED', message='Rebuild question-level evidence; do not consume old stubs or manifest pairings.')
        for script in ['build_english_pass1.py', 'build_english_pass2.py']:
            proc = subprocess.run([sys.executable, str(ROOT / 'scripts' / script)], cwd=ROOT, capture_output=True, text=True)
            print(proc.stdout, end='')
            if proc.stderr:
                print(proc.stderr, file=sys.stderr, end='')
            if proc.returncode:
                logger.log_error(error_type='builder_failure', message=proc.stdout + proc.stderr, affected_artifact=script)
                logger.complete('failed')
                return proc.returncode
            logger.log_event('EXTRACTION_COMPLETED' if 'pass1' in script else 'VALIDATION_COMPLETED',
                             message=proc.stdout.strip(), metadata={'builder': script, 'exit_code': 0})
        batch = json.loads((ROOT / 'data/extracted/english_pass1.json').read_text())
        out = ROOT / 'knowledge/english'
        summary = json.loads((out / '_PASS2_SUMMARY.json').read_text())
        payload = json.loads((out / 'pass2_output.json').read_text())
        unresolved = json.loads((out / 'unresolved_items.json').read_text())
        sat = json.loads((out / 'saturation_report.json').read_text())
        for paper in sorted({r['paper_key'] for r in batch}):
            rs = [r for r in batch if r['paper_key'] == paper]
            logger.log_event('MEMO_ALIGNED', entity_id=paper,
                             message='Printed headers, section headings, cover totals and per-item marks verified; numbered content read.',
                             metadata={'records': len(rs), 'marks': sum(r['marks'] for r in rs),
                                       'alignment': rs[0]['memo_alignment']})
        decisions = [
            ('replace_stubs', 'Document-level records contain no usable question evidence.',
             'Rebuild five usable pairs at question level; preserve source files unchanged.', 'data/extracted/english_pass1.json'),
            ('pairing', 'The July 2014 memorandum prints no header, and the 2026-named memorandum matches nothing.',
             'Pair the header-less memorandum on identical numbered content and marks plus its inventory record; leave the orphan memo unpaired.',
             'UNRES-ENG-001'),
            ('marks_gate', 'November 2016 Q1 and July 2018 Q5 print section totals above their own item sums.',
             'Declare the shortfall in the batch and in a review item; never pad an item to close the gap.',
             'UNRES-ENG-007'),
            ('fidelity', 'All local visual-literacy evidence is image-dependent.',
             'Record the memorandum answers but exclude every image-dependent record from Pass 2 families and models.',
             'UNRES-ENG-VISUAL'),
            ('evidence_gate', 'Summaries, essays and transactional options have no model answers or rubrics.',
             'Exclude them from families; log them as coverage gaps rather than inferring marking requirements.',
             'UNRES-ENG-NO-MARKING-EVIDENCE'),
            ('competence_split', 'Paper 1 and Paper 2 test different competences, and set texts recur once each.',
             'Keep P1 and P2 families separate and admit only generic literature operations, never a single-text theme family.',
             'ingestion/analysis/english_pass2_families.py'),
            ('confidence', 'Confidence must be computed, not authored.',
             'High requires four members across three papers; image-dependent and unverified records may never be members.',
             'scripts/build_english_pass2.py'),
            ('saturation_order', 'Historical download order is not evidence for this rebuilt batch.',
             'Use the recorded order of addition to question-level Pass 1, report all thirds, and do not declare saturation.',
             'knowledge/english/saturation_report.json'),
            ('scope', 'No syllabus or ATP exists in the English sample.',
             'Keep Phase 7 and later phases out of scope; assert no curriculum coverage and label sections as printed.',
             'knowledge/english/unresolved_items.json'),
        ]
        for i, (typ, context, selected, evidence) in enumerate(decisions, 1):
            logger.log_decision(decision_id=f'DEC-ENG-{i:03d}', decision_type=typ, context=context,
                                evidence=[evidence], alternatives=['Infer or silently repair the missing evidence', selected],
                                selected=selected, rationale='Preserve provenance and distinguish source facts from unvalidated synthesis.',
                                confidence='high', requires_review=True)
        for u in unresolved:
            logger.log_event('REVIEW_REQUIRED', entity_id=u['id'], message=u['summary'],
                             metadata={'type': u['type'], 'affected': u['affected']})
            if u['type'] == 'contradiction':
                logger.log_error(error_type='source_contradiction', message=u['detail'], affected_artifact=u['affected'][0],
                                 resolution=u['recommended_review'])
        logger.log_error(error_type='saturation_not_reached', message=sat['additional_diagnostics']['reason_not_saturated'],
                         affected_artifact='knowledge/english/saturation_report.json',
                         resolution='Resolve the acquisition gaps and enlarge the evidence batch.')
        write_review_queue(run_id, unresolved)
        audit = corpus_audit(batch)
        for row in audit:
            if row['disposition'] != 'admitted':
                logger.log_event('SOURCE_SKIPPED', entity_id=row['path'], message=row['disposition'])
        (ROOT / 'data/extracted/pass1/english/_CORPUS_AUDIT.json').write_text(json.dumps(audit, indent=2) + '\n')
        write_report(payload, summary, sat, unresolved, audit, run_id)
        logger.set_metrics({'files_in_organized_sample': len(audit),
                            'question_papers_in_sample': sum(a['document_type'] == 'question_paper' for a in audit),
                            'memoranda_in_sample': sum(a['document_type'] in {'memorandum', 'orphan_memo_2026'} for a in audit),
                            'papers_processed': summary['papers_in_sample'],
                            'papers_without_local_memo': sum(a['disposition'] == 'no_matching_local_memo' for a in audit),
                            'memoranda_without_matching_paper': sum(a['disposition'] in {'no_matching_local_paper', 'rejected_no_matching_paper'} for a in audit),
                            'questions_extracted': len(batch),
                            'questions_classified': summary['records_assigned_to_a_family'],
                            'questions_unclassified': len(batch) - summary['records_assigned_to_a_family'],
                            'memo_alignment_rate': 1.0, 'curriculum_mapping_rate': None,
                            'records_requiring_visual_verification': sat['additional_diagnostics']['records_image_dependent'],
                            'understanding_models': summary['understanding_models'],
                            'breakdowns': summary['breakdown_models'],
                            'diagnostics': summary['diagnostic_questions'],
                            'unresolved_items': len(unresolved),
                            'validation_failures': 0,
                            'schema_objects_checked': summary['schema_validation']['checked']})
        status_path = ROOT / 'STATUS.md'
        status = status_path.read_text()
        new_head = f'''```yaml
current_phase: 4-11 (english Pass 1 + Pass 2; Phase 7 not run)
current_subject: english
status: completed_with_review
knowledge_bank_version: null
unresolved_items: {len(unresolved)} # current english run only; earlier subject queues remain open
last_run_id: {run_id}
next_allowed_phase: english review/acquisition and Phase 7 mapping; no automatic phase continuation
```'''
        status = re.sub(r'```yaml.*?```', lambda _: new_head, status, count=1, flags=re.S)
        status = re.sub(r'\n<!-- ENGLISH_PASS2_START -->.*?<!-- ENGLISH_PASS2_END -->\n', '\n', status, flags=re.S)
        status += f'''
<!-- ENGLISH_PASS2_START -->
## English Two-Pass — 2026-09-14

**Status:** completed_with_review · **Run:** `{run_id}`

{summary['question_records_in_batch']} question records from five verified paper+memo pairs (80 + 90 + 90 + 90 + 90 = 440 marks).
{summary['question_families']} families, {summary['understanding_models']} Understanding Models, {summary['breakdown_models']} breakdowns
and {summary['diagnostic_questions']} diagnostics; {summary['schema_validation']['checked']} objects schema-valid.
{summary['records_assigned_to_a_family']} records classified; {summary['question_records_in_batch'] - summary['records_assigned_to_a_family']} deliberately unassigned
({sat['additional_diagnostics']['records_image_dependent']} image-dependent, {sat['additional_diagnostics']['records_without_marking_evidence']} without marking evidence).
{len(unresolved)} review items. All models are `unvalidated`, `0.1.0-draft`; curriculum coverage remains unknown.

**Not saturated:** the dictionary-entry family is first observed in the final third of the batch, five papers
sit below the recommended 8–15, and thirteen strata are unsampled (every unpaired sitting, the orphaned
2025/2026 memorandum, and the essay/transactional and visual-literacy competences). The header-less July 2014
memorandum was paired on content; the July 2013 paper / 2025-26 memo stub pairing is rejected.

Full report: `knowledge/english/ENGLISH_REPORT.md`.
Entry point: `python scripts/run_english_pass2.py`; tests: `python -m pytest`.
Review queue: `review_queue/RQ-P4-ENG-PASS2.yaml`.

This supersedes the historical statement above that all non-physics subjects still have stub Pass 1
records. Physics, biology and the other subjects were not rebuilt or changed. Only english entries in the
all-subject aggregate were replaced, and the stub batch was overwritten as required. No later phase was run.
<!-- ENGLISH_PASS2_END -->
'''
        status_path.write_text(status)
        artifacts = [ROOT / 'STATUS.md', REVIEW_QUEUE, ROOT / 'data/extracted/english_pass1.json',
                     ROOT / 'data/extracted/all_subjects_pass1.json']
        for pattern in ['data/extracted/pass1/english/*.json', 'knowledge/english/*.json', 'knowledge/english/*REPORT.md',
                        'ingestion/extraction/english_pass1_evidence_*.py', 'ingestion/analysis/english_pass2_*.py',
                        'scripts/*english_pass*.py', 'tests/test_english_pass2.py']:
            artifacts.extend(ROOT.glob(pattern))
        for path in sorted(set(artifacts)):
            logger.record_artifact(str(path.relative_to(ROOT)), content_hash=sha256_file(path))
        logger.complete('completed_with_review', unresolved_items=len(unresolved))
        print(f'Run completed_with_review: runs/{run_id}')
        return 0
    except Exception as exc:
        logger.log_error(error_type=type(exc).__name__, message=str(exc))
        logger.complete('failed')
        raise


if __name__ == '__main__':
    raise SystemExit(main())
