"""Authored source defects and acquisition gaps. No source correction is assumed."""
UNRESOLVED = [
 {'type':'contradiction','summary':'2022 year-end pair fails the mandatory marks gate',
  'detail':'Paper cover and body allocate Q1=70, Q2=30, Q3=30, Q4=40: 160, but print total 170. The memo labels Q3 as 40 although its subsections are 16+9+5=30. Excluded from Pass 1 batch and Pass 2; no ten-mark balancing record was invented.',
  'affected':['data/organized/biology/Year-end exam P1.pdf','data/organized/biology/Year-end exam P1 MG.pdf'],
  'evidence':['Paper pp1,14–17,24; memo pp6–9'],
  'recommended_review':'Obtain corrected paper and memo totals or missing question material from the examiner, then extract the complete pair.'},
 {'type':'data_quality','summary':'Microorganisms memo belongs to Test 1, not Test 2',
  'detail':'Both tests print 2 October 2023 and 40 marks with 10/13/17 totals. Test 1 Q2 is the penicillin/bacterial-type investigation; its memo Q2.1 says Type of bacteria, Q2.7.B says Penicillin. Test 2 Q2.1 instead asks for a dependent variable in a Vibramycin investigation. Date matching alone is insufficient. The inventory lists a separate Test 2 MG.docx that is not present locally.',
  'affected':['data/organized/biology/Class test 2- microorganisms.pdf'],
  'evidence':['Test 1 and Test 2 pp3–4; Class test- microorganisms MG.pdf p2; SOURCE-ORC-BIO-2023-013'],
  'recommended_review':'Acquire the inventory-listed Test 2 memorandum; do not reuse the Test 1 memo.'},
 {'type':'coverage_gap','summary':'Eight locally present papers have no matching local memorandum',
  'detail':'These are not included in the marking-evidence batch; no requirements are inferred from the inherited document-level stubs.',
  'affected':['data/organized/biology/'+s+'.pdf' for s in ['Class test 2- circulation','Class test 2- microorganisms','Class test- nervous system','Class test- skeletal system','Class test- excretion and skeletal system','Grade 11 cycle test 2','Grade 11 excretion class test','November exam paper 2']],
  'evidence':['data/organized/biology','data/raw/biology/SOURCE_INVENTORY.yaml'],
  'recommended_review':'Acquire and verify each missing memorandum against the actual paper; the inventory already lists several candidates.'},
 {'type':'curriculum_gap','summary':'No syllabus or ATP in the organized biology sample',
  'detail':'The two curriculum-directory files are P2 source booklets, not curriculum specifications. Topic tags are guesses; no curriculum coverage percentage or missing CAPS topics is asserted. Phase 7 was not executed.',
  'affected':['data/organized/biology/curriculum/NOVEMBER P2 SOURCE BOOKLET.pdf','data/organized/biology/curriculum/Nove exam P2 SOURCE BOOKLET 2024.pdf'],
  'evidence':['data/organized/biology/curriculum'],
  'recommended_review':'Obtain the school Grade 11 Life Sciences syllabus/ATP before curriculum mapping or validation.'},
 {'type':'data_quality','summary':'Inventory provenance requires title plus printed year',
  'detail':'Circulation paper and MG titles recur in both 2022 and 2024 inventory entries. The builder uses normalized title and verified printed year, rejecting absent or still-ambiguous matches. Inventory access statuses and hashes have not been reconciled with organized copies.',
  'affected':['data/raw/biology/SOURCE_INVENTORY.yaml'],
  'evidence':['SOURCE-ORC-BIO-2022-001','SOURCE-ORC-BIO-2022-002','SOURCE-ORC-BIO-2024-027','SOURCE-ORC-BIO-2024-028'],
  'recommended_review':'Reconcile the Phase 3 inventory with the preserved organized files, retaining both years and URLs.'},
 {'type':'data_quality','summary':'Prompt date summary and inherited pairings are not source truth',
  'detail':'Class test 2- circulation actually prints FEBRUARY 2024 (month/year, no day), not an entirely absent date. Nervous-system and Cycle Test 2 stubs had different-sitting memos. The manifest was not used for pairing.',
  'affected':['data/organized/biology/Class test 2- circulation.pdf','data/organized/sample_manifest.json'],
  'evidence':['Circulation Test 2 p1; nervous-system paper p1; Cycle Test 2 p1'],
  'recommended_review':'Correct upstream metadata in a separately authorised acquisition run, without changing source PDFs.'},
]

# Actual question IDs are resolved by the builder, never guessed from filenames.
QUESTION_ISSUES = [
 ('contradiction','Circulation pressure explanation conflicts across marking guidelines',
  '2022 Q3.3.a attributes fluctuations to contracting/relaxing arterial walls; 2023 Q3.1.7.b instead attributes them to cardiac systole/diastole. 2022 Q3.2 says the aorta receives blood directly from the left atrium. Preserve the wording and withhold this mechanism from synthesis pending examiner review.',
  [('BIO-2022-CIRC','3.2'),('BIO-2022-CIRC','3.3.a'),('BIO-2023-NOV','3.1.7.b')]),
 ('contradiction','July memo calls a labelled bone radium',
  'July Q3.1.1 spells the bone radium; the word box in Q1.5 uses Radius. Do not silently substitute a correction.',
  [('BIO-2023-JUL','3.1.1'),('BIO-2023-JUL','1.5')]),
 ('contradiction','Excretion memo includes colon/faeces despite its metabolic-waste definition',
  'July Q1.4.2 includes Large intestine/colon–faeces; Q2.1.1 defines excretion in terms of metabolic wastes. This boundary is not resolved by the batch.',
  [('BIO-2023-JUL','1.4.2'),('BIO-2023-JUL','2.1.1')]),
 ('contradiction','Memo gives rate units for a one-hour volume',
  'November Q1.5.6 asks for volume in one hour but the memo prints 15 000 cm3/minute and no unit no mark. Retained verbatim, excluded from synthesis.',
  [('BIO-2023-NOV','1.5.6')]),
 ('contradiction','Lady-bug memo retains snail wording',
  'November Q4.3.1 asks about lady bugs but its memo answer says 20 snails caught in the first sample. The source figure also remains unverified.',
  [('BIO-2023-NOV','4.3.1')]),
 ('single_exemplar','Local partial-credit rules are not cross-paper requirements',
  'Only the microorganisms memo Q3.1.5 allows one mark for fatigue alone; only July Q1.4.5 states both entries correct for a row tick. These are independent local rules, not a shared pattern.',
  [('BIO-2023-MICRO','3.1.5'),('BIO-2023-JUL','1.4.5')]),
]
