"""Authored source defects, corpus traps and acquisition gaps for English Pass 2.

Nothing here is repaired by the builders. Every entry names the affected source
paths or records so the review queue can be audited against the corpus.
"""

UNRESOLVED = [
    {'type': 'data_quality',
     'summary': 'The 2026-named memorandum is dated 2025, disagrees with its own cover row, and is orphaned',
     'detail': '"Final of Grade 11 English Paper 1 July 2026 Memo.pdf" prints DATE 22 July 2025 in its header, so the year in its filename is wrong, and its printed cover row (20+10+15+10+20+10) sums to 85 against a header of MARKS 80. Neither discrepancy can be settled from the file, and no question paper for that sitting exists in the corpus: no local paper matches its numbered content (a World Cup article comprehension and a voting-speech summary). It was not paired with anything, and no question record was created from it. The trap in the subject prompt — that the document-level stubs paired the July 2013 paper with this 2025/2026 memo — is real and is rejected here on content, not on filename.',
     'affected': ['data/organized/english/Final of Grade 11 English Paper 1 July 2026 Memo.pdf'],
     'evidence': ['Memo p1 header and cover row; memo items 1.1-1.6 and 2; no matching paper in data/organized/english'],
     'recommended_review': 'Ask the department which sitting this memorandum belongs to, correct the printed total or locate the missing question paper, then extract the pair.'},
    {'type': 'coverage_gap',
     'summary': 'Ten locally present papers have no matching local memorandum',
     'detail': 'These papers are readable and print dated headers, but no memorandum for their sitting exists in the organised sample, so no question record was created and no marking requirement was inferred. Some also carry printed total conflicts that would need to be resolved before extraction: July 2015 P1 (cover row 30+10+20+20+15=95 against MARKS 90), July 2016 P1 (printed row parses as 45+10+20+20=95 against MARKS 90), November 2018 P1 PDF (25+10+20+20+10=85 against MARKS 90) and July 2017 P2 (30+30+20=80 against MARKS 90).',
     'affected': ['data/organized/english/Grade 11 English Paper 1 July 2013.docx',
                  'data/organized/english/Grade 11 Paper 1 July 2014.docx',
                  'data/organized/english/Grade 11 English P1 July 2015.docx',
                  'data/organized/english/Grade 11 English P1 July 2016.docx',
                  'data/organized/english/Grade 11 English Paper 1 July 2017.docx',
                  'data/organized/english/Grade 11 Paper 1 Nov 2014.docx',
                  'data/organized/english/Grade 11 English P1 Nov 2015.docx',
                  'data/organized/english/Grade 11 Paper 1 November 2018 .pdf',
                  'data/organized/english/Grade 11 English Paper 2 July 2016.docx',
                  'data/organized/english/Grade 11 Paper 2  July 2017.docx'],
     'evidence': ['data/organized/english', 'data/raw/english/SOURCE_INVENTORY.yaml'],
     'recommended_review': 'Acquire the matching memorandum for each sitting and verify it against the paper before extraction; resolve each printed total conflict with the examiner rather than by arithmetic.'},
    {'type': 'data_quality',
     'summary': 'Inherited document-level stub pairings were wrong and were not used',
     'detail': 'The stub batch paired the July 2013 paper with the 2025/2026 memorandum and carried no question-level evidence at all. This run rebuilt Pass 1 from printed headers, numbered content, printed totals and source hashes; the manifest at data/organized/sample_manifest.json was not consulted. The stubs are replaced by the question-level batch.',
     'affected': ['data/extracted/english_pass1.json', 'data/organized/sample_manifest.json'],
     'evidence': ['Old stub batch; printed content of both documents'],
     'recommended_review': 'Correct upstream manifest metadata in a separately authorised run; do not change the preserved source files.'},
    {'type': 'data_quality',
     'summary': 'The subject prompt understates how many files print a date',
     'detail': 'SUBJECT_PROMPTS.md states that only four English files print a DATE in the header block. The mechanical corpus audit finds a dated header block in 19 of the 21 files; only "Grade 11 English Paper 1 July 2013.docx" and "Grade 11 Paper 2 July Memo.docx" print none. Pairing therefore used the printed header wherever it existed, and content plus printed totals for the 2014 P2 memorandum, which has no header at all.',
     'affected': ['SUBJECT_PROMPTS.md', 'data/organized/english'],
     'evidence': ['Corpus audit generated at data/extracted/pass1/english/_CORPUS_AUDIT.json'],
     'recommended_review': 'Treat the prompt sentence as incorrect for this corpus and keep the corpus audit as the record of what each file prints.'},
    {'type': 'data_quality',
     'summary': 'The subject prompt reverses the Paper 1 and Paper 2 competences as they appear in this corpus',
     'detail': 'SUBJECT_PROMPTS.md describes Paper 1 as "comprehension/contextual questions on set texts" and Paper 2 as "language". In the organised files it is the other way round: every Paper 1 in the batch (July 2018, November 2016 and November 2017, plus the unpaired Paper 1 sittings) opens with a comprehension of a news text, then a summary, a poetry section, visual literacy and textual editing, while every Paper 2 (July 2014 and July 2015) carries the set-work contextual questions, the literature essay and transactional writing. The one genuine overlap is that the Paper 1 poetry section is contextual work on set poems, which is why the competence split in this batch was made per record (paper_type Language / Literature / Writing) rather than from the prompt wording.',
     'affected': ['SUBJECT_PROMPTS.md',
                  'data/organized/english/Grade 11 Paper 1 July 2018.pdf',
                  'data/organized/english/Grade 11 Paper 2 July 2015.docx'],
     'evidence': ['Printed question 1 of the three admitted Paper 1 papers; printed section headings of the two admitted Paper 2 papers'],
     'recommended_review': 'Correct the prompt wording and keep the per-record competence labels as the record of what each paper tests.'},
    {'type': 'coverage_gap',
     'summary': 'Each set text occurs in one sitting only, so text-specific families are single-exemplar',
     'detail': 'The God of Small Things appears only in the July 2014 Paper 2 pair and Othello only in the July 2015 Paper 2 pair. Hamlet and Gatsby recur only in papers whose memoranda are absent. A family such as "theme in The God of Small Things" would therefore rest on one paper, which the prompt forbids for evidence-bearing families. Only generic operations (character motive and change, recall of a stated event, close reading of an extract) were admitted, and the Paper 1 and Paper 2 competences were kept in separate families.',
     'affected': ['data/organized/english/Grade 11 Paper 2 July 2014.docx',
                  'data/organized/english/Grade 11 Paper 2 July Memo.docx',
                  'data/organized/english/Grade 11 Paper 2 July 2015.docx',
                  'data/organized/english/Grade 11 Paper 2 July 2015 Memo.docx'],
     'evidence': ['Set-text sweep of all 21 files; families in ingestion/analysis/english_pass2_families.py'],
     'recommended_review': 'Acquire further memoranda for the same set texts (2014-2016) before admitting text-specific theme families.'},
    {'type': 'curriculum_gap',
     'summary': 'No syllabus or ATP in the English sample',
     'detail': 'The organised English sample contains papers and memoranda only. No Grade 11 English syllabus, ATP or assessment programme is present, so no curriculum coverage percentage, no missing-topic claim and no Phase 7 mapping is asserted. Topic labels in this batch are the sections printed on the papers themselves.',
     'affected': ['data/organized/english'],
     'evidence': ['data/organized/english contains no curriculum directory'],
     'recommended_review': 'Obtain the school Grade 11 English syllabus/ATP before any curriculum mapping or validation.'},
]

# (type, title, detail, [(paper_key, question_number), ...]) — resolved to source IDs by the builder.
QUESTION_ISSUES = [
    ('contradiction', 'November 2016 Paper 1 Question 1 prints 26 marks but its items allocate 25',
     'The section heading and cover row say 26 marks while items 1.1-1.9 allocate 3+1+2+2+2+3+3+2+3+4 = 25 in both the paper and the memorandum. The missing mark is left unallocated and the shortfall is declared in the batch; the per-item marks that the families use are consistent in both documents.',
     [('ENG-2016-NOV-P1', '1.1')]),
    ('contradiction', 'July 2018 Paper 1 Question 5 prints 25 marks but its items allocate 24',
     'Items 5.1-5.8 allocate 2+3+2+2+2+3+2+5+3 = 24 against the printed 25. All Question 5 records are visual-dependent and are excluded from Pass 2 families, but the printed shortfall is preserved rather than padded.',
     [('ENG-2018-JUL-P1', '5.1')]),
    ('data_quality', 'July 2018 Paper 1 prints the textual-editing section as Question 6 but numbers its items 5.1-5.5',
     'The paper and the memorandum both head the section "QUESTION 6 10 MARKS" and then number its items 5.1-5.5. The batch records the logical numbers 6.1-6.5 and stores the printed number separately; nothing is silently renumbered in the source.',
     [('ENG-2018-JUL-P1', '6.1')]),
    ('data_quality', 'July 2015 Paper 2 memorandum numbers the last extract question 1.7 twice',
     'The paper numbers the final Othello item 1.8 while the memorandum repeats 1.7 for the prayer question. The record keeps the logical number 1.8 with its printed mark, read from the content.',
     [('ENG-2015-JUL-P2', '1.8')]),
    ('fidelity', 'November 2016 Paper 1 memorandum has no Question 5 marking section at all',
     'The memorandum restates Questions 1, 2, 3, 4 and 6 but prints no marking guidance for the 15-mark visual-literacy question. Those four records retain their question text and marks with no memo answer, and cannot ground any marking requirement.',
     [('ENG-2016-NOV-P1', '5.1'), ('ENG-2016-NOV-P1', '5.2')]),
    ('rubric_gap', 'Two records are marked by an IEB rubric that the memorandum does not print',
     'The November 2016 memorandum ends one answer with "Use IEB rubric." and the July 2014 memorandum answers its 6-mark paragraph with "Mark for relevance and quoting from the extracts provided." Neither memorandum prints the rubric descriptors, so no rubric level criteria can be transcribed and neither record is used as family evidence.',
     [('ENG-2016-NOV-P1', '1.8'), ('ENG-2014-JUL-P2', '1.10')]),
    ('coverage_gap', 'Summary, essay and transactional records carry no marking evidence',
     'The three Paper 1 summaries (2016, 2017 and 2018) are restated without model answers or rubrics, and the 2014 and 2015 Paper 2 memoranda mark only the set-work question: the essay and the transactional options have no model answers, checklists or rubrics. These nine records cannot ground a breakdown model and are excluded from families.',
     [('ENG-2016-NOV-P1', '2.1'), ('ENG-2017-NOV-P1', '2.1'), ('ENG-2018-JUL-P1', '2.1'),
      ('ENG-2014-JUL-P2', '2.1'), ('ENG-2014-JUL-P2', '3.1'),
      ('ENG-2015-JUL-P2', '2.1'), ('ENG-2015-JUL-P2', '3.1'),
      ('ENG-2015-JUL-P2', '3.2'), ('ENG-2015-JUL-P2', '3.3')]),
]

# (type, title, [(paper_key, question_number), ...]) — candidates seen once only.
DEFERRED = [
    ('single_exemplar', 'Explain why a writer doubts a claim made in the text',
     [('ENG-2017-NOV-P1', '1.3')]),
    ('single_exemplar', 'Infer what a writer\'s own words reveal about how they see themselves',
     [('ENG-2017-NOV-P1', '1.9')]),
    ('single_exemplar', 'Name the figure of speech used in a line, with no effect required',
     [('ENG-2017-NOV-P1', '3.7.1')]),
    ('single_exemplar', 'Recall a single quoted word that carries a stated attitude',
     [('ENG-2017-NOV-P1', '3.8')]),
    ('single_exemplar', 'Define a movement or term in the candidate\'s own words',
     [('ENG-2018-JUL-P1', '1.1')]),
]
