"""Tier 2 understanding models and Tier 3 possible failures/diagnostics (English).

Each entry scopes its claims to the members of its family. The builder appends
explicit source IDs to every substantive field, so no claim is published without
at least two independent sources behind it. Nothing here has been validated on
learners; the states are the paper-and-memorandum evidence only.

Marking lines paraphrase what the supplied memoranda actually credit, including
their own hedges (for example the 2016 P1 memo requiring quotation before an IEB
rubric is applied, and the 2015 P2 memo's instruction to mark relevance and
quoting). Nothing is imported from outside the batch.
"""

MODELS = {
    1: dict(
        knowledge='Register, tone and word choice are named from the text itself (informal or colloquial register, tongue-in-cheek or harsh tone, connotation of a specific word), not from a general list of devices.',
        prerequisites='Read the specified paragraph or sentence and locate the words the question points at before labelling the style.',
        reasoning='Move from the named feature to what it does to the reader or to the message, so that a label such as "informal" is completed by an effect.',
        procedure='Quotethe word or phrase; name the register, tone or connotation; state the effect on the reader or the message in the context of this text.',
        evidence='a named feature supported by a quotation, followed by an effect that belongs to this text rather than to writing in general.',
        marking='The memoranda credit the label and the effect together: the 2016 paper asks for an example of informal language and its effectiveness, the 2017 memo answers with the informal diction, its quotation and the tone it creates before naming the intention, and the 2018 memo rewards an identification of colloquial register with its effect on reader and message. One-part answers that stop at "informal language" or at the effect without the textual detail do not collect the full allocation.',
        misconception='The register label alone is treated as the answer, so the effect is never stated.',
        breakdowns=[('interpretation',
                     'Names the register correctly but attaches a generic effect, e.g. "makes it interesting", that is not tied to this text.',
                     'Can quote the language but cannot connect it to the message or the reader in this paragraph.'),
                    ('concept',
                     'Uses the wrong style term for the evidence quoted (for example calls a colloquial paragraph formal), or treats connotation as a synonym list.',
                     'Supplies a term that contradicts the quotation offered.')],
        diagnostics=[('Which words in this paragraph create the style you are naming, and what would the sentence lose without them?',
                      'Points to the actual words and can state a loss in effect rather than repeating a label.'),
                     ('How does the effect you have named relate to what the writer is trying to do in this text?',
                      'Links the stylistic effect to the writer\'s purpose instead of to a general claim about good writing.')]),

    2: dict(
        knowledge='The named error types recur across the batch: split infinitive, concord, spelling, tautology, missing finite verb and a dangling preposition are each printed in a supplied sentence.',
        prerequisites='Read the whole sentence and locate the specific element the memorandum corrects; the question asks for one error, not a rewrite.',
        reasoning='Match the sentence against the grammatical rule the error breaks, then produce the minimal correction the memo accepts.',
        procedure='Name the error; write the corrected word or phrase; leave the rest of the sentence as printed.',
        evidence='An identified error named in the memorandum\'s own terms plus a correction that changes only the faulty element.',
        marking='The memoranda mark identification and correction as separate ticks (split infinitive, concord, spelling, tautology, dangling preposition and missing finite verb all print a corrected form). Where two mistakes are required, one mark is attached to each word, and the memo accepts any suitable correction of the fragment, so the correction must address the stated error rather than improve the sentence in general.',
        misconception='Any change that makes the sentence read better is accepted as the correction, even if the named error remains.',
        breakdowns=[('concept',
                     'Corrects a different word from the one carrying the error or names the wrong error type.',
                     'The corrected sentence still contains the printed error.'),
                    ('execution',
                     'Identifies the error correctly but writes a correction that is not minimal or not accurate (wrong concord form, misspelling of the correction).',
                     'Names the error yet the rewritten element does not match the memo.')],
        diagnostics=[('What rule is broken in this sentence, and which words break it?',
                      'Names the rule and isolates the offending words rather than paraphrasing the sentence.'),
                     ('Change as little as possible: what is the smallest correction that repairs this sentence?',
                      'Produces a minimal correction instead of rewriting the whole sentence.')]),

    3: dict(
        knowledge='The features the memoranda credit here are syntactic and punctuation-level: repetition and commas, active versus passive voice, hyphenation, capitalisation and compound sentence structure with a misrelated participle.',
        prerequisites='Identify the sentence or clause the question points at and separate its construction from its content.',
        reasoning='Explain what the construction emphasises, speeds up, slows down or clarifies in this sentence before naming the effect on the reader.',
        procedure='Name the feature; show what it does in this sentence; state the effect on meaning, emphasis or the reader.',
        evidence='A named construction tied to a specific sentence, with an effect that follows from it rather than from the topic of the passage.',
        marking='The memoranda reward the function, not the label: the 2016 memo names the repetition and the work of the commas, the same memo explains that the active voice keeps the paragraph\'s "real people" as the subject and focus, the 2017 memo answers with the function of the hyphen, and the 2018 memo credits capitals for status and respect and a compound sentence with a misrelated participle for the effect it has on the reader.',
        misconception='The punctuation mark or sentence type is named and described grammatically, but no consequence for meaning is stated.',
        breakdowns=[('interpretation',
                     'Describes the sentence structure accurately but stops before saying what it does to the emphasis or meaning.',
                     'Can label the construction, cannot state an effect.'),
                    ('concept',
                     'Reads a stylistic effect into punctuation that is doing ordinary grammatical work, or misses that the construction is the point of the question.',
                     'Claims an effect the sentence cannot support.')],
        diagnostics=[('What changes in this sentence if you remove or reverse the feature you have named?',
                      'Demonstrates the feature\'s work by contrast rather than repeating its name.'),
                     ('Which single word in the sentence benefits most from the emphasis you describe?',
                      'Ties the effect to a specific element of the sentence.')]),

    4: dict(
        knowledge='Poetic language items in the batch turn on simile, metaphor, personification, connotation and tone in named lines or stanzas.',
        prerequisites='Locate the line or stanza and identify the device or the connotative word before explaining it.',
        reasoning='Unpack what the comparison or word actually conveys in this poem rather than naming the device and stopping.',
        procedure='Quote the device; name it; say what it conveys about the subject; state the effect on the poem\'s mood or argument.',
        evidence='A device or connotation with its local meaning, expressed in terms of what the poem is doing rather than a dictionary definition.',
        marking='The memoranda list acceptable images and then require their connotations to be discussed (the 2016 memo offers several religious images and credits the connotation of the one chosen; the 2017 memo asks what the connotation of a single word implies; the 2018 memo credits an account of a simile\'s effectiveness). Naming is worth a mark only when an effect is added; the 2016 mark for the personification and simile pair is carried by the drought they emphasise.',
        misconception='The figure of speech is named as if naming it were the analysis.',
        breakdowns=[('concept',
                     'Names the wrong device or interprets the image literally (for example reads "police cars cockroach through the streets" as information about insects).',
                     'The stated device or meaning contradicts the quoted line.'),
                    ('interpretation',
                     'Names the device correctly but gives a general emotional label such as "sad" without saying what the image conveys.',
                     'The effect is not derived from the quoted words.')],
        diagnostics=[('What exactly is being compared with what in this line, and which word carries the comparison?',
                      'Identifies both terms of the comparison from the line itself.'),
                     ('What does the poem lose if this image is replaced with a plain statement?',
                      'Explains the work the image does rather than restating its content.')]),

    5: dict(
        knowledge='The batch tests line arrangement, enjambment, stanza structure, repetition and punctuation as carriers of meaning and pace.',
        prerequisites='Identify the structural feature in the named stanza or line before interpreting it.',
        reasoning='Connect the shape of the poem on the page (short lines, enjambment, balanced stanzas, punctuation) to the action or feeling it conveys.',
        procedure='Name the structural feature; describe what it does mechanically in this poem; state the meaning, pace or mood it produces.',
        evidence='A structural observation linked to a specific effect in this poem, not a description of the stanza\'s content.',
        marking='The memoranda credit the movement from form to effect: the 2016 memo answers with the short lines and listing that quicken the pace of the stanza, the 2017 memo credits enjambment with fluid and slow movement and credits repetition and sentence structure with the final stanza\'s meaning, and the 2018 memo credits punctuation and parenthesis with their effect on the poet\'s purpose and with inverted word order that stresses a particular word and forces the reader to pause.',
        misconception='Restating what the stanza says is offered as an answer to how the poem is structured.',
        breakdowns=[('interpretation',
                     'Describes the stanza\'s content or mood but does not name the structural feature the question asks about.',
                     'Answers about meaning only, with no structural observation.'),
                    ('concept',
                     'Treats a structural device as decoration, so the effect is unconnected to the pace or meaning, or confuses enjambment with punctuation.',
                     'The named structure does not exist at the cited line.')],
        diagnostics=[('Where does this stanza speed up or slow down, and which line break or punctuation mark causes it?',
                      'Points to a specific break or mark and connects it to pace.'),
                     ('If you rewrote this stanza as one long sentence, what would change?',
                      'Articulates the function of the structure by contrast.')]),

    6: dict(
        knowledge='Comparative items require two named poems and evidence from each; in this batch the points of comparison are the presentation of hope, the images used for a beggar figure and the effect of structure on mood.',
        prerequisites='Recognise both poems named in the question and recall at least one usable detail from each.',
        reasoning='State the point of comparison rather than describing each poem in turn, then support each side of the comparison separately.',
        procedure='Name the poems; state what is being compared; quote or cite each poem; draw the comparison to a close.',
        evidence='A comparison that quotes both poems and states a relationship between them.',
        marking='The memoranda require both sides: the 2016 memo answers the hope question by treating both poems and even links water to Mandela, the 2017 memo requires two images from each poem, and the 2018 memo divides its four marks across each poem\'s structure, the two moods and the required quotation.',
        misconception='A full answer on the first poem plus a mention of the second poem is treated as a comparison.',
        breakdowns=[('strategy',
                     'Writes about one poem at length and adds a token sentence about the other.',
                     'Quotations come from one poem only.'),
                    ('execution',
                     'Discusses both poems but never states the point of comparison, or quotes without naming the relationship.',
                     'Two paraphrases sit side by side without a link.')],
        diagnostics=[('What single sentence states the difference or similarity you are arguing?',
                      'Produces a comparative claim rather than two summaries.'),
                     ('Which quotation from each poem will you use, and what does each prove?',
                      'Selects evidence from both poems and assigns work to each quotation.')]),

    7: dict(
        knowledge='Character items in the batch ask for a motive, a change over the whole work, or the allocation of responsibility, in The God of Small Things and Othello.',
        prerequisites='Know who the named character is, what happens to them outside the printed extract, and what the question asks about them.',
        reasoning='Explain the character\'s conduct or change through reasons drawn from the work as a whole, keeping the focus on the named character where the question requires it.',
        procedure='Answer the question about the character; give a reason grounded in the work; support it with a specific moment from outside the extract where relevant.',
        evidence='A reason for the character\'s conduct or change with supporting detail from the work as a whole.',
        marking='The memoranda credit reasons, not summaries: the 2014 memo explains Vellya Paapen\'s conflict between loyalty and love and explains how Mammachi\'s revulsion undermines her claim about Christian munificence; the 2015 memo answers the change-in-character question with an earlier and a later portrait of Othello and adds the explicit instruction that the answer must focus on Othello\'s change, not on Iago\'s manipulation; the responsibility question asks for a position on Iago\'s role supported from the play.',
        misconception='Retelling the plot of the extract demonstrates understanding of the character.',
        breakdowns=[('strategy',
                     'Answers a neighbouring question — for example explains Iago\'s manipulation when the question asks about Othello\'s change.',
                     'The response is relevant to the text but not to the character or change asked about.'),
                    ('execution',
                     'Gives a defensible reason but supports it only from the printed extract, or names no specific moment from the work as a whole.',
                     'The claim is asserted without the required wider-work evidence.')],
        diagnostics=[('What does this character want in this moment, and what are they afraid of?',
                      'States a motive rather than describing the action.'),
                     ('Which moment of the work, outside this extract, best shows the change or motive you are describing?',
                      'Selects a specific moment from the wider text and connects it to the claim.')]),

    8: dict(
        knowledge='Recall items in the batch ask about a specific coinage, relationship, reported information or list of grievances in the set works.',
        prerequisites='Know the events and relationships the extract refers to; the terms may be the text\'s own coinages.',
        reasoning='Answer with the specific item the question names rather than with a general theme of the text.',
        procedure='Identify what is being asked; state the event, relationship or term, using the text\'s own wording where it is a coinage; add the brief context the marks require.',
        evidence='A precise statement of the requested fact in the text\'s terms.',
        marking='The memoranda credit the specific answer: the 2014 memo sets out the two "Returnings" behind "re-Returned", answers the twin question as "twins/siblings", names the affair between Ammu and Velutha and lists Ammu\'s three offences; the 2015 memo names the cause of Desdemona\'s death and the reason Othello gives. A thematic answer that misses the named fact has nothing to credit.',
        misconception='Any related information about the extract answers a question that names one specific fact.',
        breakdowns=[('concept',
                     'Substitutes a related fact for the one named, or misremembers the relationship between characters.',
                     'Names the wrong event or relation with confidence.'),
                    ('execution',
                     'Knows the fact but states it without the context the marks require (for example the coinage\'s two stages).',
                     'Gives a bare phrase where the memo\'s answer has two or three parts.')],
        diagnostics=[('In one sentence, what exactly does the question ask you to identify?',
                      'Restates the requested fact rather than the topic of the extract.'),
                     ('Which words in this extract tell you that this is the event being referred to?',
                      'Locates the textual anchor for the recall answer.')]),

    9: dict(
        knowledge='Close-reading items in the set works ask for the meaning of a quoted image, statement or relationship inside the printed extract.',
        prerequisites='Locate the quoted words in the extract and identify who is speaking or acting.',
        reasoning='Move from the quoted words to their meaning in the world of the text, including the values or beliefs they expose.',
        procedure='Quote the words; explain what they mean here; where asked, explain what they reveal about the society or relationship in the text.',
        evidence='An interpretation of specific quoted words in the extract, with the quotation reproduced.',
        marking='The memoranda credit quotation together with explanation: the 2014 memo answers the spiritual-connection question with quoted sensory detail, and the caste-system question is answered by naming irrational generalised stereotyping and accepting any suitable supporting quotation; the 2015 memo unpacks the rose image and the paradox of loving after death.',
        misconception='The quotation is offered as the answer, without an explanation of what it means.',
        breakdowns=[('execution',
                     'Quotes accurately but does not explain the words, or explains without quoting.',
                     'One half of the required pair is missing.'),
                    ('interpretation',
                     'Offers an explanation the quotation cannot support, or reads a metaphor literally.',
                     'The stated meaning is not located in the quoted words.')],
        diagnostics=[('Which exact words from the extract are you interpreting?',
                      'Selects a quotation instead of paraphrasing the passage.'),
                     ('What do those words tell you about how this character or society sees the world?',
                      'Connects the quotation to a value or belief rather than repeating its content.')]),

    10: dict(
        knowledge='Dictionary-entry items require the components the question names: part of speech, definition and sometimes etymology, for a word as used in the supplied text.',
        prerequisites='Read the word in its paragraph and decide what it means there, not in isolation.',
        reasoning='Match the word to a part of speech and write a definition that fits the printed context, adding the origin where the question asks for it.',
        procedure='Give the word; mark the part of speech; write the contextual definition; add the requested origin for the coinage.',
        evidence='All requested components present and consistent with the context of the text.',
        marking='Each requested component is allocated separately: the 2017 memo credits a noun label and a contextual definition; the 2018 memo requires part of speech, definition and etymology, and its credited answer explains that the hashtag is coined as a social-media handle. A definition that ignores the context, or a missing component, loses that component\'s mark.',
        misconception='A general definition of the word is given when the question asks for its meaning in this text.',
        breakdowns=[('concept',
                     'The part of speech is misidentified, or the definition does not match the word\'s use in the paragraph.',
                     'The entry would not fit the printed sentence.'),
                    ('execution',
                     'A required component is omitted (no etymology where asked) or is embedded so vaguely that it cannot be credited.',
                     'Components are missing rather than wrong.')],
        diagnostics=[('In this sentence, what job does the word do — what kind of word is it?',
                      'Identifies the grammatical class from the sentence.'),
                     ('What would a reader who only had this paragraph understand the word to mean?',
                      'Writes a contextual definition rather than a general one.')]),

    11: dict(
        knowledge='Evaluation items ask for a position on reliability, positioning or success, and the memoranda accept more than one defensible position provided it is supported from the text.',
        prerequisites='Identify the claim or campaign being evaluated and the evidence the text itself supplies.',
        reasoning='Weigh the supplied evidence, take a position, and answer the question actually asked (how reliable, how successful, how positioned) rather than describing the text.',
        procedure='State the position; give the textual evidence for it; where the question allows, state the counter-position and why it is not taken.',
        evidence='A stated judgment with the specific textual evidence that supports it.',
        marking='The memoranda reward supported judgment and explicitly allow either side: the 2016 memo models Stein\'s answer from the extract and then compares it with Brooks, the 2017 memo allows the opinion to be called unreliable or reliable depending on the support offered, and the 2018 memo credits an evaluative answer about the campaigns\' limits with its own counter-consideration noted.',
        misconception='Summarising the article or campaign is treated as evaluating it.',
        breakdowns=[('strategy',
                     'Describes what the text says instead of judging reliability, positioning or success.',
                     'No position is taken.'),
                    ('interpretation',
                     'Takes a position but supports it with evidence that does not bear on the judgment, or ignores the counter-evidence the memo allows.',
                     'The evidence and the judgment are unrelated.')],
        diagnostics=[('What exactly are you judging, and what is your judgment in one sentence?',
                      'States the object and the position rather than summarising.'),
                     ('Which evidence in the text would someone who disagrees with you use, and how do you answer it?',
                      'Engages the strongest contrary evidence instead of ignoring it.')]),

    12: dict(
        knowledge='Idiom items ask what a fixed expression means in its paragraph, and one item asks how an altered expression differs from the standard one.',
        prerequisites='Locate the expression in the paragraph and recognise it as a fixed or altered form.',
        reasoning='Translate the idiom into its contextual meaning, and where the form is altered, explain what the alteration does to the meaning.',
        procedure='Quote the expression; explain its meaning here; for the altered form, set the standard expression beside it and state the difference and the writer\'s reason.',
        evidence='A contextual gloss of the expression, extended to the difference between forms where the question asks.',
        marking='The memoranda credit the meaning and the effect: the 2016 memo answers the idiom with the writer\'s agreement and answers the altered expression with the connotations of both forms and the writer\'s motive for choosing the first; the 2017 memo credits the shift from the idiomatic to the literal sense across the two paragraphs; the 2018 memo credits the idiom as naming and shaming men of power.',
        misconception='A literal reading of the idiom is offered as its meaning.',
        breakdowns=[('concept',
                     'Gives a general definition of the idiom rather than its meaning in this passage, or misses that the expression has been altered.',
                     'The answer could belong to any text.'),
                    ('execution',
                     'Explains one form but not the other when the question asks for a comparison of the two.',
                     'Only half of the required contrast is present.')],
        diagnostics=[('What does this expression mean in this sentence — who is doing what to whom?',
                      'Glosses the idiom in the paragraph\'s terms.'),
                     ('This expression comes from a standard form: what has changed, and what does the change do?',
                      'Identifies the alteration and its effect instead of treating the expression as fixed.')]),

    13: dict(
        knowledge='Metaphor items ask what a comparison implies about its subject: an orchid generation, a cartoon strongman, and earthquake shockwaves.',
        prerequisites='Recognise that a comparison is being made and identify both sides of it.',
        reasoning='Carry the source image\'s qualities across to the subject, then state the implication the writer wants the reader to accept.',
        procedure='Name the comparison; list the qualities it imports; state what it implies about the subject in this text.',
        evidence='An implication derived from the image\'s own qualities, expressed as a claim about the subject.',
        marking='The memoranda credit the unpacked comparison: the 2016 memo answers the orchid metaphor with fragility and difficulty of maintenance, the 2017 memo answers the Popeye reference by identifying the character and applying the swelling brain image, and the 2018 memo answers "shockwaves" with the earthquake sense and the scale and reach of the abuse.',
        misconception='The image is decoded as a code word (orchid = young people) without any qualities being transferred.',
        breakdowns=[('concept',
                     'Identifies only one side of the comparison or substitutes an unrelated association.',
                     'The qualities transferred are not the image\'s.'),
                    ('interpretation',
                     'Lists the image\'s qualities but never states the implication for the subject.',
                     'Description of the image replaces the claim about the subject.')],
        diagnostics=[('What kind of thing is the writer comparing the subject to, and what is it like?',
                      'Names both sides of the comparison and some qualities of the image.'),
                     ('What does the writer want you to believe about the subject once you accept that comparison?',
                      'States the implication rather than the image.')]),

    14: dict(
        knowledge='Poetry-meaning items ask for a central message, a title\'s effectiveness or the meaning of a stated idea, and the memoranda consistently require quotation.',
        prerequisites='Read the whole poem named and locate the lines that carry the message.',
        reasoning='State the poem\'s idea in a sentence and then attach the lines that establish it, rather than paraphrasing the stanza.',
        procedure='State the message or idea; quote the line(s) that support it; where a title is asked about, tie its meaning to the poem\'s content.',
        evidence='A stated reading of the poem with quotations, and in title questions a reason why the title fits the content.',
        marking='The memoranda reward the reading and the quotation together: the 2016 memo requires quotation in the Mandela contrast and answers the title question by quoting the blessing of water; the 2017 memo credits the wordplay of composition/decomposition with the poem\'s message and expects quotation; the 2018 memo credits an explanation of a compressed expression and requires substantiation and reference to the poem in the title and addressee questions.',
        misconception='A summary of the poem\'s events or a statement of its mood is offered as its message.',
        breakdowns=[('strategy',
                     'Paraphrases the poem stanza by stanza instead of stating a message.',
                     'No single reading is asserted.'),
                    ('execution',
                     'States a defensible message but supports it with no quotation, or quotes lines that carry a different idea.',
                     'The reading and its evidence do not match.')],
        diagnostics=[('Complete this sentence: the poem\'s message is that ...',
                      'Produces one claim about the whole poem.'),
                     ('Which line is doing the most work in your reading, and what would be lost if it were removed?',
                      'Selects evidence that carries the stated reading.')]),

    15: dict(
        knowledge='Opening and rhetorical devices in the batch are a rhetorical question, an opening sentence whose appropriateness is judged, and a rhetorical question whose effectiveness is explained.',
        prerequisites='Recognise the device and locate it at the start of the text or paragraph.',
        reasoning='Explain what the device does for the reader and the writer\'s purpose, not merely what a rhetorical question is.',
        procedure='Name the device and where it occurs; state its effect on the reader; connect it to the writer\'s purpose or the column\'s argument.',
        evidence='An effect of the opening move tied to the writer\'s purpose in this text.',
        marking='The memoranda credit effect and purpose: the 2016 memo judges the opening sentence by its conversational style, its use of a quotation and the writer\'s purpose of raising awareness; the 2017 memo explains that the opening question points to the ridiculousness of the question and involves the reader; the 2018 memo credits a rhetorical question with raising awareness and prompting action.',
        misconception='The definition of the rhetorical device is offered instead of its effect.',
        breakdowns=[('concept',
                     'Treats a rhetorical question as a genuine question to be answered with information from the text.',
                     'Supplies factual content instead of an effect.'),
                    ('interpretation',
                     'States a general "engages the reader" effect without tying it to this text\'s purpose.',
                     'The effect could belong to any opening.')],
        diagnostics=[('What response does this opening move try to produce in a reader who meets it first?',
                      'Names an effect attributable to this opening.'),
                     ('How does that effect serve the writer\'s purpose in this piece?',
                      'Connects the opening to the text\'s argument or aim.')]),
}
